fontc/src/main.rs
fontir/src/error.rs
fontir/src/filestate.rs
fontir/src/ir.rs
fontir/src/source.rs
resources/testdata/WghtVar-Bold.ufo/glyphs/contents.plist
resources/testdata/WghtVar-Bold.ufo/glyphs/plus.glif
resources/testdata/WghtVar-Regular.ufo/glyphs/contents.plist
resources/testdata/WghtVar-Regular.ufo/glyphs/plus.glif
ufo2fontir/Cargo.toml
ufo2fontir/src/source.rs

Provide a set of Path:DesignSpaceLocation(s) to the create IR function. Intended to leave us in a good position to actually build glyph IR.

Provide the location when creating glif work

---

fontc/src/main.rs
fontir/Cargo.toml
fontir/src/error.rs
fontir/src/lib.rs
fontir/src/serde.rs
fontir/src/source.rs
fontir/src/stateset.rs
ufo2fontir/src/source.rs

Intended use is to capture slices from .glyphs files so we can see things like which glyphs have changed since the prior compile (wip of this in #21)

Add the ability to capture the state of a slice.

---

Cargo.toml
fontir/src/serde.rs
fontir/src/stateset.rs
glyphs-reader/Cargo.toml
glyphs-reader/README.md
glyphs-reader/plist_derive/Cargo.toml
glyphs-reader/plist_derive/src/lib.rs
glyphs-reader/src/font.rs
glyphs-reader/src/from_plist.rs
glyphs-reader/src/lib.rs
glyphs-reader/src/plist.rs
glyphs-reader/src/to_plist.rs
glyphs2fontir/Cargo.toml
glyphs2fontir/src/lib.rs
glyphs2fontir/src/source.rs
resources/testdata/infinity.glyphs

Grab Raph's plist-derive glyphs-reading, tweak it to support Hash, and use hash on types to track fragments of Glyphs files instead of relying on slices of the raw string.
Fixes #23 .

Use hashable types and derived plist conversion instead of raw access

---

fontc/Cargo.toml
fontir/Cargo.toml
glyphs2fontir/Cargo.toml
ufo2fontir/Cargo.toml

I'm sure we'll add them back in time as proper deps but we don't need them right now. This gets us to git-clean for #17.

Remove unused fontations deps

---

glyphs-reader/Cargo.toml
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs2/Unicode-QuotedHexSequence.glyphs
resources/testdata/glyphs2/Unicode-UnquotedHex.glyphs
resources/testdata/glyphs3/Unicode-UnquotedDec.glyphs
resources/testdata/glyphs3/Unicode-UnquotedDecSequence.glyphs

Add examples of all known codepoint formats in glyphs files and prove we can parse them. Fixes #34.
I wound up just bashing it with a regex to make it consistent as that lets me keep the logic simple.

Parse unicode from glyphs files

---

fontc/src/main.rs
fontir/Cargo.toml
fontir/src/ir.rs
fontir/src/lib.rs
fontir/src/orchestration.rs
fontir/src/source.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

Exploratory beginning of moving #26 into main fontc. Meant to establish the means to capture data from, and provide data to, work so we can do things like spawn a BE make glyph task that can safely acquire any bits of IR it needs to execute.

Playing with how to move state around

---

fontir/src/error.rs
fontir/src/ir.rs
glyphs-reader/src/font.rs
resources/testdata/glyphs2/WghtVar_ImplicitAxes.glyphs
ufo2fontir/src/toir.rs

Get the axis ranges from .glyphs files

---

fontc/src/main.rs
fontir/src/error.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
fontir/src/serde.rs
fontir/src/source.rs
glyphs-reader/src/font.rs
glyphs2fontir/Cargo.toml
glyphs2fontir/src/source.rs
resources/testdata/WghtVar-Bold.ufo/glyphs/bonus_bar.glif
resources/testdata/WghtVar-Bold.ufo/glyphs/contents.plist
resources/testdata/WghtVar-Regular.ufo/lib.plist
resources/testdata/glyphs3/WghtVar_3master_CustomOrigin.glyphs
resources/testdata/glyphs3/WghtVar_GlyphOrder.glyphs
ufo2fontir/src/source.rs

Begin moving towards graph orchestration akin to that shown in #26.
* Use Context to manage access to data; work reads from and publishes to it.
* Allow writing IR to disk to be turned off.
* Make pushing to Context do the write to disk if it is enabled.
* Teach glyphs and ufo 2ir to write static metadata
* As a result of this realize you have no idea how to set VF origin in Glyphs so add that; fixes #44.
* Put the hook in for glyphs2ir to write glyphs but don't do anything useful from it
Builds on #42. Step toward #27.

Push Glyphs axes => StaticMetadata using Context

---

fontir/src/coords.rs
fontir/src/lib.rs
fontir/src/piecewise_linear_map.rs

Create a converter class that, once populated from a set of examples, can convert any unit to any unit. We pay a few extra bytes to store different mappings. In return you can say things like MyUserCoord.to_internal(converter) which is explicitly about starting from UserCoord and producing InternalCoord. 
Intent is to be explicit about types in a way Python does not lend itself to, hopefully thereby minimizing confusion. You can still pick the wrong unit but it should be harder to do it by accident.

Mk2 of unit interchange

---

fontir/src/coords.rs
fontir/src/error.rs
fontir/src/ir.rs
fontir/src/piecewise_linear_map.rs
fontir/src/serde.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

Begin to plumb actual unit types, established in #56, into system. Store a converter in StaticMetadata, serializing it in the standard user:design form (https://github.com/googlefonts/fontmake-rs/blob/main/resources/text/units.md#user--design).
Builds on https://github.com/googlefonts/fontmake-rs/pull/43. Step toward https://github.com/googlefonts/fontmake-rs/issues/22.
Clean copy of #47, this time against the units branch which hopefully addresses the core problems.

Use updated converters on .designspace files

---

fontir/src/error.rs
glyphs-reader/src/font.rs
glyphs-reader/src/lib.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs2/WghtVar.glyphs
resources/testdata/glyphs3/WghtVar.glyphs
smoke_test/smoke_test.py

Manual component generated based on examination of Texturina (Glyphs 2, https://github.com/Omnibus-Type/Texturina, sources/Texturina.glyphs) and Lexend (Glyphs 3, https://github.com/googlefonts/lexend, sources/ofl/lexendgiga/sources/Lexend.glyphs) plus ofc https://github.com/schriftgestalt/GlyphsSDK/blob/Glyphs3/GlyphsFileFormat/GlyphsFileFormatv3.md#differences-between-version-2.
Step toward #27. Builds on #60, which is hopefully in good shape now.

Use an enum to distinguish Path from Component, populate for Glyphs 2 and 3

---

Cargo.toml
fontc/src/main.rs
fontdrasil/Cargo.toml
fontdrasil/src/lib.rs
fontdrasil/src/orchestration.rs
fontdrasil/src/paths.rs
fontir/Cargo.toml
fontir/src/lib.rs
fontir/src/orchestration.rs
fontir/src/paths.rs
fontir/src/source.rs
glyphs2fontir/Cargo.toml
glyphs2fontir/src/source.rs
ufo2fontir/Cargo.toml
ufo2fontir/src/source.rs

Introduce a crate for things FE and BE both use. Naming based on yggdrasil, the world tree that connects norse realms, to keep the "fontir" style alive.
Intent is a future BE crate will have it's own Context and use the same machinery. Split out of #76.

Fontdrasil

---

Cargo.toml
fontbe/Cargo.toml
fontbe/src/error.rs
fontbe/src/lib.rs
fontbe/src/orchestration.rs
fontbe/src/paths.rs
fontc/src/error.rs
fontc/src/lib.rs
fontc/src/main.rs
fontc/src/work.rs
fontdrasil/src/lib.rs

Make fontc use AnyWork, AnyWorkId, etc so it can accomodate FE and BE tasks with non-overlapping id spaces. Subset of changes from #76.

Add wiring for backend tasks

---

fontbe/src/features.rs
fontbe/src/orchestration.rs
fontbe/src/paths.rs
fontc/Cargo.toml
fontc/src/main.rs
fontc/src/work.rs
fontdrasil/Cargo.toml
fontdrasil/src/lib.rs
fontdrasil/src/types.rs
fontir/src/error.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
fontir/src/paths.rs
fontir/src/serde.rs
fontir/src/source.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

Replaces #87 which made fontc unsuitable for library use.
Fixes #86

Use SmolStr instead of String in WorkIdentifier::GlyphName

---

fontbe/Cargo.toml
fontbe/src/features.rs
fontbe/src/orchestration.rs
fontbe/src/paths.rs
fontc/src/main.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
glyphs-reader/src/font.rs
glyphs-reader/src/lib.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
resources/testdata/glyphs2/Fea_Class.glyphs
resources/testdata/glyphs2/Fea_Feature.glyphs
resources/testdata/glyphs2/Fea_Order.glyphs
resources/testdata/glyphs2/Fea_Prefix.glyphs

Using a workaround for https://github.com/cmyr/fea-rs/issues/115. Will need changes when an official way to compile from memory arrives.
Does not implement the only interesting part of feature compilation: [TokenExpander](https://github.com/googlefonts/glyphsLib/blob/24b4d340e4c82948ba121dcfe563c1450a8e69c9/Lib/glyphsLib/builder/tokens.py#L12). Tracking token expansion in #92.
Confirmed generated file for Texturina was identical to what I got from Python and used Texturina to build the tests.

Compile simple - no token expansion - fea for .glyphs

---

fontir/Cargo.toml
fontir/src/error.rs
fontir/src/ir.rs
glyphs-reader/Cargo.toml
glyphs-reader/src/font.rs
glyphs-reader/src/lib.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
resources/testdata/glyphs2/Component.glyphs
resources/testdata/glyphs2/WghtVar.glyphs
resources/testdata/glyphs3/Component.glyphs
resources/testdata/glyphs3/WghtVar.glyphs
ufo2fontir/Cargo.toml
ufo2fontir/src/toir.rs

Fixes #93. Note that I chose to keep a 2x3 - as Glyphs 2 did - rather than Glyphs 3 style individual fields because it's not obvious what order those fields apply in.

glyphs contour and component conversion

---

fontbe/Cargo.toml
fontbe/src/error.rs
fontbe/src/features.rs
fontc/src/main.rs

Build against https://github.com/cmyr/fea-rs/pull/119.
Ran into some issues:
1. Had to copy the feature content for in memory use
1. Using a closure for the resolve sounded lovely until I tried to actually do it, then I angered the compiler and ultimately made a struct
1. `cargo test -p fontc fea` now fails, apparently absolute paths aren't welcome?
* `/blah-blah-blah/fontmake-rs/resources/testdata/Static-Regular.ufo/features.fea` triggers `thread 'tests::compile_fea' panicked at 'assertion failed: path.is_relative()', ...blah blah.../fea-rs/src/util/paths.rs:15:9
Update: ^ fixed by latest updates to the fea-rs branch.

Use upcoming compile api for fea-rs

---

fontbe/src/orchestration.rs
fontc/src/main.rs
fontdrasil/src/orchestration.rs
fontir/src/coords.rs
fontir/src/error.rs
fontir/src/ir.rs
fontir/src/lib.rs
fontir/src/orchestration.rs
fontir/src/variations.rs
glyphs-reader/src/font.rs
glyphs-reader/src/plist.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

Partial (as far as delta weights) https://github.com/fonttools/fonttools/blob/2f1f5e5e7be331d960a0e30d537c2b4c70d89285/Lib/fontTools/varLib/models.py in Rust. Meant to be used when compiling an IR Glyph (set of outlines at positions in designspace) to binary glyf + gvar.
Comments based on reading the code plus pestering @behdad. Anything helpful is probably his, the errors are mine :)
The three independent parallel vec's don't feel great to me, would like to think more about that. I'd like to land this very close to Python then refine from there.
Built on #118 to avoid noise from clippy; merge that first.

VariationModel in Rust, part 1

---

fontir/src/error.rs
fontir/src/ir.rs
fontir/src/serde.rs
fontir/src/variations.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

Building on #117, construct and retain a variation model along with static metadata. For example, Lexend produces
```yml
glyph_locations:
- Hyper Expansion: 0.0
Weight: 0.0
- Hyper Expansion: 0.0
Weight: 0.14432989
- Hyper Expansion: 0.0
Weight: 0.44329897
- Hyper Expansion: 0.0
Weight: 1.0
- Hyper Expansion: 1.0
Weight: 0.0
- Hyper Expansion: 1.0
Weight: 0.44329897
- Hyper Expansion: 1.0
Weight: 1.0
```

Store a VariationModel in StaticMetadata

---

Cargo.toml
fontbe/Cargo.toml
fontbe/src/features.rs
fontbe/src/orchestration.rs
fontc/src/main.rs
fontc/src/work.rs
fontdrasil/src/orchestration.rs
fontir/Cargo.toml
fontir/src/error.rs
fontir/src/glyph.rs
fontir/src/lib.rs
fontir/src/orchestration.rs
fontir/src/paths.rs
fontir/src/variations.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs2/MixedContourComponent.glyphs
ufo2fontir/src/source.rs

Split IR glyphs with contours and components - observed in Lexend - apart such that a glyph with both migrates its contours into a new glyph then references that glyph as a component.
Update the ACL rigging to accomodate; we need the ability to express the ability to write to any glyph including those we've never seen before because we're creating them.
Fixes #125 by converting glyphs with different component definitions at different positions in designspace to simple glyphs.
Split out from #120 to make review more tractable.
The most interesting changes are in fontir/src/glyph.rs.

Add a phase that eliminates mixed contour+component glyphs; legal in source but not binary

---

fontbe/src/orchestration.rs
fontc/src/main.rs
fontc/src/work.rs
fontdrasil/src/orchestration.rs
fontir/src/glyph.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
glyphs2fontir/src/source.rs

Upcoming changes, such as merging glyphs, need to be able to read and/or write things not readily expressed as a set of specific ids such as "all glyphs." To accomodate this update read access (previously done for write) controlled by a function rather than a fixed set of identifiers.
Hoisted out of #120 in hopes of turning that into a series of small more reviewable PRs.

Make ACL system more flexible (static glyf, 1 of 3)

---

fontbe/src/cmap.rs
fontbe/src/features.rs
fontbe/src/glyphs.rs
fontbe/src/orchestration.rs
fontbe/src/post.rs
fontc/Cargo.toml
fontc/src/main.rs
fontir/src/glyph.rs
fontir/src/orchestration.rs
fontir/src/paths.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

Instead of hand-writing Context::get/set x try to use a macro. To make that work cleanly separate some things I'd been lazy about like not having explicitly separate init/final static metadata.
In `fontbe/src/orchestration.rs` I could not seem to hit on the right magic incantation to avoid writing per-type read functions. I end up wanting a constraint to FontRead and then I have a lifetime and then it's mad at me.

Try to de-duplicate some of our Context helpers

---

fontbe/src/font.rs
fontbe/src/head.rs
fontbe/src/lib.rs
fontbe/src/orchestration.rs
fontbe/src/paths.rs
fontc/src/main.rs
fontir/src/error.rs
fontir/src/ir.rs
fontir/src/serde.rs
glyphs-reader/src/error.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/FloatUpem-Regular.ufo/fontinfo.plist
resources/testdata/FloatUpem-Regular.ufo/glyphs/contents.plist
resources/testdata/FloatUpem-Regular.ufo/lib.plist
resources/testdata/float_upem.designspace
resources/testdata/glyphs3/infinity.glyphs
ufo2fontir/Cargo.toml
ufo2fontir/src/source.rs

Contributes to #138.
Put upem into it because hey, we might need that. Turns out we weren't capturing it from source so... do so.
ttx now runs to completion on fontc produced fonts. I'm mildly amazed. Try it yourself!
```shell
cargo run -p fontc -- --source resources/testdata/static.designspace
ttx build/font.ttf
```

Add a minimal head table. Our fonts now ttx.

---

fontc/src/config.rs
fontc/src/lib.rs
fontc/src/main.rs

This also makes the 'init' function into a method on this type, but otherwise avoids any substantive changes.
There are a few FIXMEs in the code here where I have questions about some possible minor changes.
This is based on #160, and shouldn't be merged until that is.

[fontc] Move Config to new 'config' module

---

fontbe/src/glyphs.rs
fontbe/src/hmetrics.rs
fontc/src/main.rs
fontir/src/glyph.rs
fontir/src/ir.rs
fontir/src/serde.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/Unicode-UnquotedDec.glyphs
resources/testdata/glyphs3/Unicode-UnquotedDecSequence.glyphs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

`Glyph::default_location -> GlyphInstance` is added and used by hmtx. Various other files are modified for the sheer joy of it.
Fixes #164. Feel free to merge if it seems OK.

Require Glyph to have a default location, make that instance easy to get

---

fontbe/src/orchestration.rs
fontc/src/lib.rs
fontc/src/work.rs
fontc/src/workload.rs
fontdrasil/src/lib.rs
fontdrasil/src/orchestration.rs
fontir/Cargo.toml
fontir/src/glyph.rs
fontir/src/orchestration.rs
glyphs2fontir/src/source.rs

This is a little refactor around the `AccessFn` type.
TLDR: I wanted to make this a struct so that we could replace the free functions used to construct it with some methods, and then in the process of that I decided it would be more efficient to use an enum that could efficiently handle the common none/all/one cases.
This isn't a hugely impactful change, but I think it is at least a modest ergonomics improvement.

Rework AccessFn type

---

fontc/src/args.rs

This was necessary when it was called from another crate, but now all tests live in the lib.
Just Merge Me

Remove doc(hidden) from test helper

---

fontbe/src/fvar.rs
fontbe/src/name.rs
fontir/src/ir.rs
fontir/src/serde.rs
glyphs2fontir/Cargo.toml
glyphs2fontir/src/source.rs
ufo2fontir/Cargo.toml
ufo2fontir/src/source.rs

Fixes #196
For some reason serde kept puking when I try to handle name id as a u16 so I made it a string. Ex `'Unable to deserialize "/tmp/.tmpRPdlUn/static_metadata.preliminary.yml" names.name_id: invalid type: integer `2`, expected A valid NameId at line 3 column 14'`

Use font_types NameId

---

.github/workflows/rust.yml
fontbe/src/glyphs.rs
fontc/src/workload.rs
resources/githooks/pre-commit
resources/githooks/pre-push
resources/scripts/check_no_println.sh
ufo2fontir/src/source.rs

I did this just to brush up on shell scripting and git hooks, so feel free to reject if you think this is not useful.
Also, note this deliberately only checks the specific lines that are added (cached) to the index, not all the lines in an .rs file. And it strips all `//` inline comments so that a commented-out `println!()` or `eprintln!()` would be allowed. If we wanted to support multi-line /**/ comments, I found a crate/CLI tool called [comment-strip](https://crates.io/crates/comment-strip/) but I don't think it's worth it.

add pre-push git hook to check for println! or eprintln! statements in Rust files

---

fontbe/Cargo.toml
fontc/Cargo.toml
fontc/src/args.rs
fontdrasil/Cargo.toml

Fixes #224 
credits to @rsheeter for the hint to using ArgAction::Set
> https://github.com/clap-rs/clap/issues/1649#issuecomment-1156638220 might offer a path

allow to set fontc --emit-ir=false

---

fontbe/Cargo.toml
fontbe/src/head.rs

when opening a font compiled with fontc with fontTools.ttLib.TTFont, we get a warning because the created/modified fields are set to 0 and the font looks suspiciously too old.
Here I changed it such that we match fontmake's default behavior: i.e. set those two head fields to the current timestamp (as seconds since the TrueType epoch), or to `SOURCE_DATE_EPOCH` if the latter environment variable is present.
This is common way to ensure reproducible builds and fontmake also supports that: see https://reproducible-builds.org/specs/source-date-epoch/
Note that the head.created in particular (not the head.modified) can also be controlled via a 'date' font attribute in .glyphs source, which is equivalent to 'openTypeHeadCreated' from UFO fontinfo.plist. However for now I added a TODO for that, …

[fontbe/head] set created/modified to current timestamp or SOURCE_DATE_EPOCH

---

Cargo.toml
fontir/Cargo.toml
fontir/src/coords.rs
fontir/src/variations.rs

Intended use is to produce data to feed into a future `Gvar::from_glyph_variations` method that will be added in https://github.com/googlefonts/fontations/pull/319 or perhaps a follow-on.
Does not yet implement rounding properly; see https://github.com/googlefonts/fontmake-rs/issues/235.

Add get deltas method

---

fontir/src/ir.rs
glyphs2fontir/src/toir.rs
ufo2fontir/src/toir.rs

this is to match fonttools PointToSegmentPen(outputImpliedClosingLine=True) and make sure that we don't lose or add any points when converting from points to BezPath and back to points (cf. https://github.com/googlefonts/fontmake-rs/pull/236#discussion_r1158279820).
(I pushed this last minute before leaving and plan to add more tests tomorrow hence marked as draft, but feel free to take a look if you want)

GlyphPathBuilder: always output implicit closing line for closed paths 

---

fontbe/src/head.rs

Make env what the test expects rather than asserting it happens to be.
JMM.

Adjust handling of env var in a test

---

fontbe/Cargo.toml
fontbe/src/avar.rs
fontbe/src/error.rs
fontbe/src/font.rs
fontbe/src/fvar.rs
fontbe/src/glyphs.rs
fontbe/src/gvar.rs
fontbe/src/lib.rs
fontbe/src/orchestration.rs
fontbe/src/paths.rs
fontc/Cargo.toml
fontc/src/lib.rs
fontc/src/workload.rs
fontdrasil/src/orchestration.rs
fontir/Cargo.toml
fontir/src/coords.rs
fontir/src/error.rs
fontir/src/ir.rs
fontir/src/serde.rs
fontir/src/variations.rs
glyphs2fontir/Cargo.toml
ufo2fontir/Cargo.toml
ufo2fontir/src/source.rs

Builds on #230, #239. Fixes #207. Fixes #95. 
Update fontations to pickup gvar fixes and thereby fixes #245.
`cargo run -p fontc -- --source resources/testdata/mov_xy.designspace` now produces a VF that works in a browser.
I have punted some feedback to issues as I believe just compiling any vf that works is worth capturing, specifically:
1. https://github.com/googlefonts/fontmake-rs/issues/240
1. https://github.com/googlefonts/fontmake-rs/issues/241
Sufficient to compile an at least somewhat functional Oswald:
```shell
$ git clone https://github.com/googlefonts/OswaldFont
$ cd fontmake-rs
$ cargo run -p fontc -- --source ../OswaldFont/sources/Oswald.glyphs
```
In browser:

Compile simple VFs w/gvar that works in a browser

---

resources/testdata/glyphs2/WghtVar_Avar.glyphs
resources/testdata/glyphs3/WghtVar_Avar.glyphs

Includes:
1. An instance that remaps weight, so an avar table is needed
1. A master below weight 400 so we need to pick the default properly (e.g. search for Regular as fontmake does)
Not handling these features causes Oswald to compile wrong, hence the milestone assignment.

Add examples of glyphs files with instances

---

fontbe/src/avar.rs
fontbe/src/font.rs
fontc/src/lib.rs
fontir/src/error.rs
glyphs-reader/src/error.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
resources/testdata/glyphs2/WghtVar_Avar.glyphs

Improve, though not yet to parity with fontmake, handling of glyphs 2/3 instances:
* Load glyphs instances for glyphs v2 and v3
* Upgrade v2 to v3 per our std practice
* We do not yet support all fields. Baby steps.
* The code for this is tiresome and lengthy
* Fix typo that lead to avar not being merged into final font
* Include instance mappings in user:design mappings, which improves avar production
* We now match the Oswald avar noted in https://github.com/googlefonts/fontmake-rs/issues/250#issuecomment-1504057038
* Figure out the default instance and use it to assign axis defaults
* We now match the Oswald fvar axes noted in https://github.com/googlefonts/fontmake-rs/issues/250#issuecomment-1504057038
* We do not yet emit any named instances
Step toward #250

Load .glyphs instances and use them to inform axis rigging

---

.github/workflows/rust.yml

Runs `cargo test -p` for each package rather than a single `cargo test` for the whole workspace.
JMM

[ci] test all packages individually

---

glyphs-reader/plist_derive/src/lib.rs
glyphs-reader/src/font.rs

As requested in https://github.com/googlefonts/fontmake-rs/pull/252#discussion_r1165739577

Use `#[fromplist(rest)]` instead of `#[rest]`

---

fontbe/src/glyphs.rs
fontir/src/glyph.rs

Only consider basis vectors - not translation - when deciding if we need to convert to contours. Numerous Oswald glyphs we previously unnecessarily converted to contours are now kept as components, ref https://github.com/googlefonts/fontmake-rs/issues/250#issuecomment-1507845219, 2.
Credit @anthrotype for pointing out the problem in IM.

Only convert to contours if basis vectors vary

---

fontbe/src/glyphs.rs
fontir/src/ir.rs

Builds on #266. Many Oswald glyphs now set USE_MY_METRICS and produce identical results to fontmake. Improves results for https://github.com/googlefonts/fontmake-rs/issues/250#issuecomment-1507845219, 3.

Set USE_MY_METRICS similar to how ufo2ft does it

---

fontir/src/variations.rs

Purely out of curiosity - we're far from ready for any real perf tuning - I ran a flamegraph of Oswald building (`rm -rf build/ && cargo flamegraph -p fontc --  --source ../OswaldFont/sources/Oswald.glyphs --emit-ir false`). It showed an inordinate amount of time in variationmodel deltas, `fontir::variations::VariationModel::deltas (404 samples, 10.75%)`, dominated by `alloc::raw_vec::RawVec<T,A>::reserve_for_push`. Reserve ahead, reducing deltas enough to be hard to find on the flamegraph.

Preallocate delta buffer

---

fontc/src/args.rs
fontc/src/lib.rs
fontir/src/glyph.rs
fontir/src/ir.rs
fontir/src/orchestration.rs

Improves Oswald build alignment with fontmake as run by gftools. See https://github.com/googlefonts/fontmake-rs/issues/250#issuecomment-1513807429.
Builds on #267.
Once this plus the PRs it builds on are merged the largest source of difference in `glyf` for Oswald is that we don't remove implicit on-curves.

Support component flattening

---

Cargo.toml
fontbe/Cargo.toml
fontc/Cargo.toml
fontdrasil/Cargo.toml
fontir/Cargo.toml
glyphs-reader/Cargo.toml
glyphs2fontir/Cargo.toml
ufo2fontir/Cargo.toml

It's unlikely these wouldn't match on purpose. If we do need inconsistency it becomes very visible: everything but that uses workspace, why doesn't that?

Centralize versions of shared dependencies

---

fontbe/src/metrics_and_limits.rs

Amusingly the sample compile at https://github.com/googlefonts/fontmake-rs#sources-to-play-with triggers this bug.

Don't crash when a glyph bbox x_max is < 0

---

fontc/src/lib.rs
fontc/src/workload.rs

Helps with #285, after this hmtx has just a handful of diffs. Most are small diffs in lsb, for example 15 vs 18, plus one weird one `<mtx name="brevecomb-cy" width="600" lsb="167"/>` that gets a width of 0 in the fontmake-py version.

Adjust the dependencies for hmtx to ensure bbox is available

---

Cargo.toml
fontc/src/lib.rs

Fixes #251. Do not just merge because the key fontations change, in https://github.com/googlefonts/fontations/pull/417, is not yet published.

Use latest write-fonts so we produce identical cmap's for Oswald.

---

resources/scripts/ttx_diff.py

Builds on #287 because I was using it to help test that. Submit #287 first. Current result:
```
COMPARISON
Only fontmake produced 'GDEF', 'GPOS', 'GSUB', 'HVAR', 'STAT'
DIFF 'OS_2', build/fontc.OS_2.ttx build/fontmake.OS_2.ttx
DIFF 'cmap', build/fontc.cmap.ttx build/fontmake.cmap.ttx
DIFF 'fvar', build/fontc.fvar.ttx build/fontmake.fvar.ttx
DIFF 'glyf', build/fontc.glyf.ttx build/fontmake.glyf.ttx
DIFF 'gvar', build/fontc.gvar.ttx build/fontmake.gvar.ttx
DIFF 'head', build/fontc.head.ttx build/fontmake.head.ttx
DIFF 'hhea', build/fontc.hhea.ttx build/fontmake.hhea.ttx
DIFF 'maxp', build/fontc.maxp.ttx build/fontmake.maxp.ttx
DIFF 'name', build/fontc.name.ttx build/fontmake.name.ttx
DIFF 'post', build/fontc.post.ttx …
```

Helper for frequent diff pattern

---

fontbe/src/fvar.rs
fontbe/src/gvar.rs
fontc/src/lib.rs
fontir/src/ir.rs
fontir/src/serde.rs
glyphs-reader/src/font.rs
glyphs-reader/src/lib.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
resources/scripts/ttx_diff.py
resources/testdata/glyphs2/WghtVar_Instances.glyphs
resources/testdata/glyphs3/WghtVar_Instances.glyphs
ufo2fontir/src/source.rs

Sufficient to make Oswald fvar report to match the one from fontmake:
```shell
python resources/scripts/ttx_diff.py ../OswaldFont/sources/Oswald.glyphs | grep "'fvar'"
```
New test files created by loading WghtVar.glyphs in Glyphs, running add instance for each master, and saving as v2/3.

Add basic support for named instances for .glyphs files

---

Cargo.toml
fontbe/src/error.rs
fontbe/src/os2.rs
fontc/src/lib.rs
fontir/src/ir.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs2/WghtVar_OS2.glyphs
resources/testdata/glyphs3/WghtVar_OS2.glyphs
ufo2fontir/src/source.rs

Makes most, though not all, of OS/2 match. The following differences are not addressed in this PR:

Make Oswald OS/2 from fontc closer to that from fontmake

---

fontc/src/lib.rs
fontir/src/coords.rs
resources/testdata/FontInfo-Regular.ufo/fontinfo.plist
resources/testdata/WghtVar-Bold.ufo/fontinfo.plist
resources/testdata/WghtVar-Regular.ufo/fontinfo.plist
ufo2fontir/src/source.rs

fvar is now identical, OS/2 has the same diff as #294 shows for .glyphs

Bring OS/2 and named instance support for ufo+ds up to par with .glyphs

---

fontbe/src/os2.rs

Match outlineCompiler.py default value for break char

---

fontbe/src/features.rs
fontbe/src/font.rs
fontbe/src/orchestration.rs
fontbe/src/paths.rs
fontc/src/args.rs
fontc/src/lib.rs
fontc/src/workload.rs
fontdrasil/src/orchestration.rs
fontir/src/orchestration.rs
resources/testdata/Static-Regular.ufo/features.fea

Split the single feature font from fea-rs into pieces and include those pieces in the final font instead of running fea-rs and then just abandoning the results if it succeeded.
This reveals that for Oswald GSUB doesn't match and we aren't ending up with a GPOS at all; filed #308.

Improve handling of fea-rs output

---

fontbe/src/os2.rs
fontc/src/lib.rs

See https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/otlLib/maxContextCalc.py
`python resources/scripts/ttx_diff.py ../OswaldFont/sources/Oswald.glyphs --compare default` at long last reports `Identical 'OS_2'`
I have not implemented GPOS but the pattern is clear and this was enough of a pita I'd like to checkpoint :)

Compute usMaxContext for GSUB

---

fontbe/src/fvar.rs
fontc/src/lib.rs
fontir/src/ir.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/scripts/ttx_diff.py
ufo2fontir/src/source.rs

ttx_diff in default mode:
```shell
Only fontmake produced 'GDEF', 'GPOS', 'HVAR', 'STAT'
DIFF 'glyf', build/default/fontc.glyf.ttx build/default/fontmake.glyf.ttx
DIFF 'head', build/default/fontc.head.ttx build/default/fontmake.head.ttx
DIFF 'hhea', build/default/fontc.hhea.ttx build/default/fontmake.hhea.ttx
DIFF 'maxp', build/default/fontc.maxp.ttx build/default/fontmake.maxp.ttx
DIFF 'post', build/default/fontc.post.ttx build/default/fontmake.post.ttx
```
Note that I modified ttx_diff.py to eliminate …

Make Oswald 'name' match fontmake

---

fontbe/src/post.rs
fontir/src/ir.rs
fontir/src/serde.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

Oswald post matches after:
```
Only fontmake produced 'GDEF', 'GPOS', 'HVAR', 'STAT'
DIFF 'glyf', build/default/fontc.glyf.ttx build/default/fontmake.glyf.ttx
DIFF 'head', build/default/fontc.head.ttx build/default/fontmake.head.ttx
DIFF 'hhea', build/default/fontc.hhea.ttx build/default/fontmake.hhea.ttx
DIFF 'maxp', build/default/fontc.maxp.ttx build/default/fontmake.maxp.ttx
Identical 'post'
```

Match glyphsLib/ufo2ft defaults for underline thickness/position

---

Cargo.toml
fontbe/src/error.rs
fontbe/src/features.rs

The only major change here is that fea-rs now just passes us the tables we want, so we no longer need to compile and then reparse them. (This also means we can remove one of our error variants, since fea-rs no longer generates binary)
JMM

This updates to new versions of fontations + fea-rs

---

fontbe/src/metrics_and_limits.rs
fontir/src/ir.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/FontInfo-Regular.ufo/fontinfo.plist
resources/testdata/glyphs2/WghtVar_OS2.glyphs
resources/testdata/glyphs3/WghtVar_OS2.glyphs
ufo2fontir/src/source.rs

Note that I have punted italic slope rise into #318 
ttx_diff of Oswald after shows matching hhea:
```
Only fontmake produced 'GDEF', 'GPOS', 'HVAR', 'STAT'
DIFF 'glyf', build/default/fontc.glyf.ttx build/default/fontmake.glyf.ttx
DIFF 'head', build/default/fontc.head.ttx build/default/fontmake.head.ttx
Identical 'hhea'
DIFF 'maxp', build/default/fontc.maxp.ttx build/default/fontmake.maxp.ttx
Identical 'post'
``

Improve hhea enough to match for Oswald

---

fontbe/src/name.rs
resources/scripts/ttx_diff.py

As noted in https://github.com/googlefonts/fontc/pull/314#pullrequestreview-1455005475, apparently I invented a sort order for 'name'. Turns out the spec says something else; do that instead.

Use the real sort order for 'name'

---

Cargo.toml
fontbe/src/head.rs
fontbe/src/metrics_and_limits.rs
fontc/Cargo.toml
fontc/src/lib.rs
fontc/src/workload.rs
fontir/Cargo.toml
fontir/src/ir.rs
fontir/src/serde.rs
glyphs-reader/Cargo.toml
glyphs-reader/src/font.rs
glyphs2fontir/Cargo.toml
glyphs2fontir/src/source.rs
resources/scripts/ttx_diff.py
resources/testdata/WghtVar-Regular.ufo/fontinfo.plist
resources/testdata/glyphs3/Dated.glyphs
ufo2fontir/Cargo.toml
ufo2fontir/src/source.rs

Specifically:
* lowest rec ppm
* flags
* font revision
* created/modified
Fixes #233. Fixes #249.
Requires https://github.com/googlefonts/fontations/pull/469 which is in write-fonts 0.5.1.
The only Oswald head diff I'm left with is checksum. https://github.com/googlefonts/fontations/issues/466 requests fontations set checksum adjustment. It won't match until all tables do ofc.

Set more of head correctly

---

resources/scripts/ttx_diff.py

It's not helpful to report `head` differs when it's only by checksum and that's expected because some other table doesn't match.
JMM

Remove checksum from diff

---

fontbe/src/font.rs
fontbe/src/lib.rs
fontbe/src/orchestration.rs
fontbe/src/paths.rs
fontbe/src/stat.rs
fontc/src/change_detector.rs
fontc/src/lib.rs
resources/scripts/ttx_diff.py

ttx_diff claims we match Oswald. Not cheating at all to massage the results right?
```shell
Only fontmake produced 'GDEF', 'GPOS', 'HVAR'
Identical 'STAT'
DIFF 'glyf', build/default/fontc.glyf.ttx build/default/fontmake.glyf.ttx
Identical 'head'
Identical 'hhea'
DIFF 'maxp', build/default/fontc.maxp.ttx build/default/fontmake.maxp.ttx
Identical 'post'
```

Write a rudimentary STAT

---

glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs2/WghtVar.glyphs
resources/testdata/glyphs3/WghtVar.glyphs

Tiptoing toward #308
The existing test to confirm reading glyphs2 wghtvar == read glyphs3 wghtvar verifies the field rename works as intended.

Add example .glyphs kern and ability to read it

---

Cargo.toml
fontc/src/lib.rs

fixes a bug when computing implied oncurves, and also prunes more implied oncurves (by testing midpoints either before or after rounding the float coordinates to integer)
After this, compiling Oswald.glyphs with fontc gives identical maxp and the glyf table diff is the following:
```diff
--- build/default/fontc.glyf.ttx        2023-06-08 16:53:37.677358984 +0100
+++ build/default/fontmake.glyf.ttx     2023-06-08 16:53:37.677358984 +0100
@@ -10285,7 +10285,6 @@
</contour>
<contour>
<pt x="219" y="-9" on="1"/>
-        <pt x="219" y="-9" on="1"/>
<pt x="290" y="-9" on="0"/>
<pt x="382" y="51" on="0"/>
<pt x="430" y="157" on="0"/>
@@ -10331,7 +10330,6 @@
<pt x="25" y="124" on="0"/>
<pt x="75" y="37" on="0"/>
<pt x="163" y="-9" on="0"/>
-        <pt x="219" y="-9" on="1"/>
</contour> …
```

require write-fonts 0.6.1

---

resources/scripts/ttx_diff.py

Requires [fontmake 3.6.0](https://github.com/googlefonts/fontmake/releases/tag/v3.6.0) just released

ttx_diff.py: pass --drop-implied-oncurves fontmake option to reduce glyf diff

---

fontbe/src/error.rs
fontbe/src/features.rs
fontc/src/args.rs
fontc/src/lib.rs
fontir/src/error.rs
fontir/src/ir.rs
resources/testdata/fea_include.designspace
resources/testdata/fea_include_ufo/FeaInc-Bold.ufo/features.fea
resources/testdata/fea_include_ufo/FeaInc-Bold.ufo/fontinfo.plist
resources/testdata/fea_include_ufo/FeaInc-Bold.ufo/glyphs/bar.glif
resources/testdata/fea_include_ufo/FeaInc-Bold.ufo/glyphs/contents.plist
resources/testdata/fea_include_ufo/FeaInc-Bold.ufo/glyphs/plus.glif
resources/testdata/fea_include_ufo/FeaInc-Bold.ufo/layercontents.plist
resources/testdata/fea_include_ufo/FeaInc-Bold.ufo/metainfo.plist
resources/testdata/fea_include_ufo/FeaInc-Regular.ufo/features.fea
resources/testdata/fea_include_ufo/FeaInc-Regular.ufo/fontinfo.plist
resources/testdata/fea_include_ufo/FeaInc-Regular.ufo/glyphs/bar.glif
resources/testdata/fea_include_ufo/FeaInc-Regular.ufo/glyphs/contents.plist
resources/testdata/fea_include_ufo/FeaInc-Regular.ufo/glyphs/plus.glif
resources/testdata/fea_include_ufo/FeaInc-Regular.ufo/layercontents.plist
resources/testdata/fea_include_ufo/FeaInc-Regular.ufo/lib.plist
resources/testdata/fea_include_ufo/FeaInc-Regular.ufo/metainfo.plist
resources/testdata/fea_include_ufo/common.fea
resources/testdata/static.fea
ufo2fontir/src/source.rs

First crack at resolving includes. For the purposes of incremental compilation all fea files in the .designspace dir will be considered for feature file change. An include pointed outside the .designspace dir won't be detected as changed when attempting incremental compile.
Fixes #296. After this change I can compile https://github.com/madig/FirerSans w/o error. I make no claim that the font will actually _work_ ofc.

Resolve fea includes for UFO against dir containing .ufo

---

fontc/src/change_detector.rs
fontc/src/lib.rs
fontdrasil/src/types.rs
fontir/src/error.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
fontir/src/paths.rs
fontir/src/serde.rs
fontir/src/source.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/designspace_from_glyphs/README.md
resources/testdata/designspace_from_glyphs/WghtVar-Bold.ufo/groups.plist
resources/testdata/designspace_from_glyphs/WghtVar-Regular.ufo/groups.plist
resources/testdata/designspace_from_glyphs/WghtVar-Regular.ufo/kerning.plist
resources/testdata/glyphs2/WghtVar.glyphs
resources/testdata/glyphs3/WghtVar.glyphs
ufo2fontir/src/source.rs

Intent is to output variable features we compile with fea-rs. IR model is meant to accomodate glyphs and designspace. Most interesting part should be `fontir/src/ir.rs` which has the IR changes, esp. `struct Kerning` which holds a variable-first representation of kerning.
left/right KerningGroup all the things. Or kern left/right ... it's all very confusing.
https://gist.github.com/rsheeter/4c8e7822d276f871eef974f8c1975ace shows an example of kerning IR (for Oswald).
Step toward #308. I want to leave filling in the blanks and aligning kerning groups to a subsequent PR.

Model kerning in IR and capture it for .glyphs and .designspace

---

fontir/src/ir.rs
glyphs2fontir/src/source.rs
resources/testdata/WghtVar-Bold.ufo/groups.plist
resources/testdata/WghtVar-Regular.ufo/groups.plist
ufo2fontir/src/source.rs

Based on discussion on https://github.com/googlefonts/ufo2ft/pull/635, treat the group names in the default master as authorititive. Remap alternate names for the same {glyphs} in other masters. Ignore all groups from non-default masters that do not identify a set of glyphs given a name in the default.

Take the default master as authoritative in designspace kerning

---

Cargo.toml

After this diff is:
```shell
$ python resources/scripts/ttx_diff.py ../OswaldFont/sources/Oswald.glyphs --compare default
Compare default in build/default
(cd build/default && cargo run -p fontc -- --source /usr/local/google/home/rsheeter/oss/OswaldFont/sources/Oswald.glyphs --build-dir . > fontc.log 2>&1)
(cd build/default && ttx -o font.ttx font.ttf > ttx.log 2>&1)
(cd build/default && fontmake -o variable --output-dir Oswald.glyphs --drop-implied-oncurves --no-production-names --keep-direction /usr/local/google/home/rsheeter/oss/OswaldFont/sources/Oswald.glyphs > fontmake.log 2>&1)
(cd build/default/Oswald.glyphs && ttx -o Oswald-VF.ttx Oswald-VF.ttf > ttx.log 2>&1)
TTX FILES
fontc     build/default/fontc.ttx
fontmake  build/default/fontmake.ttx
COMPARISON
Only fontmake produced …
```

Update to write-fonts 0.6.2 to get updated reverse pen

---

fontir/src/coords.rs
fontir/src/variations.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

This makes the API more discoverable and intuitive to users familiar with other Rust collection types.

[fontir] Use common rust method names in Location

---

fontbe/src/error.rs
fontc/src/workload.rs

`Display` is intended to be human readable, and will generally produce better output than `Debug`.
This is particularly true in fea-rs, where we have fancy display impls.
Motivated by trying to debug #349. I have some fixes up, but there's a bunch of other nasty stuff in the FEA here that I need to look into.

Use display representations when logging errors

---

fontbe/src/avar.rs
fontbe/src/cmap.rs
fontbe/src/features.rs
fontbe/src/font.rs
fontbe/src/fvar.rs
fontbe/src/glyphs.rs
fontbe/src/gvar.rs
fontbe/src/head.rs
fontbe/src/metrics_and_limits.rs
fontbe/src/name.rs
fontbe/src/orchestration.rs
fontbe/src/os2.rs
fontbe/src/post.rs
fontbe/src/stat.rs
fontc/src/lib.rs
fontdrasil/src/orchestration.rs
fontir/src/glyph.rs
fontir/src/orchestration.rs
fontir/src/paths.rs
fontir/src/source.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

For context, initially I wasn't sure how our work model would play out. I feel like it's settled enough to be worth tidying up. I plan to move knowledge of what slots the work reads/writes to the work itself in a subsequent PR.
`fontdrasil/src/orchestration.rs` is the interesting part, to the extent there is an interesting part. The result is just shuffling things to get id from `Work::id()`
Along the way I deleted a fixme, filing https://github.com/googlefonts/fontc/issues/355 instead.

Housekeeping: a work should know it's own id

---

Cargo.toml

should fix some issues compiling GoogleSans, see https://github.com/googlefonts/googlesans/issues/586#issuecomment-1613351936
JMM

bump fea-rs dep to 0.9.1

---

fontc/src/main.rs

I'm not sure if this is contentious or not?
Before:
2023-07-12T15:59:18.091023Z: ThreadId(1): DEBUG: 7624 glyphs identified After:
[2023-07-12T15:58:38.552647Z ThreadId(1) ufo2fontir::source DEBUG] 7624 glyphs identified`
So this is slightly more verbose, but knowing where a message was logged from is very helpful when debugging. If we want to shave more characters we can use millis instead of micros in the timestamp, and assign custom thread names in the threadpool.

Include source info when writing logs

---

fontbe/src/glyphs.rs
fontbe/src/orchestration.rs
fontc/src/workload.rs
fontdrasil/src/types.rs
fontir/src/glyph.rs
fontir/src/ir.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

These impls fell into one of two categories: they were either wrapping a call to clone, or they were doing acting as general constructors.
In the cases where they were wrapping a clone call, I just moved the 'clone' to the callsite. In the cases where they were acting as general constructors, I moved them into `new` methods.

Remove most impls of From<&T>

---

ufo2fontir/Cargo.toml
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

The upstream API has changed to make the 'name' fields on instance/source types optional. This patch is the minimal fix, where we check all names on load and insert placeholders if they are missing.
An alternative solution might be to use something other than the name to uniquely identify these objects.
This is a draft as the upstream PR (https://github.com/linebender/norad/pull/313) has not yet been merged.

[ufo2fontir] Fix for optional designspace names

---

fontbe/src/gvar.rs
fontbe/src/orchestration.rs
fontir/src/variations.rs

TupleBuilder was iterating over VariationRegion's axis_tents which is a BTreeMap, but it should instead iterate over the region's tents following the fvar's axis order, that's what the gvar Tuples must follow. Otherwise we store deltas for the wrong axes!

must follow fvar axes order when building gvar GlyphDeltas

---

fontir/src/error.rs
fontir/src/ir.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
resources/testdata/glyphs2/QCurve.glyphs
resources/testdata/glyphs3/QCurve.glyphs
ufo2fontir/src/toir.rs

GlyphPathBuilder: support contours starting with offcurves or without oncurves

---

fontbe/src/glyphs.rs
fontc/src/workload.rs
fontdrasil/src/orchestration.rs

#359 changed BE glyph work from depending on only the IR glyphs used to all IR glyphs. This forces the can run check to take a slow path (table scan) due to use of Access::Custom and inhibits concurrent execution of FE and BE glyphs.
This PR late-binds dependencies for BE glyph work. Initially access unknown - never runnable - is used and then, once the corresponding IR glyph is done, a set of the specific dependencies is used. This should be faster to evaluate runnable on and re-enable concurrent FE/BE glyph work executions.
Intended to partially address #369. 
#369 doesn't offer complete steps to reproduce but it appears to be roughly `time fontc GS designspace`. My tests and results follow (some noise from cli omitted, measured on an M1 Mac):
**Oswald 2.415s => 1.302s**
```shell
$ for …
```

Restore fine-grained glyph work dependencies

---

fontbe/src/gvar.rs

Fixes https://github.com/googlefonts/fontc/issues/388

fontbe/gvar: don't skip glyphs without variations

---

Cargo.toml
fontbe/src/glyphs.rs

Fixes https://github.com/googlefonts/fontations/issues/564
**DO NOT MERGE** as this requires https://github.com/googlefonts/fontations/pull/565 to be released and write-fonts to be bumped first

iup_delta_optimize' contour_ends wants endpoint indices, must -1 lengths

---

fontc/src/workload.rs

Assignment of thread names causes each to root individually in flamegraph, making it essentially useless. Note the tp0, 1, etc:
If we don't name them the flamegraph is very useful:
So don't name the threads. If we *really* like thread names we can make it optional - even on by default - in a followon while also documenting how to get a good flamegraph.
JMM.

Restore the ability to produce a meaningful flamegraph

---

README.md

Add the docs promised in https://github.com/googlefonts/fontc/pull/391
[rendered](https://github.com/googlefonts/fontc/tree/dg#running-flamegraph)
JMM

Document flamegraph, it's quite handy

---

fontbe/src/glyphs.rs
fontbe/src/metrics_and_limits.rs
fontbe/src/orchestration.rs
fontc/src/lib.rs

A bit of cleanup on top of  #379.
This renames the backend 'Glyph' type to 'NamedGlyph', and turns it into a simple struct, containing a `write-fonts` Glyph and the associated name.
This also lets us delete the GlyphPersistable type, since we don't need to store a flag indicating whether the glyph is simple or composite.

Use fontations Glyph enum

---

fontbe/src/glyphs.rs
fontbe/src/head.rs
fontbe/src/orchestration.rs
fontc/src/lib.rs

Based on #382 
-----
This also uses the LocaFormat type in fontations (which was copied from here) which then forces us to hack around orphan rules.
Playing around with this i have a better understanding of the annoyance we encountered previously about serializing loca. The main question this patch raised for me, was whether or not we should just have a `GlyfAndLoca` struct that wraps both those tables, as they're always generated together? This would let us simplify some of our serialization code.

Use fontations glyf/loca builder

---

fontir/src/ir.rs
glyphs2fontir/src/toir.rs
ufo2fontir/src/toir.rs

Before, `fontc`glyphs2fontir::toir::to_ir_contours_and_components (1 samples, 0.92%)` showing the usual vec growth fns.
After, can't find to_ir_contours_and_components in the flamegraph for GlyphIrWork at all.
Also avoid the clone in `src_path.nodes.clone()`.

Preallocate some buffers based on flamegraph

---

Cargo.toml
fontbe/src/features.rs

That is, axis locations can now exist in one of user, design, or normalized coordinates.

[features] Update fea-rs to allow axis unit suffixes

---

.github/workflows/rust.yml

Trying to get setup to turn on merge queues (https://github.blog/2023-07-12-github-merge-queue-is-generally-available/) per https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#configuring-continuous-integration-ci-workflows-for-merge-queues

Add merge_group to on:

---

fontbe/src/features.rs

Instead of converting normalized to user so that fea-rs could callback to us to convert it to normalized again
JMM, hopefully thereby proving the wonders of the merge queue

Generate kerning fea with normalized units

---

.github/workflows/rust.yml

Logs like this suggest parallelizing tests might speed up PRs turning green:
Put each of the 1m+ items into it's own job and everything else into one.
JMM

Try to parallelize test execution

---

fontc/src/main.rs

This lets us ensure that we see the Display impls intead of the Debug impls, which are generally less useful.

Manually catch & print errors in main()

---

fontc/src/lib.rs

#378 reports no contours should take no space. Evidently that has been made true already so add a test to make sure it stays true.
Fixes #378.
JMM

Prove no outlines take no glyf space

---

fontc/src/lib.rs
fontdrasil/src/types.rs
fontir/src/glyph.rs
fontir/src/ir.rs
resources/testdata/glyphs2/Mono.glyphs

For WghtVar.glyphs, which does not define notdef, we get this:
```shell
$ python resources/scripts/ttx_diff.py ../OswaldFont/sources/Oswald.glyphs
COMPARISON
Only fontmake produced 'HVAR'
DIFF 'GDEF', build/default/fontc.GDEF.ttx build/default/fontmake.GDEF.ttx
DIFF 'GPOS', build/default/fontc.GPOS.ttx build/default/fontmake.GPOS.ttx
Identical 'STAT'
Identical 'glyf'
Identical 'head'
Identical 'hhea'
Identical 'maxp'
Identical 'post'
```
Fixes #149 
Fixes #420

Generate missing .notdef like ufo2ft

---

fontbe/src/features.rs

Fixes #426 
I first push a reproducer to demostrate the bug, then follow up with the fix

Fix MissingAxisTentError when building Oswald

---

fontc/src/lib.rs
fontir/src/ir.rs

.notdef glyph represent the absence of a character, so it should not be explicitly mapped in the cmap. Currently we were adding a no-op map from 0x0000 (the NULL character) to glyph index 0 (.notdef) but this is unnecessary.
https://learn.microsoft.com/en-us/typography/opentype/spec/cmap#overview
> Regardless of the encoding scheme, character codes that do not correspond to any glyph in the font should be mapped to glyph index 0. The glyph at this location must be a special glyph representing a missing character, commonly known as .notdef.
NULL is for something else entirely. Basically _all_ character codepoints that are not suppoted in a given font (including NULL in the particular case of the test font as well as most font nowadays) get _implicitly_ mapped to glyph id 0, aka ".notdef" …

leave generated .notdef glyph unmapped in cmap

---

fontbe/src/avar.rs
fontbe/src/features.rs
fontbe/src/font.rs
fontbe/src/fvar.rs
fontbe/src/glyphs.rs
fontbe/src/gvar.rs
fontbe/src/stat.rs
fontir/src/ir.rs
fontir/src/serde.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

Based on observed confusion, rename the fields that hold axes and update comments. Key change is in `fontir/src/ir.rs`, the rest is just refactoring updating things.
Note that I am deliberately not fixing the clippy error about datetimes, will do that in it's own PR
JMM

Rename static metadata fields for clarity

---

Cargo.toml
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

Fix things that make CLI noise: warnings from chrono deprecations (ignored in #431) and new resolver
JMM

Housekeeping

---

fontdrasil/src/types.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
fontir/src/paths.rs
glyphs-reader/src/font.rs
resources/testdata/glyphs2/WghtVar_Anchors.glyphs
resources/testdata/glyphs3/WghtVar_Anchors.glyphs

Step toward marks, ref https://github.com/googlefonts/fontc/issues/308#issuecomment-1717920210

Add support for anchors to IR and glyphs2fontir

---

fontc/src/lib.rs
fontir/src/error.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
fontir/src/paths.rs
fontir/src/source.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

Anchors are very helpful if you want ot eventually build marks.
An unfortunate implication of anchors living in glyphs is features will end up unable to start until all FE glyphs are done. This is hard to avoid given that the anchors live with the glyphs in both major source formats.
It would be possible to just bundle anchors with glyph ir but for now I didn't.

Capture anchors in glyphs and ufo 2 fontir

---

fontc/src/args.rs
fontc/src/change_detector.rs
fontc/src/lib.rs

Fixes #430
Adds a --compile-features={true,false} bool flag (true by default) to optionally skip OT layout features compilation.
I need to add tests and convince myself the new option is wired up in all the places it needs be, but judging from casual local testing it seems to produce the desired effect, i.e. optionally skip BE job for FEA compilation, observe font contains no GDEF/GPOS/GSUB tables.

add --compile-features=false to disable FEA compilation

---

glyphs-reader/plist_derive/src/lib.rs
glyphs-reader/src/from_plist.rs
glyphs-reader/src/plist.rs

This is an attmept to smooth over some papercuts, motivated by reviewing the glyphspackage PR.
- This makes the error type an actual error type
- adds type aliases for Dictionary/Array
- Adds simple methods for trying to cast from a generic plist enum to dict/array/string, returning a useable error if the types are wrong

Improve plist ergonomics

---

README.md

[rendered](https://github.com/googlefonts/fontc/tree/go#focused-flames)
For example, focused on fea_rs in hopes of helping with https://github.com/googlefonts/fontc/issues/456
JMM

Capture instructions to narrow a flamegraph

---

fontc/src/args.rs
fontc/src/change_detector.rs
fontc/src/lib.rs
fontc/src/main.rs
fontc/src/timing.rs
fontc/src/workload.rs
fontir/src/orchestration.rs
fontir/src/paths.rs

How might we understand what our threads are up to? - it's hard to tell from most profiles. By visualizing it ourselves of course! First hacky draft:
Above each row is a thread and time goes left to right. The pink area (color/label strategy tbd) shows very fine grained FE glyph work being distributed among threads, this is what we want. Next we see a period where nothing can be done until we have final glyph order, understandable but not what we want. We can see any speedup to glyph order production is a big win as it's delaying everything. Next we see a lot of per-glyph BE work in light blue, then a period where fea-rs is the long pole as we push toward completion. 
We can see that kern, which is executable as soon as glyph order is done and blocks backend fea, doesn't start for a quite …

Add a visualization of thread activity

---

fontbe/src/glyphs.rs

This better matches the behaviour of fontmake:
- we mark (0, 0) all deltas as being optional
- we ensure we always write at least one delta for a composite glyph, per https://github.com/fonttools/fonttools/issues/1381
With this patch our gvar diff is down to about 300 lines, the majority of which looks to be something causing the two methods that are computing interpolatable points producing slightly different results in some cases; will investigate that next.
closes #398

Improve handling of composite glyph deltas

---

fontbe/src/avar.rs
fontbe/src/error.rs
fontbe/src/font.rs
fontbe/src/metrics_and_limits.rs
fontbe/src/orchestration.rs
fontbe/src/os2.rs
fontc/src/lib.rs

Fixes #469
although a few other tests are still failing, I'm not sure exactly how to fix them.
IIUC, because in the case of all-identity maps I'm no longer writing out an avar table, the tests that attempt to compile a second time are failing because the Avar backend task is being run again, whereas they expect that it not be run...

skip avar segments when they are all identity mappings

---

fontc/src/args.rs
fontc/src/lib.rs
fontir/src/glyph.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
resources/scripts/ttx_diff.py
resources/testdata/glyphs2/Component.glyphs

https://github.com/googlefonts/fontc/issues/291#issuecomment-1557358538 notes "if we want to match gftools default behavior of decomposing unconditionally all transformed components we need to add a corresponding option to fontc"
So ... do that. After this the glyf and gvar diff in ttx_diff gftools mode is down to a very few points where we're off by one:

Optionally eliminate components with transforms to match gftools

---

fontc/src/lib.rs
resources/testdata/wght_var_instance_stylename.designspace
ufo2fontir/src/source.rs

Fixes https://github.com/googlefonts/fontc/issues/386
~~Note the previous behavior of taking instance.name and stripping familyname prefix does not match fonttools behavior so I removed it. The instance.name (like similar element name attributes in DS format) is meant as an identifier for cross-referencing elements and is not used for named instances' style names. Only instance `stylename` attribute (and the localised names if any) are used by fonttools to set the fvar's NamedInstance subFamilyNameID.~~
The `stylename` attribute can be omitted in DSv5 and be generated using axis labels, but for most projects (including those two Google private projects that we wish to use this for) they are likely to be defined explicitly so with this PR we use them.
Also note that the …

ufo2fontir: prefer use instance.stylename

---

Cargo.toml
fontir/src/glyph.rs

Added with kurbo 0.10.2 in https://github.com/linebender/kurbo/pull/307
has same functionality as ReverseContourPen when applied to BezPath, but without the loss of precision from f64 to f32

use BezPath::reverse_subpaths() from latest kurbo

---

fontc/src/args.rs

As suggested in https://github.com/googlefonts/fontc/pull/480#discussion_r1345607291 I revised the help string to something I found informative when I actually ran `--help`
JMM

Update verbose flag string

---

fontbe/src/glyphs.rs
fontc/src/args.rs
fontc/src/lib.rs
fontir/src/orchestration.rs
resources/scripts/ttx_diff.py

Fixes https://github.com/googlefonts/fontc/issues/174
~~but somewhat blocked on https://github.com/googlefonts/fontations/issues/640~~ Now using the latest kurbo's BezPath::reverse_subpaths() instead of ReverseContourPen

Reverse TrueType glyph contour direction by default to match fontmake

---

fontc/src/lib.rs
fontdrasil/src/paths.rs

Helps with #41. Doesn't deal with reserved / weird filenames.

Add an underscore after capitals in glyph names

---

fontbe/src/paths.rs
fontc/src/lib.rs
fontdrasil/src/paths.rs
fontir/src/paths.rs

Continuing from #486, avoid unsafe names. As @anthrotype noted in https://github.com/googlefonts/fontc/pull/486#pullrequestreview-1664846053 it's a footgun that's all but sure to go off.
Validation of uniqueness is deferred to https://github.com/googlefonts/fontc/issues/487.

Further improve generation of safe filenames

---

fontbe/src/features.rs
fontbe/src/fvar.rs
fontbe/src/post.rs
fontc/src/args.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
fontir/src/serde.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

Related to: #248
Reads postscript names from the `lib.plist` of UFO sources, and then uses them when writing the post table.
Compiling Oswald using its `Makefile` yields an identical post table to that of a fontc-compiled UFO-based Oswald.
Tests not yet updated to account for the extra field on `StaticMetadata`, or extra parameter of `StaticMetadata::new`. Very much just a proof of concept to gather feedback and see if there are any changes wanted in our approach before updating tests. Naturally, tests should also be added for reading/writing these names.
For discussion:
1. How do we want to handle duplicate postscript entry values?
2. What auto-generation do we need to implement for glyph names that are not included in AGLFN? What does `fontmake` do?
3. Do we want to add a CLI flag to …

Postscript names for UFO sources

---

resources/scripts/ttx_diff.py

After PR #489 got merged, fontc should use the same glyph postscript names as fontmake does, so we no longer need to pass the --no-production-names flag to compare the two sets of fonts

[ttx_diff.py] remove fontmake's --no-production-names flag

---

resources/scripts/ttx_diff.py

https://github.com/googlefonts/fontc/issues/248#issuecomment-1775429891
JMM

[ttx_diff.py] pass --no-production-names until supported for both .glyphs & DS

---

fontir/src/coords.rs
fontir/src/ir.rs
fontir/src/serde.rs

Add a test to expose #499 and fix it. Fixes #499.
While we're here, coalesce  `axes_default: NormalizedLocation, variable_axes_default: NormalizedLocation,` to a single field with the default location as that's what the consuming code expects.
JMM

Don't lose MiscMetadata in serde

---

fea-lsp/editors/vscode/package-lock.json
fea-lsp/editors/vscode/package.json

Very possibly we should just delete this crate, which is a language server for FEA based on fea-rs; but in the meantime we might as well at least update these deps.
- closes #507
- closes #508
- closes #509
- closes #510

Update fea-lsp dependencies

---

resources/scripts/check_no_println.sh

A few remain; I believe these need to either go away or move to `fea-rs/src/bin/` (e.g. the compile and print warnings fn)
```shell
$ resources/scripts/check_no_println.sh
Error: The following Rust source files contain println! or eprintln! statements:
fea-rs/src/compile/compiler.rs:182:             eprintln!("{}", tree.format_diagnostic(&w, is_tty));
fea-rs/src/token_tree.rs:327:                     eprintln!(
fea-rs/src/token_tree/rewrite.rs:134:         eprintln!("\"");
Please remove or comment out the println! and eprintln! statements before pushing.
```

Add an allowlist for prints and permit a few

---

Cargo.toml
fea-rs/Cargo.toml
fontbe/Cargo.toml
fontc/Cargo.toml
ufo2fontir/Cargo.toml

This makes fea-rs use the workspace deps where possible, and makes fontbe use the local fea-rs.
It also makes a few other updates to update paths & urls in fea-rs/Cargo.toml, and it bumps a few out of date dependencies.

[chore] Update manifests post fea-rs merge

---

Cargo.toml
glyphs2fontir/Cargo.toml
ufo2fontir/Cargo.toml

it's a norad dependency but we don't import it directly anywhere in fontc (`git grep quick_xml` returns nothing) so there's no need to have it here, is there?

Remove unused quick-xml

---

fea-rs/Cargo.toml
fea-rs/src/bin/compile.rs
fea-rs/src/compile.rs
fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/validate.rs
fea-rs/src/compile/variations.rs
fontbe/src/features.rs

* Make fontbe depend on the local fea-rs
* Share coord types
* Simplify the VariationInfo trait as a result. 
Fixes https://github.com/cmyr/fea-rs/issues/242
Note that I retained the fea-rs AxisLocation to represent the raw value parsed. It has to be turned into a fontdrasil coord to be able to change types.

fea-rs => fontc coords

---

Cargo.toml
fea-rs/src/common.rs
fea-rs/src/common/glyph_class.rs
fea-rs/src/compile.rs
fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/compiler.rs
fea-rs/src/compile/feature_writer.rs
fea-rs/src/compile/features.rs
fea-rs/src/compile/language_system.rs
fea-rs/src/compile/lookups.rs
fea-rs/src/compile/lookups/gpos.rs
fea-rs/src/compile/tables/gdef.rs
fea-rs/src/lib.rs
fontbe/src/features.rs
fontc/src/lib.rs
fontdrasil/src/types.rs

Migrate https://github.com/cmyr/fea-rs/pull/241 to fontc. Rebase on #516; that should be merged first.
Fix a test that took up failing because we assumed no user features meant no features at all and that stopped being true when we added feature writers.
Copied from fea-rs, @cmyr's notes:
This PR is a start on providing API that allows the client to specify additional feature code at compile time, without needing to use FEA as an IR.
This involves:
- letting the client provide us with a `FeatureWriter` type during compilation
- calling this type after the compilation pass, but before assembling the final tables
- letting it add new lookups and features
- and merging these features and lookups into the overall set before building the final tables
It also involves making certain internal …

feature writer api

---

fea-rs/Cargo.toml
fontc/Cargo.toml

This was broken because fea-rs added a bunch of new binary targets, and also had set 'default-run' to its own main binary; this sets it back to be the fontc binary.
JMM

Fixup 'default-run' settings

---

fea-rs/src/compile/feature_writer.rs
fea-rs/src/compile/lookups/gpos.rs
fea-rs/src/compile/variations.rs
fontbe/src/error.rs
fontbe/src/features.rs
fontc/src/lib.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
resources/scripts/ttx_diff.py
resources/testdata/glyphs2/WghtVar_Anchors.glyphs
resources/testdata/glyphs2/WghtVar_Anchors.glyphspackage/glyphs/brevecomb.glyph
resources/testdata/glyphs2/WghtVar_Anchors.glyphspackage/order.plist
resources/testdata/glyphs3/WghtVar_Anchors.glyphs
resources/testdata/glyphs3/WghtVar_Anchors.glyphspackage/glyphs/brevecomb.glyph
resources/testdata/glyphs3/WghtVar_Anchors.glyphspackage/order.plist

Starting to work toward marks based on discussion with @anthrotype. Likely to be step one in a series of PRs.
Helps with https://github.com/googlefonts/fontc/issues/308.
Builds on @cmyr's work to avoid generating fea strings in #496. Rebased to sit on top of fea-rs merge into fontc and the feature writer api (#517).
Includes API sketch from https://github.com/cmyr/fea-rs/pull/243, updated per https://github.com/cmyr/fea-rs/pull/243#discussion_r1370696462.
`fontbe/src/features.rs` is the heart of it.

First step toward marks

---

fea-rs/src/compile/lookups/helpers.rs
fea-rs/src/compile/variations.rs
fea-rs/test-data/fonttools-tests/PairPosSubtable.expected_diff
fea-rs/test-data/fonttools-tests/bug633.expected_diff

We previously matched otlLib, but that order is slightly funny and doesn't match what varLib does, and varLib is more relevant for fontc.
I expect that otlLib will be update shortly to match this behaviour in any case.

[fea-rs] Tweak logic for assigning glyph class ids

---

fontc/src/lib.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs

The v2 notation is up-converted to equivalent layer attributes' coordinates as found in v3 sources.
We already have test files for glyphs{2,3}/IntermediateLayer.glyphs, because we checked them in when we added support for sparse DS sources, so the tests simply check that we get the same result whether we build from glyphs2, glyphs3 or DS sources (the latter were originally converted from .glyphs using `fontmake -o ufo`).
Fixes #62

Add support for intermediate (aka "brace") layers from Glyphs sources

---

fea-rs/src/common.rs
fea-rs/src/common/glyph_class.rs
fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/feature_writer.rs
fea-rs/src/compile/lookups.rs
fea-rs/src/compile/lookups/contextual.rs
fea-rs/src/compile/lookups/gpos_builders.rs
fea-rs/src/compile/lookups/helpers.rs
fea-rs/src/compile/tables/gdef.rs
fea-rs/src/lib.rs
fea-rs/test-data/compile-tests/mini-latin/good/single_sub_format_c.fea
fea-rs/test-data/compile-tests/mini-latin/good/single_sub_format_c.ttx
fontbe/src/features.rs

This is a funny patch, but it addresses a long-standing wart in fea-rs that regained my attention in the process of working through how our ClassDefs were assigning ids differently than was fontmake.
The tl;dr is that what FEA calls a 'glyphclass' is just an arbitrary sequence of glyphs. In several places, however, we use these classes in places where we are representing members of an OpenType ClassDef. In these cases, we need to do things like compare two sets for equality, and in this case we want to have a fixed order, and ignore duplicates.
The previous implementation was ad-hoc, using a `sort_and_dedupe` method in certain places, where it would take some arbitrary `GlyphClass` and turn it into one that conformed to these expectations; but we were not using it consistently, and it …

Add 'GlyphSet' type to fea-rs to encode the property of a sorted & deduped set of glyphs

---

resources/testdata/designspace_from_glyphs/WghtVar-Regular.ufo/glyphs/hyphen.glif
resources/testdata/designspace_from_glyphs/WghtVar.designspace
resources/testdata/designspace_from_glyphs/WghtVar_Anchors-Bold.ufo/glyphs/brevecomb.glif
resources/testdata/designspace_from_glyphs/WghtVar_Anchors-Bold.ufo/glyphs/contents.plist
resources/testdata/designspace_from_glyphs/WghtVar_Anchors-Bold.ufo/lib.plist
resources/testdata/designspace_from_glyphs/WghtVar_Anchors-Regular.ufo/glyphs/brevecomb.glif
resources/testdata/designspace_from_glyphs/WghtVar_Anchors-Regular.ufo/glyphs/contents.plist
resources/testdata/designspace_from_glyphs/WghtVar_Anchors-Regular.ufo/lib.plist
resources/testdata/designspace_from_glyphs/make_designspace.sh
resources/testdata/glyphs2/WghtVar_NoExport.glyphs
resources/testdata/glyphs3/WghtVar_NoExport.glyphs

Re-ran resources/testdata/designspace_from_glyphs/make_designspace.sh with new input. It also changed some existing files.
hyphen is not exported while being used as a component, meant to trigger "If the non-export glyphs are used as components in other composite glyphs, [the components will get decomposed](https://github.com/googlefonts/ufo2ft/blob/efb4658890ba645292a9c6bc055c91afe225c4a1/Lib/ufo2ft/util.py#L65-L87) as the base glyphs they point to get pruned." (https://github.com/googlefonts/fontc/issues/532)
The new test files are not yet used and would not compile correctly if they were. Baby steps.

Add test files that restrict glyph export

---

fontbe/src/os2.rs
fontc/src/lib.rs
fontir/src/ir.rs
fontir/src/serde.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

Turns out the default is format-specific. Helps with #530.

Match fontmake defaults for fsType

---

fontbe/src/features.rs
resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Bold.ufo/glyphs/hyphen.glif
resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Bold.ufo/lib.plist
resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Regular.ufo/glyphs/hyphen.glif
resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Regular.ufo/lib.plist
resources/testdata/glyphs2/WghtVar_NoExport.glyphs
resources/testdata/glyphs3/WghtVar_NoExport.glyphs

the first commit adds a bunch of anchors to a no-export glyph "hyphen" in WghtVar_NoExport.glyphs test file to  trigger issue https://github.com/googlefonts/fontc/issues/555
Will follow up with a fix

Fix MissingGlyphId while building mark feature with a non-export glyph with anchors

---

fontbe/src/features.rs
fontc/src/lib.rs

We used to produce a lookup per base (ty @cmyr for noticing!) which isn't quite right.

Push building a lookup up one level

---

fontbe/src/features.rs
fontir/src/ir.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

This replaces our use of HashMap with BTreeMap in various places where we later iterate over a collection, which ensures that we are constructing our features in the same order (ensuring that, for instance, the same item has the same delta set index between builds)
JMM

[fontc] Ensure feature code is deterministic

---

fontc/src/workload.rs

Simplified version of #466. Impact is most readily visible in the timing output:
Before:
kern may start as far right as the edge of the blue (be glyph) jobs.
After:
kern will consistently start at the left edge (earlier) of the blue jobs. Trying to detect a measurable performance boost with hyperfine was inconclusive, which is better flips run to run. Amusingly Oswald is now too fast for hyperfine to get useful #s at all on Mac. I tried the following:
```shell
$ cargo build --release && hyperfine --warmup 10 --runs 50 --prepare 'rm -rf build/' 'target/release/fontc --source ../OswaldFont/sources/Oswald.glyphs --emit-ir false'
$ cargo build --release && hyperfine --warmup 3 --prepare 'rm -rf build/' 'target/release/fontc --source ../googlesans/source/GoogleSans/GoogleSans.designspace …
```

Directly interfere to start kern sooner

---

fea-rs/src/compile/lookups/gpos_builders.rs
fea-rs/test-data/compile-tests/mini-latin/good/early_kern_rules_win.fea
fea-rs/test-data/compile-tests/mini-latin/good/early_kern_rules_win.ttx

Thanks @simoncozens for reporting this and proposing a fix, I just applied that and added a test for confirm.
https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#6bii-enumerating-pairs
> Specific pairs generated by an enum rule may be overridden by specifying preceding single pairs. Because of this case, it is not an error when specific kern pairs conflict because they have the same glyphs. When specific kern pair rules conflict, the first rule specified is used, and later conflicting rule are skipped.
Fixes https://github.com/googlefonts/fontc/issues/550

[fea-rs] ensure first wins when specific kern rules conflict

---

fontbe/src/features.rs
glyphs2fontir/src/source.rs
resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Bold.ufo/groups.plist
resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Bold.ufo/kerning.plist
resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Regular.ufo/groups.plist
resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Regular.ufo/kerning.plist
resources/testdata/glyphs2/WghtVar_NoExport.glyphs
resources/testdata/glyphs3/WghtVar_NoExport.glyphs
ufo2fontir/src/source.rs

to trigger the other issue noted at https://github.com/googlefonts/fontc/issues/555#issuecomment-1804163641
> when collecting the glyph groups, we let non-export glyphs in the kerning groups IR, but the the fontbe kern feature generator arbitrarily assigns gid 0 (.notdef?!) to missing glyphs when construcing the coverages which is wrong. Since we are pruning pairs from the kerning IR when single glyphs are not in the glyph order, we should similarly also prune missing/non-export glyphs when they occur inside a kerning group as we construct the kerning IR.

ensure non-export glyphs get pruned from kerning groups

---

fontc/src/change_detector.rs
fontc/src/error.rs
fontc/src/lib.rs
fontc/src/main.rs
fontc/src/timing.rs
fontc/src/workload.rs

I believe I can also migrate some of the work in glyph order out of it to avoid having it block the world.
Before, glyph order blocks all be work:
After, some be (blue) work can happen before glyph order:
Hopefully part of a series leading to improvements wrt #456.

Don't block on glyph order if you don't have to

---

README.md
fontc/src/args.rs
fontc/src/change_detector.rs
fontc/src/config.rs
fontc/src/lib.rs
fontir/src/orchestration.rs
resources/scripts/time_build.py

As discussed with Rod in chat, we prefer to have incremental builds be opt-in rather than opt-out. Not only it's faster to build without, but also it reduces the risk that the casual user might incur in potential bugs on subsequent builds related to incomplete inter-task dependencies (I know, we should test this code path more to be more confident about it).
Also I propose to rename the option from `--emit-ir` to `--incremental` because the latter communicates the intent better to the user. The old name is kept for backward compatibility but it won't be shown in the --help.
The flag takes an optional bool argument, which can thus be omitted altogether for simplicity.
E.g. --incremental is equivalent to --emit-ir=true; omitting the whole flag (default behavior) is equivalent to …

don't emit IR by default and rename option to --incremental

---

README.md
fontbe/src/paths.rs
fontc/src/args.rs
fontc/src/change_detector.rs
fontc/src/lib.rs
fontc/src/main.rs
resources/scripts/ots_test.sh
resources/scripts/time_build.py
resources/scripts/ttx_diff.py
smoke_test/smoke_test.py

This adds a new `-o`/`--output-file` CLI flag to tell fontc where to save the output file. It keeps defaulting to the existing `build/font.ttf` like before (we may want to change that to use, say, the font's postscript name e.g. Oswald-Regular.ttf, so one could build more than one font in the same default build directory without overwriting them? but that's a separate issue). 
Also, I changed so that the input source is a positional argument, but I didn't want to break existing usages of `-s`/`--source` option so I kept the latter and made them two methods mutually exclusive, and require at least one of the two is not None before the final Args can be constructed.
So the old way of calling fontc continues to work (e.g. `fontc --source Oswald.glyphs` or `fontc -s Oswald.glyphs`), but now …

make input arg positional, add -o/--output-file option

---

.github/workflows/gsbuild.yml

Adds a GH Action workflow to build the GS project on pull request commits with a debug build of the fontc compiler.

Add GS main branch build CI testing

---

fontc/src/args.rs

It creates problems when you do `fontc -i font.glyphs` (as it attempts to parse the positional input source as the bool argument for --incremental) so it forces one to have to put the filename in front followed by the optional parameter, e.g. `fontc font.glyphs -i`..
I think this is an unnecessary complication and would rather drop support for the old --emit-ir=true|false flag alias... I think it's fine to simplify and only have a single bool flag `-i/--incremental` that takes no parameters.

[fontc/args] don't take true|false argument in --incremental

---

.github/workflows/gsbuild.yml

--source flag is no longer needed after https://github.com/googlefonts/fontc/pull/576 (though it still works)
JMM

[gsbuild] remove superflous --source CLI flag, use positional input source

---

fontc/src/args.rs

Adds the automated clap support for command line `--version` and `-V` options to report the fontc executable version number.
Also updates the command line `--help` documentation with the following description:
```
-V, --version
Print version
```

Add automated clap --version / -V CLI version string support

---

resources/scripts/ots_test.sh

Updates the ots_test.sh shell script to use the latest OTS release version (v9.0.0 => v9.1.0)
related: #589

Bump OTS testing version to latest

---

fontbe/src/avar.rs

GS contains a `GRAD` axis whose avar segment maps does not have any interesting mappings.
It happens to be the last one in the axis order. We were filtering out axis segment maps that contain only identity maps, leading to an avar table with fewer segment maps than there are fvar axes, which is invalid as OTS correctly points out.
So we now still emit these non-interesting segment maps when bulding avar and there's at least one of them that is not an identity map.
Also note that, despite the OT spec allows for empty segment maps for axis that don't distort the default normalization, we want to match fontmake/fonttools and emit the required {-1:1, 0:0, 1:1} mappings even when no other interesting mappings are present for an axis, because apparently some old implementations need that (see …

[fontbe/avar] don't skip no-op segment maps

---

fontc/src/lib.rs

In the process of looking into how to add mark-mark tests I got a bit distracted trying to figure out a way to reduce the boilerplate in the existing tests.
This mostly does that, although it also slightly tweaks how some asserts are structured.

[fontc] More code reuse in fontc tests

---

fontir/src/glyph.rs
fontir/src/ir.rs
fontir/src/serde.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

This is a little bit of cleanup to be more consistent in our (non)use of TryInto.
No functional change, JMM

Build builder with 'build' instead of TryInto

---

fea-rs/src/parse/context.rs

I believe this was turned on by accident when I migrated fea-rs into this repo, and I noticed it was sometimes showing up in test output.
This was confusing, since normally rustc swallows stderr during test execution, and only prints it if a test fails? but apparently this depends on some implementation detail of `eprintln`, and does not apply when you do the `writeln` hack.
JMM

[fea-rs] Disable printing in test

---

fontc/Cargo.toml
fontc/build.rs
fontc/src/args.rs
fontc/src/main.rs

Adds a new `--vv` option for verbose debugging version reporting of:
- fontc version + git commit SHA hash
- rustc host triple
- rustc version + toolchain channel + short git commit SHA hash + commit date
- llvm version
- cargo profile (release / debug)
- cargo optimization level
Adds a new fontc package [vergen](https://crates.io/crates/vergen) build dependency and build.rs file to set the environment variables required to define these strings at build time.  Should continue to support deterministic builds with the data fields that I've included in this report.
Example output:
```
$ target/release/fontc --vv
fontc 0.0.1 @ 39104650dd31603be7b97a169c468c39bc0e5674
x86_64-apple-darwin
rustc 1.76.0-nightly (channel: nightly, 3a85a5cfe 2023-11-20)
llvm 17.0
cargo profile: release
cargo …
```

Add verbose debugging version reporting

---

fontc/src/workload.rs

With this --incremental works again
Fixes https://github.com/googlefonts/fontc/issues/581

[workload] exclude non-runnable jobs when popping items from the run_queue

---

Cargo.toml
fontbe/Cargo.toml
fontbe/src/glyphs.rs

Instead of hard-coding tolerance=1.0, we now use the same default tolerance as fontTools.cu2qu, which is relative to the font's UPEM, i.e. UPEM/1000
Fixes https://github.com/googlefonts/fontc/issues/474

[fontbe] make cu2qu tolerance relative to UPEM

---

fea-rs/src/common.rs
fea-rs/src/compile.rs
fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/feature_writer.rs
fea-rs/src/compile/lookups.rs
fea-rs/src/compile/lookups/contextual.rs
fea-rs/src/compile/lookups/gpos_builders.rs
fea-rs/src/compile/lookups/gsub_builders.rs
fea-rs/src/compile/metrics.rs
fea-rs/src/compile/tables.rs
fea-rs/src/compile/valuerecordext.rs
fontbe/src/features.rs
fontbe/src/kern.rs
fontbe/src/orchestration.rs

Previously we used the `ValueRecord` and `AnchorTable` types in write-fonts. This had the complication that anytime you needed to include deltas you had to have access to a `VariationStoreBuilder`, which was a bottleneck for fontc.
With this change, we now just store the deltas inline in the record/anchor type, and only go and turn them into actual `write-fonts` types at the very end, after merging anything we've received from feature writers.
This patch makes the fewest changes outside fea-rs that were possible in order to get things working again; as follow up we can go and figure out how best to update the kerning/marks code to take advantage of this new model.
This requires https://github.com/googlefonts/fontations/pull/719; this includes a commit that patches Cargo.toml to point at …

Add variable-aware ValueRecord and Anchor types to fea-rs

---

fea-rs/src/compile/lookups/gpos_builders.rs
fontbe/src/error.rs
fontbe/src/features.rs
fontbe/src/kern.rs
fontbe/src/marks.rs
fontbe/src/orchestration.rs

This is followup to #598; since we don't need access to the feature builder in order to construct anchors or value records, we can now construct the various builders directly in the relevant tasks.

Construct kerning/mark lookup builders direclty

---

fontbe/src/error.rs
fontbe/src/marks.rs

We now include the name of the glyph as well as the both group names, allowing us to print a (hopefully) useful error message.
Follow up from #609

[features] Improve PreviouslyAssignedClass error

---

fontdrasil/src/coords.rs
fontdrasil/src/serde.rs
fontir/src/ir.rs
fontir/src/serde.rs

The problem was that serde_yaml doesn't like it when BTreeMap is used as the key to a collection. Since this is only the case in `Location`, it's much simpler to just have a cusom serde impl for that type.
I expect this will lead to further simplification, although I will leave that for additional PRs.
progress towards #495

[fontir] Remove custom serde impl for Kerning

---

glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/fstype_0x0000.glyphs
resources/testdata/glyphs3/fstype_0x0104.glyphs

`python resources/scripts/ttx_diff.py ../OswaldFont/sources/Oswald.glyphs` now reports OS/2 identical

Allow .glyphs to specify fsType

---

fontbe/src/metrics_and_limits.rs
fontbe/src/os2.rs
fontc/src/lib.rs
fontir/src/ir.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

using the same logic as in ufo2ft.fontInfoData.
Also read the respective fields for caret rise/run in UFO fontinfo.plist and apply them if present.
For Glyphs sources, the caret slope rise/run cannot be overridden, only indirectly via the italic angle it seems to be able to control them.

Use italic_angle to set default hhea caret slope/run

---

glyphs-reader/src/font.rs
resources/testdata/glyphs3/CustomOrigin.glyphs

If you create a New Font from Glyphs.app and then add a 'Variable Font Origin' custom parameter (which we currently do support) and set this to the first and only master that the newly created font comes with (which Glyphs.app assigns the id of `m01` using an unquoted plist string), and then attempt to compile, you will get a ParseIntError when parsing the custom parameters, because glyphs-reader thinks that it is an integer.
I add a reproducer first, and follow up with the actual fix.

[glypsh-reader] fix ParseIntError when custom param has unquoted string

---

fontc/src/error.rs
fontir/src/error.rs

There were a number of places where we had access to additional information that we were not presenting in our error messages.

Improve error messages in fontc/fontir

---

fontbe/src/post.rs
fontir/src/ir.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

they are not _static_ metadata, as they can vary across masters and MVAR defines tags for them.
Note I'm using the Glyphs.app default underlinePosition for fontir::GlobalMetrics' default `UnderlinePosition` (ie. -0.1 * units_per_em), however in ufo2fontir I override that with ufo2ft's default underlinePosition.
This way, we match the current fontmake output (in absence of explicit underline settings) for both .glyphs and .designspace inputs, even though... well they don't match one another for historical reasons which nobody can care less

move underline_thickness/position to GlobalMetrics as they are MVAR-iable

---

fontbe/src/avar.rs
fontbe/src/cmap.rs
fontbe/src/features.rs
fontbe/src/font.rs
fontbe/src/fvar.rs
fontbe/src/glyphs.rs
fontbe/src/gvar.rs
fontbe/src/head.rs
fontbe/src/hvar.rs
fontbe/src/kern.rs
fontbe/src/marks.rs
fontbe/src/metrics_and_limits.rs
fontbe/src/name.rs
fontbe/src/orchestration.rs
fontbe/src/os2.rs
fontbe/src/post.rs
fontbe/src/stat.rs
fontc/src/lib.rs
fontc/src/timing.rs
fontc/src/work.rs
fontc/src/workload.rs
fontdrasil/src/orchestration.rs
fontir/src/glyph.rs
fontir/src/orchestration.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

Access::Custom took a closure and required a scan over pending jobs to determine if it matched any. Instead count the number of pending jobs of each type and resolve "blocks on all of type" (e.g. all IR Glyphs) by checking if the count of those pending is 0.
Key outcome is deletion of `can_run_scan` from `fontc/src/workload.rs` . hyperfine reports no significant change in performance:
```shell
$ cargo build --release && hyperfine --warmup 25 --runs 100 --prepare 'rm -rf build/' 'target/release/fontc ../OswaldFont/sources/Oswald.glyphs'
main   130.6 ms ±  10.9 ms
branch 127.9 ms ±   8.0 ms
```
A mildly amusing outcome is that you can potentially detect that all-of(something) is done before you can detect a specific id is done because the former is a decrement to an atomic and the latter …

Remove Access::Custom; it forces table scans to figure out what can run

---

resources/scripts/ttx_diff.py

Arguably having a few points off by one after cu2qu, decomposition, and/or transformation isn't worth the effort to fix. Exploring what allowing a small but non-zero number of x/y values to differ from fontmakes by 1 might look like.
See #483. We should still address rounding (#235) because for NLI that could accumulate a significant error.
@anthrotype wdyt?

Allow 0.1% of coordinates to differ from fontmake by 1

---

fontdrasil/src/coords.rs
fontdrasil/src/piecewise_linear_map.rs
fontdrasil/src/serde.rs

This contains two commits, one that removes the serde impl and one that removes the custom iterator in favour of `iter().map()`.
One other note here: it *feels* to me like `OrderedFloat` is basically an implementation detail, and that we shouldn't need to use it in public API, but I see that it is used in lots of places so I'm not totally sure. Does anyone remember the original motivation for using this type? was it just ensuring that we have `Eq` and `Ord`, for putting it in collections?
oh I also had another question: I noticed that the `PiecewiseLinearMap` stores floats instead of our `Coord` types... is this because we anticipated it being used in other places? If not I think the API would be clearer if we just used the coord types directly here. (edit: I think i can answer my own …

Cleanup for the CoordConverter type

---

fontdrasil/src/lib.rs

It is not actually used anywhere else currently, and making it private provides some benefits (specifically we will more warnings about unused methods/dead code)
(JMM)

[fontdrasil] Make piecewise_linear_map module private

---

ufo2fontir/src/source.rs

we were calling the (very expensive) kerning_groups_for function twice, whene we can trivially reuse the results of the first call.
this looks to make a measurable difference before/after (in a profile this fn accounted for .6% of the total compile time)
```
Benchmark 1: target/release/fontc ../fontfiles/googlesans/source/GoogleSans/GoogleSans.designspace
Time (mean ± σ):      4.327 s ±  0.060 s    [User: 6.830 s, System: 3.038 s]
Range (min … max):    4.252 s …  4.443 s    10 runs
Benchmark 1: target/release/fontc ../fontfiles/googlesans/source/GoogleSans/GoogleSans.designspace
Time (mean ± σ):      4.282 s ±  0.044 s    [User: 6.835 s, System: 3.034 s]
Range (min … max):    4.218 s …  4.349 s    10 runs
```
(JMM)

[ufo2fontir] Avoid duplicate loading of kerning groups

---

fontir/src/ir.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

I just made a similar change in ufo2ft, see https://github.com/googlefonts/ufo2ft/issues/804
JMM

use units_per_em for default caret_slope_rise

---

fontbe/src/os2.rs
fontir/src/ir.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

if the source file does provide generic ascender/descender values, we need to use those to derive the OS/2 and hhea values. We want to match ufo2ft defaults.
Surprisingly the code already contained urls to ufo2ft's source code but it didn't actually match the code it linked to..

match ufo2ft's default ascender/descender settings

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/variations.rs
fontbe/src/avar.rs
fontbe/src/features.rs
fontbe/src/glyphs.rs
fontbe/src/kern.rs
fontbe/src/marks.rs
fontbe/src/orchestration.rs
fontbe/src/test_util.rs
fontc/src/change_detector.rs
fontc/src/lib.rs
fontc/src/timing.rs
fontc/src/workload.rs
fontdrasil/src/coords.rs
fontdrasil/src/orchestration.rs
fontir/src/glyph.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
fontir/src/paths.rs
fontir/src/source.rs
fontir/src/variations.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

Step toward #639. Doesn't produce a speedup yet but I like the better threading. Basically breaks up the leftmost kern from https://github.com/googlefonts/fontc/issues/610#issuecomment-1833125480. 
Things to poke in subsequent PRs:
1. Read file sooner, that has no need to block on glyph order etc
1. Looks like kern_at could have started sooner than it did
1. BE kerning spends a lot of time in a big loop, might be worth splitting up
* GS has about 60k pairs to loop over, we could just break into N groups, say num CPUs or just a fixed value

Try spreading FE kerning across threads per location

---

layout-normalizer/src/gpos.rs

This now ensures that rules from all subtables in a lookup are correctly combined, and also adds the 'first hit wins' logic, ignoring any item (in the main coverage table) in a subtable that has appeared in a previous subtable for the same lookup.

[ttx_diff] Fix incorrect subtable handling

---

layout-normalizer/build.rs

The path I'd used didn't exist, which caused cargo to more aggressively rebuild this target.

[ttx_diff] Fix incorrect path in build script

---

layout-normalizer/src/common.rs
layout-normalizer/src/gpos.rs

Sometimes a given feature has a common set of lookups, which are shared between multiple language systems. In this case, we will now just print rules once.
For a large font this brought our output size down from 400+ mb to ~30mb, which is still too much but isn't *insane*.
(we didn't notice this problem before because fonts with a large number of rules/lookups/systems are likely using extension lookups, and we were just skipping those)

[ttx_diff] Group language systems with identical lookups

---

fea-rs/src/compile/features.rs

Helps with #647. After this change GSUB and gvar are the same size, binary different, and ttx equal. Previously ttx had a diff about UINameValue.
```shell
<FeatureParamsStylisticSet>
<Version value="0"/>
-            <UINameID value="264"/>  
+            <UINameID value="259"/>  
</FeatureParamsStylisticSet>
$ f=../googlesans/source/GoogleSans/GoogleSans.designspace; \
export SOURCE_DATE_EPOCH=$(date +%s); \
cargo build --release && rm -rf build/ \
&& target/release/fontc $f && cp build/font.ttf build/first.ttf \
&& target/release/fontc $f && cp build/font.ttf build/second.ttf \
&& diff -u <(fonttools ttx -o - -l build/first.ttf | tail -n +2) <(fonttools ttx -o - -l build/second.ttf | tail -n +2)
...
----  ----------  --------  --------
GDEF  0x264FC9B0     18586       300
GPOS …
```

Stable name order

---

.github/workflows/rust.yml
fontbe/src/kern.rs
fontbe/src/marks.rs
fontdrasil/src/coords.rs

This also fixes some existing broken links.
locally I'm getting warnings printed everytime I run the pre-push checks, so we should be catching this in CI.
JMM

[ci] Fail CI if docs contain broken links

---

fea-rs/src/compile.rs
fea-rs/src/compile/lookups.rs
layout-normalizer/Cargo.toml
layout-normalizer/src/gpos/pairpos.rs

This changes the logic around skipping rules to only skip if there is an entry for the _pair_, instead of for the first glyph.
Most of this PR is a test and a bunch of test-setup code which I hope to reuse.
This uses the builders in fea-rs, and doing that required me to make a trait in there public, but that seems fine.
- closes #657 
- progress on #643

[ttx_diff] Better handling of pairpos subtables

---

Cargo.toml
fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/variations.rs
fontbe/src/features.rs
fontbe/src/hvar.rs
layout-normalizer/src/gpos/pairpos.rs

This involves a breaking change to the VariationStoreBuilder, which in turn requires us to tweak the FeatureProvider trait in fea-rs, but overall fairly painless.

[chore] Update write-fonts to 0.21.0

---

layout-normalizer/src/common.rs
layout-normalizer/src/gpos/marks.rs
layout-normalizer/src/gpos/pairpos.rs

As with pairpos, we will only skip a rule if the (base, mark) pair has already been seen in a preceding subtable.

[ttx_diff] Better handling of mark pos subtables

---

layout-normalizer/src/common.rs
layout-normalizer/src/gpos.rs
layout-normalizer/src/gpos/marks.rs
layout-normalizer/src/gpos/pairpos.rs

This is just a refactor, with no functional changes.
This is ultimately just a better, simpler implementation. It preserves more information about lookup order, which will be helpful as we try to do things like unify overlapping rules across lookup boundaries.

[ttx_diff] Less type erasure in layout-normalizer

---

Cargo.toml

required for https://github.com/googlefonts/fontc/issues/647

bump write-fonts to 0.21.1

---

fontbe/src/kern.rs
fontc/src/workload.rs

I believe this resolves the issue described at https://github.com/googlefonts/fontc/issues/647#issuecomment-1889793531 by applying the same fix as #655 to the second scatter/gather we do on kerning.
I have filed #677 to track making this simpler as it's definitely harder than it shoudl be.
The following produces observably unstable output on main, usually in 2-4 builds, and is stable through 20 cycles after the fix:
```shell
$ rm -f *.ttxl threads*.svg && for i in {0..19}; do echo "CYCLE $i" && rm -rf build/ && cargo run ../googlesans/source/GoogleSans/GoogleSans.designspace --emit-timing && cp build/threads.svg ./threads_$i.svg && ttx -l build/font.ttf > run$i.ttxl && grep GPOS *.ttxl; done
CYCLE 2
Finished dev [unoptimized + debuginfo] target(s) in 0.19s
Running `target/debug/fontc …
```

Fix the order of BE kern gathering

---

.github/workflows/rust.yml
resources/scripts/repeatable-builds.sh

This PR adds a new shell script to help debugging repeatable builds locally, and adds Oswald to the CI testing repeatable builds (the gvar randomness about order of shared tuples would only trigger when building Oswald, not GS somehow).
Finally, I added a step to upload the built ttfs as CI artifacts if any failure occurs, also useful for remote debugging.

Add repeatable-builds.sh and test Oswald as well

---

layout-normalizer/src/common.rs
layout-normalizer/src/gpos.rs
layout-normalizer/src/gpos/marks.rs
layout-normalizer/src/gpos/pairpos.rs
layout-normalizer/src/gpos/test_helpers.rs

This adds the proper normalization logic for pairpos rules: basically we will now sum the values in subsequent lookups that apply to the same pairs.
this PR also involves moving some test helpers to a common `test_helpers` module, since they're needed by different tests that live in different places.
There's one question inline: basically I'm not sure how we should think about merging of device tables, or if we should care. Also I'm assuming that if deltas are provided there should be the same number of deltas in each master, and we can just sum them individually?

[ttx_diff]: Normalize kern rules

---

layout-normalizer/src/common.rs
layout-normalizer/src/gpos.rs
layout-normalizer/src/gpos/marks.rs
layout-normalizer/src/gpos/test_helpers.rs

This is conceptually simple, although the implementation is a bit hairy: basically we want to track the last time we see each (base, mark) pair, and then we want to go through all the rules and remove any pairs that are going to be included later on.

[ttx_diff] Normalize marks

---

fea-rs/src/bin/ttx_test.rs
fea-rs/src/tests/compile.rs
fea-rs/src/util/ttx.rs

This utility had broken a bit during the move from the old fea-rs repo into this new repo; in particular it would fail if you ran it from the `fea-rs` directory, which is annoying.
We will now attempt to figure out where we're running from when determining the path to the test data, instead of hardcoding paths.
JMM

[fea-rs] Fixups for ttx_test util

---

Cargo.toml
fontc/Cargo.toml
fontc/src/change_detector.rs
fontir/src/ir.rs
fontra2fontir/Cargo.toml
fontra2fontir/README.md
fontra2fontir/src/lib.rs
fontra2fontir/src/source.rs

Fontra source can describe varc so having an IR source for it seems like it will be handy.
Per discussion with Just we will want to ingress their json format, not .rcjk.
Fontra json examples can be found in https://github.com/notofonts/noto-cjk-varco action runs, e.g. https://github.com/notofonts/noto-cjk-varco/actions/runs/7714671850. In subsequent PRs I will add sample sources to resources.

Add fontra2fontir without an actual implementation

---

fea-rs/src/parse/context.rs
fea-rs/src/token_tree.rs
fea-rs/src/token_tree/cursor.rs

This was part of a pattern I had copied from rust-analyzer but removing it has only a minor impact on performance and allow Node to be Sync, which we need in fontc.

[fea-rs] Remove use of Cell from Node

---

resources/scripts/requirements.txt

Reverts googlefonts/fontc#702
Found a bug in ufo2ft v3 (used by fontmake 3.8.0) related to --drop-implied-oncurves (which we use in ttx_diff.py):
https://github.com/googlefonts/ufo2ft/pull/817
The Oswald glyf/gvar tables that we build with fontmake 3.8 with --drop-implied-oncurves option enabled is invalid because of it, thus it shows spurious diffs when compared against the respective fontc tables.
We may want to revert until it gets fixed (hopefully tomorrow once I add a test to that PR so we won't regress again)

Revert "use the latest fontmake 3.8.0"

---

fea-rs/test-data/README.md

This used to be in a separate repo, so the link was useful. Now the link is not useful, and also wrong.
JMM

[fea-rs] Fixup test-data/README.md

---

resources/scripts/requirements.txt

fontmake 3.8.0 (actually one of its deps i.e. ufo2ft v3) had a regression which has been fixed with this bugfix release:
https://github.com/googlefonts/ufo2ft/releases/tag/v3.0.1
https://github.com/googlefonts/fontmake/releases/tag/v3.8.1
Reverts #704

requirements.txt: update fontmake to 3.8.1

---

fontra2fontir/src/fontra.rs
fontra2fontir/src/toir.rs

Try to make field matching in fontra more obvious with newtypes. Don't reinvent chunks.

---

ufo2fontir/src/source.rs

Currently with a UFO like this:
```
<key>familyName</key>
<string>Noto Sans Balinese</string>
<key>styleMapFamilyName</key>
<string>Noto Sans Balinese</string>
<key>styleMapStyleName</key>
<string>bold</string>
<key>styleName</key>
<string>Bold</string>
<key>trademark</key>
```
fontc produces a font like this:
```
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
Noto Sans Balinese
</namerecord>
<namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
bold
</namerecord>
<namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
2.005;GOOG;NotoSansBalinese-bold
</namerecord>
<namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
Noto Sans Balinese bold
</namerecord>
<namerecord nameID="5" platformID="3" platEncID="1" langID="0x409"> …
```

Correct case of subfamily name

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/src/parse/grammar/gsub.rs
fea-rs/src/token_tree/rewrite.rs
fea-rs/src/token_tree/typed.rs
fea-rs/test-data/compile-tests/mini-latin/good/contextual_null_sub.fea
fea-rs/test-data/compile-tests/mini-latin/good/contextual_null_sub.ttx

- closes https://github.com/cmyr/fea-rs/issues/246
cc @simoncozens

[fea-rs] Support inline 'by Null' in contextual sub

---

resources/scripts/ttx_diff.py

fontc only builds a STAT table when compiling a variable font, if one attempts to use ttx_diff to compare a static font then an AssertionError will trigger. ttx_diff should not expect STAT to always be present.

[ttx_diff] skip STAT if it is missing

---

fea-rs/src/parse/grammar/glyph.rs

This will now correctly identify when a glyph class contains an invalid token, and will continue on afterwards to parse the rest of the glyph class.
JMM

[fea-rs] Improve glyph class parsing error messages

---

ufo2fontir/src/toir.rs

Components with a xyScale and yxScale are currently broken. Noto Sans Balinese before this patch:
After:
Comment explains why.

Correct ordering of transform coefficients

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/lookups.rs
fea-rs/src/compile/output.rs
fea-rs/src/compile/tables.rs
fea-rs/src/compile/tables/gdef.rs

- ClassId was a pre-write-fonts enum standing in for the GlyphClassDef enum, which we can now juse use directly
- passing any explicit GDEF classes through to the output feels like the simplest way to expose these to manual feature generation code, since that code needs to compile anyway to get the GSUB table.
The motivation here was that I want the explicit classes in a more user-friendly format, instead of having to go muck about in the compiled GDEF ClassDef table/recheck the AST to figure out if it was inferred or not, etc.

[fea-rs] Remove ClassId, add gdef classes to output

---

fontc/src/lib.rs

Kind of a funny one: the chrono crate, in a patch release, deprecated a method. In CI we run clippy and set it to 'deny warnings', which makes this an error, and means that CI is currently not passing.
JMM

[chore] Fix deprecation in chrono crate

---

fontbe/src/error.rs
fontbe/src/kern.rs
fontbe/src/orchestration.rs
fontc/src/lib.rs
fontdrasil/src/types.rs
fontir/Cargo.toml
fontir/src/ir.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

This encodes in the type system the idea that kerning groups have an associated side, instead of having this be encoded as a prefix on a string.
This removes the need to hae separate `KernSide` enums, and removes possible complications around using the same type for glyph names and group names.
----
I was expecting this to be a smaller diff, but overall I think it's at least a modest improvement.

Add KernGroup type

---

fontbe/src/kern.rs

This was way more confusing than it should've been, but ultimately I
believe this is correct. It brings the oswald diff from 8.6k/3.3k to
7.5k/2.2k, which is very promising.
I do now see one additional difference in kerning, which is that in some cases we have identical values at each position in the designspace; this means we don't need to store deltas at all. We're also sometimes storing explicit 0 values, which is also unnecessary.
CI is currently broken, pending #726.
this is based on #725, which will go in when CI is fixed.

Kern alignment

---

fontbe/src/kern.rs

This skips writing sets of all-zero deltas.
This removes the last funny numerical diffs I was seeing in the generated kerning, which hopefully means the only remaining differences are related to script splitting (and so will make debugging that work much simpler)

[kerning] Prune nop deltas

---

fontbe/src/features/marks.rs

This was a significant source of noise in the diff.

[marks] Prune nop deltas from marks

---

Cargo.toml
fea-rs/src/common/glyph_class.rs
fea-rs/src/compile/lookups.rs
fea-rs/src/compile/lookups/gpos_builders.rs
fea-rs/src/compile/metrics.rs
fea-rs/src/token_tree/typed.rs
fontbe/Cargo.toml
fontbe/src/features.rs
fontbe/src/features/kern.rs
fontbe/src/features/ot_tags.rs
fontbe/src/features/properties.rs
fontbe/src/orchestration.rs
fontc/src/workload.rs

This patch is imperfect, but I think it is worth getting something committed that we can iterate from.
- modulo a very small number of differences, this matches the output of fontmake on Oswald.
- this does not correctly set the lookup flags (or mark filtering set); I'll do that as a followup
- this does not handle the 'dist' feature
- the testing here is anemic. I have at least figured out *how* to write tests against this, and I see that there are some ideas at https://github.com/googlefonts/ufo2ft/blob/cea60d71dfcf0b1c0fa4e133ec4231ba06fe0da0/tests/featureWriters/kernFeatureWriter_test.py that look worth porting, but I think it makes sense to focus on this as I continue to refine.

Split kerning by script

---

fontbe/src/features.rs
fontbe/src/features/common.rs
fontbe/src/features/kern.rs
fontbe/src/orchestration.rs

This adds a `PendingLookup` type so that we can compute and store the lookup flag and the mark filtering sets when we generate the kerning lookups.
based on #731, which should go in first.

set lookupflag and mark filtering set for kerning lookups

---

fontc/src/lib.rs

I was seeing a panic where we were trying to create the directory "" if I passed `fontc -o myfont.ttf` e.g. a relative path to a file. Per the docs on Path::parent,
> .. Returns `Some("")` for relative paths with one component
So we need to explicitly check this case.
In the process I also tweaked the signature of require_path; there's no need to return a `PathBuf` that is identical to the path that was passed by the user (and we were always throwing away the returned path in any case.)

Guard against empty parent path

---

layout-normalizer/src/gpos/pairpos.rs

When checking whether a value record was empty we were only considering the default metrics, not the deltas.

[ttx_diff] Fix logic bug in normalizer

---

resources/scripts/ttx_diff.py

Previously the fontc output would live in `build/{compare}/font.ttf`, and the fontmake output would live in `build/{compare}/{source}`, which was unintuitive.
Now fontc write `build/{compare}/fontc.ttf` and fontmake writes `build/{compare}/fontmake.ttf`.
- this requires #737

[ttx_diff] Make generated fonts easier to find

---

fontbe/src/features/kern.rs

These were not available when this code was first written.
based on #735

[kern] Use LookupFlag constants

---

fontbe/src/features/kern.rs
fontbe/src/orchestration.rs

Generated kerning only ever sets one value record, so we don't need to define both in our IR.

[kerning] Remove second record from PairPosEntry

---

fontbe/src/orchestration.rs

this is one argument for preferring `pub(crate)` to `pub` where possible: you don't get warnings if items marked `pub` are unused.

[cleanup] Delete some dead code

---

fontbe/src/error.rs
fontbe/src/features/kern.rs
fontbe/src/orchestration.rs

Following the general principle of "validate data as early as possible.
This validates the raw kerning data when it is assembled from the IR, which means that subsequent code can use that data without needing to handle error conditions.
In particular, we ensure that:
- all glyphs and groups referenced in a rule exist
- all glyphs referenced in a group exist
- groups are non-empty
Missing items are filtered, and a warning is logged.

[kerning] Pre-validate kerning groups & pairs

---

README.md

Preview: https://github.com/googlefonts/fontc/tree/readme-depmap?tab=readme-ov-file#dependency-map
Fixes https://github.com/googlefonts/fontc/issues/607

Add a graph of dependencies to the README

---

fontbe/src/error.rs
fontbe/src/features.rs
fontbe/src/features/kern.rs
fontbe/src/features/marks.rs
fontir/src/ir.rs

There were a few giant FIXMEs in the resolve_variable_metric fn; if memory serves I think I'd initially written that patch as "just a sketch" and then it was merged to unblock other work.
In any case, this rationalizes things a bit, adding error variants for the case where we can't compute deltas for anchors & kerns.

[fontbe] Fixup errors for variable metrics

---

fea-rs/src/common/glyph_class.rs
fontbe/src/features/kern.rs
fontbe/src/orchestration.rs

This reworks how we do kerning in order to preserve information about whether rules included a glyph class until we are ready to do the final compilation.
Preserving this information lets us match the behaviour of FEA in ordering these rules, where we put (glyph, glyph) first, followed by (glyph, class), (class, glyph) and finally (class, class).
---
With this patch `ttx_diff` is producing identical output to oswald for generated kerning.

[kerning] Delay decomposing kern rules

---

fontbe/src/features/kern.rs
fontbe/src/orchestration.rs
fontc/src/lib.rs
fontir/src/ir.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

We have a proliferation of names, and we are using the name KernSide to describe this role in fontbe. I think it's ultimately less confusing to have names duplicated between ir/be in places where the types are essentially equivalent.
(happy to be disagreed with on this, but thought i'd open the PR for discussion)

[fontir] Rename KernParticipant -> KernSide

---

fontbe/src/features/marks.rs
fontbe/src/orchestration.rs
fontdrasil/src/types.rs
fontir/src/ir.rs

I'm making sense of the existing code, and cleaning up a few little inconsistencies.
- the MarkGroupName struct wasn't really part of any public api and was being used as a type alias
- the AnchorName type was aliased to 'GlyphName'
In both these cases I think it's simpler for us to just use SmolStr directly for now, and we can introduce stronger types if there is any confusion.

[fontbe] Minor marks cleanup

---

fontbe/src/features/marks.rs
fontdrasil/src/types.rs
fontir/src/error.rs
fontir/src/ir.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

This is shared between frontends, and doing this in ir simplifies backend code.

Move anchor name parsing into fontir

---

layout-normalizer/src/main.rs

Previously if we were writing to a file (instead of to stdout) we were not using buffered writes, which was causing us to be slower than we needed to be (2-3x slower for oswald in debug, on my machine)
(been investigating why the normalizer is so slow, and ran into this)

[ttx_diff] Buffer writing from layout normalizer

---

fontbe/src/error.rs
fontbe/src/features/marks.rs
fontbe/src/orchestration.rs
fontir/src/ir.rs

This patch just matches the existing behaviour, but it will be improved to match the behaviour of fontmake.
no functional change, diffs are all the same etc; just thought this would be a good checkpoint that will reduce the size of subsequent diffs.

[marks] Move marks logic into a context struct

---

resources/testdata/designspace_from_glyphs/IntermediateLayer-Black.ufo/kerning.plist
resources/testdata/designspace_from_glyphs/IntermediateLayer-Regular.ufo/kerning.plist
resources/testdata/designspace_from_glyphs/IntermediateLayer.designspace
resources/testdata/glyphs2/IntermediateLayer.glyphs
resources/testdata/glyphs3/IntermediateLayer.glyphs

I modified an existing test file that contained intermediate glyph layers. These only contribute sources for the glyph outlines and are expected to be ignored for other global font metrics or kerning.
I added a kerning pair between 'i' and 'i', defined at Regular and Black masters.
The expectaction is that these intermediate locations don't participate in kerning variations; however because we currently use a single VariationModel initialized from the union of all the _glyphs_ locations for generating deltas for the OpenType Layout features (see #407), the regions' min or max for variable kerning are computed incorrectly: in this particular example, instead of expected 0.0 (normalized Regular) and 1.0 (normalzied Black), the support's min is somewhere in between (0.6), which is where the …

Add test files to reproduce issue #407

---

glyphs-reader/src/font.rs
resources/testdata/glyphs3/ComponentAnchor.glyphs

This field is used to select which anchor should be used to position a component when multiple are available, and we need it for anchor propagation to work correctly.
Broke this out of fixups for #782; I'll rebase that when this is merged.

[glyphs] Parse 'anchor' field of glyph components

---

glyphs-reader/Cargo.toml
glyphs-reader/src/font.rs
glyphs-reader/src/glyphdata.rs
glyphs-reader/src/lib.rs
glyphs-reader/src/propagate_anchors.rs
resources/testdata/glyphs3/PropagateAnchorsTest-propagated.glyphs
resources/testdata/glyphs3/PropagateAnchorsTest.glyphs

This implements basic anchor propagation in `glyphs-reader`. Propagation happens before the conversion to IR. Handling this here lets us more closely match the behaviour of glyphs.app.
This work is based on a python rewrite of the original objc; that work (by @anthrotype) is available in [a google doc](https://docs.google.com/document/d/1bXF8usWtsInYFUYIMvq3ds4jjPdbf2uDykewYyxQ-wU/edit?resourcekey=0-EqPApxblj5YTtDOG-1bZfA).
This code is now fairly well covered by tests, and I am reasonably confident that it replicates the behaviour of the original code in at least all the obvious cases.
~The original code is tricky and handles a bunch of edge cases. Some of that is included in this, and some of that is not. In particular, this does not handle the "*origin" anchor (see #769) and it does …

Anchor propagation

---

fontbe/src/features.rs
fontbe/src/features/kern.rs
fontbe/src/features/marks.rs
fontir/src/ir.rs

I'm at the point now with marks where I'm mostly just making small fixes to address a specific issue in the diff, so I think it makes sense to checkpoint my current progress.
This has us very close to fontmake, modulo one issue where fontmake is not treating certain digraph (and presumably ngraph) glyphs as bases (itself an issue in the current python anchor propagation code: https://github.com/googlefonts/glyphsLib/issues/368). The only other obvious thing I see right now is that fontc is not setting the lookup flag or the filter glyph set; I'll tackle that next.

More marks progress

---

layout-normalizer/src/gpos.rs
layout-normalizer/src/gpos/marks.rs

We weren't handling this at all. This implementation does not do some of the fancier stuff that we do for other mark attachment rules, since these lookups are less common and it seems much less likely that there will be overlapping lookups that apply rules to the same glyphs.

[ttx_diff] Add basic support for mark2lig rules

---

.github/workflows/release.yml
pyproject.toml

For the Glyphs.app fontc export plugin (#684) we need to make precompiled binaries of fontc available to download and run without requiring to build from source. Glyphs.app already comes with Python, which in turn comes with an established and secure way to distribute and install binary packages via the Python Package Index (PyPI) and the pip installer.
With the help of a tool called maturin (see [source](https://github.com/PyO3/maturin) and [docs](https://www.maturin.rs/)) it's super easy to make Python wheels out of any Rust crate, including binary-only ones like fontc. Maturin itself is written in Rust, uses cargo under the hood, and it's primarily used to package up hybrid Python/Rust projects -- which fontc technically is not (but who knows, it may in the future get a python API as …

Add release workflow to build and publish source and binary artifacts to Github and PyPI

---

fontbe/Cargo.toml
fontbe/src/features.rs
fontbe/src/features/marks.rs
fontc/src/lib.rs
fontdrasil/src/types.rs
layout-normalizer/src/common.rs
layout-normalizer/src/glyph_names.rs
layout-normalizer/src/gpos.rs
layout-normalizer/src/gsub.rs
layout-normalizer/src/main.rs

This adds a nice mechanism for testing our mark generation, based on `layout-normalizer`.
Basically this provides a builder where you can set up some set of glyphs + anchors + GDEF categories + user FEA, and then what feature code gets generated, in a normalized textual representation.
Getting this to work required a few tweaks in various places; I made it so that `layout-normalizer` can work only with the specific tables (instead of requiring a full font) and I also tweaked the `MarkLookupBuilder` so that our testing code more closely matches what we do during regular compilation.

Mark testing harness

---

glyphs-reader/src/propagate_anchors.rs

This is just to sanity check that our behaviour is matching glyphs.app in the case where we have a glyph with multiple base components but which is not a ligature.
JMM

[glyphs] Add test for anchor propagation on digraph

---

fontc/src/lib.rs

will be fixed by #779
I push it separately to demostrate this

add (failing) test case to repro #407

---

fontbe/src/features.rs
fontbe/src/hvar.rs
fontc/src/lib.rs
fontir/src/ir.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

This fixes 'incorrect feature deltas when sparse' https://github.com/googlefonts/fontc/issues/407
The global StaticMetadata.variation_model now only includes 'full' masters (i.e. defining kerning) for both UFOs+DS and .glyphs input (previously this was the case only for the latter).
When we call `resolve_variable_metric` we make new sub-model when locations != global_model.locations(), or just reuse the global model when locations are equal -- which is currently basically always true for the common source formats (DS and glyphs) in the case of kerning, as the latter is meant to be "dense" and can only be specified for the "full" or globally-defined masters. However, we don't preclude the possibility that in the future other (or newer) source formats may define sparse kerning data, and our …

[fontbe] Fix incorrect feature deltas w/ sparse glyph sources

---

fontc/Cargo.toml

there's this nice cargo sub-command called https://github.com/cargo-bins/cargo-binstall which allows one to install pre-compiled binaries for one's own platform/architecture that are hosted on Github Releases.
This is particularly useful e.g. for https://github.com/googlefonts/fontc-action where one would like to install fontc the quickest way possible instead of building from source.
Usually cargo binstall just works and it requires no configuation, but in our particular case, because we push prefixed tags like `fontc-v{version}` instead of bare `v{version}`, then cargo binstall cannot automatically find the github releases download URL, and falls back to the slower `cargo install` (from source).
This little change to fontc/Cargo.toml should make sure the correct URL will be used.

add support for cargo binstall in fontc/Cargo.toml

---

fea-rs/src/compile/lookups/contextual.rs
fea-rs/src/compile/lookups/gsub_builders.rs
fea-rs/test-data/fonttools-tests/bug512.expected_diff

In certain situations we were unnecessarily creating duplicate lookups. Matching fonttools here is another step towards eliminating the GSUB ttx diff for oswald.
- closes #541

[fea-rs] Match fontools merging of inline GSUB 1 rules

---

Cargo.toml
fontbe/src/gvar.rs
fontc/src/lib.rs
resources/testdata/varpos.designspace
resources/testdata/varpos_Regular.ufo/features.fea
resources/testdata/varpos_Regular.ufo/fontinfo.plist
resources/testdata/varpos_Regular.ufo/glyphs/A_.glif
resources/testdata/varpos_Regular.ufo/glyphs/contents.plist
resources/testdata/varpos_Regular.ufo/glyphs/layerinfo.plist
resources/testdata/varpos_Regular.ufo/layercontents.plist
resources/testdata/varpos_Regular.ufo/lib.plist
resources/testdata/varpos_Regular.ufo/metainfo.plist

Will fix https://github.com/googlefonts/fontc/issues/815
CI will be 🔴 until https://github.com/googlefonts/fontations/pull/919 is merged write-fonts dependency bumped

[fontbe] pass explicit axis_count when constructing Gvar

---

fea-rs/test-data/compile-tests/mini-latin/good/aalt_lookup_ids.fea
fea-rs/test-data/compile-tests/mini-latin/good/aalt_lookup_ids.ttx

When we generate the aalt feature we need to insert new lookups into the beginning of the lookup list. This means we need to update all subsequent lookup ids, and I was concerned that we were not doing this correctly for lookups that were referenced by contextual rules.
It turns out we were handling this correctly, but it is a situation that deserves a test case.

[fea-rs] Add test case for adjusting aalt lookup ids

---

fea-rs/src/tests/compile.rs
fea-rs/src/util/ttx.rs

Some little edits I made during a debugging session that will be useful to preserve:
- allow logging while running compile tests
- compile tests should not require presense of both 'good' and 'bad' input sets

[fea-rs] Minor testing fixups

---

fea-rs/src/compile.rs
fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/lookups.rs
fea-rs/src/compile/lookups/gpos_builders.rs
fontbe/src/features/marks.rs
fontbe/src/orchestration.rs

This is a rewrite of the initial implementation in #794 to more closely match fontmake (and pass the basic tests there).
- ~Several tests in this PR will fail until it is rebased onto #803; these failures are the result of issues in the normalizer.~
- ~also requires #802.~

Generate MarkToLig lookups, take two

---

fea-rs/src/compile/validate.rs
fea-rs/test-data/compile-tests/mini-latin/bad/negative_lig_caret_idx.ERR
fea-rs/test-data/compile-tests/mini-latin/bad/negative_lig_caret_idx.fea
fea-rs/test-data/compile-tests/mini-latin/good/negative_lig_caret_pos.fea
fea-rs/test-data/compile-tests/mini-latin/good/negative_lig_caret_pos.ttx

When validating ligature caret statements I had the logic reversed, and was disallowing negative positions (which are fine) but allowing negative indices (which are not).
The fix is simple, and this adds some test coverage for this case.
- fixes #838

[fea-rs] Allow negative values in LigatureCaretByPos

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/lookups/contextual.rs
fea-rs/src/compile/lookups/gsub_builders.rs
fea-rs/test-data/compile-tests/mini-latin/glyph_order.txt
fea-rs/test-data/compile-tests/mini-latin/good/contextual_format_2.fea
fea-rs/test-data/compile-tests/mini-latin/good/contextual_format_2.ttx

With this change, if an existing lookup already contains the substitution that are trying to add, we will just reuse that lookup.
Our behaviour here was already slightly different from fonttools; this is a further optimization. I've opened https://github.com/fonttools/fonttools/issues/3551 there, and believe fonttools should match this behaviour.

[fea-rs] More reuse of lookups for inline multisub rules

---

fea-rs/src/parse/grammar/mod.rs
fea-rs/test-data/compile-tests/mini-latin/good/lookup_extension.fea
fea-rs/test-data/compile-tests/mini-latin/good/lookup_extension.ttx

I've never seen this syntax in the wild before, and apparently it wasn't covered by our tests. Now it is.
JMM

[fea-rs] Parse useExtension keyword in lookups

---

glyphs2fontir/src/toir.rs

rustc was complaining about this, I imagine it's related to the 1.79 update?
(not sure if we wanted to use this later or something, I erred on the side of deleting code)

[g2ir] Remove unused FontInfo field

---

fontc/src/config.rs
fontc/src/error.rs
fontir/src/error.rs
fontir/src/stateset.rs
fontra2fontir/src/fontra.rs
fontra2fontir/src/source.rs
glyphs2fontir/src/source.rs
ufo2fontir/src/source.rs

This is some initial cleanup of the errors in fontir; the next step is going to be to unify Error and WorkError.
- Replace various Error variants with a 'BadSource' error that packages up a particular error cause with the path of the problematic source
- Remove the general 'io error' variant from Error in favour of finer-grained errors that include additional context.
- get rid of `dyn Error`

[fontir] Start to refactor errors

---

fontbe/src/features/marks.rs
fontc/src/work.rs
fontir/src/error.rs
fontir/src/glyph.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
fontir/src/source.rs
fontra2fontir/src/fontra.rs
fontra2fontir/src/source.rs
fontra2fontir/src/toir.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

This also makes errors more granular:
- errors related to finding, loading, or parsing a source file are their own 'BadSource' error type, which always preserves the path of the file in question;
- errors that occur during conversion of a specific glyph are now their own 'BadGlyph' error type, which means we always preserve the name of the glyph in question when such an error occurs.
A few other variants were removed or combined.

[fontir] Unify Error & WorkError

---

fontc/src/change_detector.rs
fontc/src/config.rs
fontc/src/error.rs
fontc/src/lib.rs
fontc/src/main.rs
fontc/src/work.rs
fontc/src/workload.rs

The last little bit of error work, on top of #855.
- Removes AnyWorkError, and adds variants for BeError and and Panic to fontc::Error
- instead of returning a vec of errors when tasks fail, just return the first error we see (log the rest)
- Ensure that we always know the relevant path when we encounter an io::Error

[fontc] Tweak root error type

---

resources/scripts/ttx_diff.py

This adds a `--json` flag to the ttx_diff script. When set, the script will output a JSON dictionary describing the results of a particular operation.

[ttx_diff] Add support for outputing JSON

---

resources/scripts/ttx_diff.py

This tries to quantify the total size of the difference across all tables in a font, based on the total number of lines that differ in the ttx/otl-normalizer output.
This is not hugely scientific, but will give us a single number that we can track per-font.

[ttx_diff] Add a 'total diff' number to json output

---

resources/scripts/ttx_diff.py

This really adds up when compiling lots of crates.

[ttx_diff] run crates in --release from ttx_diff script

---

fontc_crater/Cargo.toml
fontc_crater/src/args.rs
fontc_crater/src/main.rs
fontc_crater/src/sources.rs
fontc_crater/src/ttx_diff_runner.rs
resources/scripts/check_no_println.sh
resources/scripts/ttx_diff.py

This adds the ability to diff lots of fonts and collect the aggregate results.
- this is based on #852, but also requires #860 and #861.
- This currently just outputs JSON, instead of fancier reports
- `fontmake` fails on a ton of sources, presumably because we are passing the wrong args? I think we should be using `gftools builder --generate` to generate recipes from config files or something? For instance we always pass `-o variable` to fontmake, even when we aren't building a variable font.
- but we get reasonable output for some fonts, and in that case it looks like,
```json
{
"success": {
"../gf_fonts/Advent/sources/AdventPro.designspace": {
"diffs": {
"GPOS": 1.0,
"HVAR": 0.99195546,
"OS_2": 0.9946581,
"gasp": "fontmake",
"glyf": 0.9999832,
"gvar": 0.9998928,
"head": 0.9967949, …
```

[fontc_bulk] Call out to ttx_diff script

---

fontc_crater/src/ttx_diff_runner.rs
resources/scripts/ttx_diff.py

This fixes an issue where multiple instances of ttx_diff, running in parallel, would be overwriting each other's output.

[crater] Make ttx_diff write to a tempdir

---

resources/scripts/ttx_diff.py

We were expecting each glyph in the fontmake `glyf` table to also exist in `fontc`, which is not guaranteed (I mean it should be the case, but sometimes is not)

[ttx_diff] Fix crash when glyphsets not equal

---

glyphs-reader/src/font.rs
resources/testdata/glyphs2/alignment_zones_v2.glyphs

In particular we are now more careful about associating alignment zones with the appropriate metrics.
This mostly resolves #873, with the exception that we do not correctly add additional metrics for any defined alignment zones which do not correspond to standard metrics.
This issue (in particular the removed assert) was causing us to panic on eight inputs.

[glyphs] Improve g2 -> g3 metric conversion

---

glyphs-reader/src/error.rs
glyphs-reader/src/font.rs
glyphs-reader/src/propagate_anchors.rs
glyphs2fontir/src/source.rs

A number of our crater fails are the result of glyphs that have categories or subcategories that do not exist in the current version of glyphs.
With this patch, instead of erroring when we encounter these categories we will just ignore them, and fall through as we would when no explicit category was set (in which case we infer it based on unicodes and/or glyph name.)
This also changes the sub_category field on Glyph to be non-optional, since `Subcategory` has its own `None` variant, and it feels like asking for trouble if we have two different ways of indicating none-ness.

[glyphs] Ignore unknown glyph categories

---

glyphs-reader/src/font.rs

This is followup on #874 and should close #873.
The implementation is based on looking at what actually happens to glyph sources if they contain additional alignment zones and are converted from v2 to v3, in glyphs.

[glyphs] Convert non-metric alignment zones to metrics

---

glyphs-reader/src/font.rs

This exists in one of our test fonts, and doesn't seem like it should be fatal (fontmake does the iteration in the other direction and doesn't hit this)

[glyphs] Ignore extra axes in axis mapping

---

glyphs-reader/src/font.rs
glyphs-reader/src/plist.rs

And replace it with two new variants which try to capture more context. This will hopefully make it easier to debug glyphs parsing failures.

[glyphs] Remove Error::SomethingWentWrong

---

fontir/src/variations.rs
glyphs-reader/src/glyphdata.rs

This lint feels like a misfire; we need to explicitly pass a reference because we mutate below.

[chore] Fix a clippy lint, rustfmt

---

resources/scripts/requirements.txt
resources/scripts/ttx_diff.py

difflib is not very efficient, and this has a significant impact on runtime; for `NotoSansMono` I go from 18m of wall time to 13m16s.

[ttx_diff] replace difflib with cdifflib

---

glyphs-reader/src/propagate_anchors.rs
resources/testdata/glyphs3/PropagateAnchorsTest-propagated.glyphs

this is unnecessary, the order we generate is not random, we use IndexMap and we append in the order in which components appear in the composite glyph, therefore it's better to keep the resulting ordering of propagated anchors (and adjust the test file accordingly) instead of artificially sorting the anchors by name in the test code only, just to make the test pass. In Python glyphsLib we use (ordered) dicts that remember insertion order so we will generate identical propagated anchors as well. The order of anchors is not semantically meaningful anyway, so this is a minor cosmetic change only.

[propagate_anchors] do not sort anchors by name in test

---

fea-rs/src/bin/compile.rs
fea-rs/src/compile/error.rs

fea-rs collects extensive diagnostic information during parsing and compilation, and is able to report errors associated to specific locations in the input FEA. This wasn't very fine-grained, though, and was causing problems with crater (because sometimes the stderr text for a given error would be extremely long, and include a bunch of ANSI escape codes) and so I turned off this finer-grained reporting.
It would be nice to have it available as an option, though, especially now that I'm trying to add support for new syntax, and would like to see what the actual errors are.
This adds a new method to the CompilerError that will print the error in the old verbose style, and makes it so that when you call the fea-rs binary directly (which is really not useful for debugging) it uses this method …

[fea-rs] Add CompilerError::display_verbose

---

glyphs-reader/src/propagate_anchors.rs

`origin_anchor` test case fails at the moment, still investigating why

propagate_anchors: fix mis-named test case, add specific one for *origin anchors

---

glyphs-reader/src/font.rs
glyphs-reader/src/plist.rs
resources/testdata/glyphs3/number_value.glyphs

This adds support for parsing the [number values](https://glyphsapp.com/learn/tokens#g-number-values) that can exist in a glyphs master.
This is required in order for us to properly compile FEA containing these values.
- progress on #92

Parse glyphs number values

---

resources/scripts/ttx_diff.py

For very large fonts one of the biggest time sinks is actually normalization. We need to normalize both outputs; previously we were doing this sequentially, which is totally unnecessary; with this patch we ensure that we normalize both fonts at the same time (using python threading, which is adequate since all the actual work is happening in a child process.)
For a simple test input this reduced runtime from 12m28s to 8m56s.

[ttx_diff] Run otl-normalizer in parallel

---

fea-rs/src/parse/grammar/glyph.rs
fea-rs/test-data/parse-tests/good/null_as_glyphname.PARSE_TREE
fea-rs/test-data/parse-tests/good/null_as_glyphname.fea

The spec is explicit that if a keyword is used as a glyphname than it needs to be escaped with '\', but feaLib does not enforce this and a bunch of noto fonts use 'NULL' (unescaped) as a glyph name.
Making this work is pretty trivial, and this gets us compiling a bunch of (12) additional sources, so I'm happy to compromise principles for expediency.

[fea-rs] Allow unescaped 'NULL' keyword as glyph name

---

resources/scripts/ttx_diff.py

While resolving off-by-ones we were doing a relatively expensive linear search for a matching item; this puts all the items into a dictionary ahead of time and queries that instead, which offers a huge speedup on large fonts (from a small number of hours to a small number of minutes)

[ttx_diff] Be less quadratic

---

fontc/src/args.rs
fontc/src/main.rs

Previously we were always printing the full error info for FEA errors but that's very verbose and was annoying for the crater stuff, so I had turned it off for a bit. This gives control back to the user, who can pass `-v` at the command line to see the old-style error report.
- fixes #900

[fontc] Add verbose flag, print FEA errors if set

---

Cargo.toml
fea-rs/src/compile.rs
fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/feature_writer.rs
fea-rs/src/compile/metrics.rs
fea-rs/src/compile/tables/gdef.rs
fontbe/src/features/marks.rs
fontbe/src/orchestration.rs
fontir/src/ir.rs

~*This is currently patching fontations to bring in https://github.com/googlefonts/fontations/pull/1090, I'll do a release when that gets merged*~
This patch generates a `LigCaretList` entry for any glyphs which include an anchor name beginning with `caret_` or `vcaret_`.
- currently this happens during mark generation, which is convenient since we have access to all the anchors there.
- this matches the `LigCaretList` produced by `fontmake` for oswald.
- closes #809

Generate LigCaretList table

---

resources/scripts/ttx_diff.py

The order of items in this list doesn't matter, so we can put it in ascending order, matching fontc.
This doesn't move the needle too much, but I was finding the difference confusing.

[ttx_diff] Make fontmake lookuplist order match fontc

---

fontc_crater/resources/style.css
fontc_crater/src/ci/html.rs
fontc_crater/src/main.rs
fontc_crater/src/ttx_diff_runner.rs

This now renders a very basic summary of changes and results for the last run after the overall summary table.
In the future I would like to make it so this is hidden by default and can be displayed as desired for the last N runs, but this first pass is a useful start.
In addition I would like to add another level of detail for individual runs (showing the command that failed and the backtrace) but that can be followup.
you can preview the new look at https://googlefonts.github.io/fontc_crater/

[crater] Add basic 'detail view' for previous run

---

fontbe/src/features.rs
glyphs2fontir/src/source.rs

This checks whether or not the FEA contained explicit glyph categories, and if it did not it replaces the categories computed by fea-rs (which include only glyphs that were used in mark positioning rules) by the categories either provided in public.openTypeCatgories (in UFO, if set) or assigned to individual glyphs in glyphsapp.
- closes #805 
- closes #850
- progress on #810

Set GDEF Glyph Categories if not explicit in FEA

---

fea-rs/src/compile/lookups/gpos_builders.rs
fea-rs/test-data/compile-tests/mini-latin/good/pairpos_format_choice.fea
fea-rs/test-data/compile-tests/mini-latin/good/pairpos_format_choice.ttx

In particular this means that we will not try to be smart about grouping rules into subtables based on their actual value formats; we will instead minimize the number of subtables by choosing the union of the value formats for each rule.

[fea-rs] Match fontmake for class-based pairpos

---

fontc_crater/resources/style.css
fontc_crater/src/ci/html.rs
fontc_crater/src/ttx_diff_runner.rs

This will show what tables are producing a diff, or the text of an error for an error.
you can see how this looks at https://googlefonts.github.io/fontc_crater/ (it's not pretty! but it at least presents the relevant info)

[crater] Add detail view for particular fonts

---

resources/scripts/ttx_diff.py

lxml throws the following warning message when running ttx_diff script at line 354
```
FutureWarning: The behavior of this method will change in future versions.
Use specific 'len(elem)' or 'elem is not None' test instead.
```
So let's be explicit

ttx_diff.py: fix lmxl FutureWarning when doing `if not element:`

---

fea-rs/src/compile/tables/gdef.rs
fontbe/src/features/marks.rs

When generating variable FEA the various Feature Writers use otround, since variable FEA syntax does not support floats.
This is not an issue with kerning, since glyphsapp does not allow for non-integer kerning values, but it is an issue for LigatureCarets and potentially for other variable mark positions (this needs more investigation)
- closes #810

[fontbe] Match fonttools behaviour for LigCaret rounding

---

fontc_crater/src/ci/html.rs

Since it can only happen as a result of rounding; so do an explicit check and skip rounding if we're rounding to 100.

[crater] Never show '100%' diff

---

fontc_crater/src/ci/html.rs

We were iterating a hashset, which meant the html could change slightly between different runs on the same inputs.
JMM

[crater] Ensure html generation is deterministic

---

fontc_crater/src/ci/html.rs

This makes it easy to see what changes have been made in fontc between two runs, which should help us figure out what is causing a given change.
For example, given the run that is current as of the time of this PR, we create the link [`1c75077e`](https://github.com/googlefonts/fontc/compare/b8d421ca...1c75077e/).

[crater] Make git sha a link to github diff

---

fontbe/src/features.rs
fontc/src/lib.rs
resources/testdata/glyphs3/gdef_categories_no_layout.glyphs

Previously we would only add a GlyphClassDef table to an existing GDEF table, but would not create a GDEF table if one had not been produced by feature compilation.
This patch matches the behaviour of fontmake.
This does raise the question of whether or not either compiler should bother generating a GlyphClassDef subtable in the absense of GPOS/GSUB, but that's something we can address separately.

[fontbe] Create GDEF for GlyphClassDef if needed

---

fontc_crater/src/ci/html.rs
fontc_crater/src/ttx_diff_runner.rs

That is, in the detail view where it shows the per-table diff percentages for a given font, if there have been any changes from the previous run display the delta at the per-table level, so we can better understand what changed.
You can see how this looks at https://googlefonts.github.io/fontc_crater/

[crater] Show per-table deltas in diff detail view

---

fontir/src/ir.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/TheBestNames.glyphs
resources/testdata/glyphs3/VersionMajorMinor.glyphs
ufo2fontir/src/source.rs

Fixes #906 
We should now match fontmake (ufo2ft) logic for determining the two sets of family and subfamily names depending on which one is present or not.

Fix the NameBuilder family/subfamily fallback logic 

---

fontc_crater/src/ttx_diff_runner.rs

This isn't present by default on systems that don't have GNU Coreutils installed, and without this check we will just happily fail for every target.
(last night's crater run failed because I hadn't included `opt/homebrew/bin` in the PATH of the ci machine, and it hit this issue)

[crater] Assert presence of timeout(1) before run

---

fontir/src/glyph.rs

must decompose transformed components before flattening deep nested components

---

fontbe/src/features/marks.rs
fontc/src/lib.rs
resources/testdata/glyphs3/Oswald-AE-comb.glyphs

Otherwise the lookups will not be applied as the base marks will be skipped.
- Fixes https://github.com/googlefonts/fontc/issues/958

Add base marks to mark filtering sets of mark-to-mark attachment lookups

---

resources/scripts/ttx_diff.py

Like it is done for named instance name IDs.

[ttx_diff] Normalize axis labels in fvar and STAT tables

---

fea-rs/src/parse/grammar/metrics.rs
fea-rs/src/token_tree/typed.rs

I'd failed to update one function in light of adding a new possible type of metric (for glyphs number value syntax)
- fixes #948

[fea-rs] Fix bug in valuerecord access logic

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/test-data/compile-tests/mini-latin/good/script_stmt_scope.fea
fea-rs/test-data/compile-tests/mini-latin/good/script_stmt_scope.ttx

We were not clearing our internal state of the active script when finishing a feature block, which caused us to not handle an identical 'script' statement occurring at the start of the subsequent feature block.

[fea-rs] Fix issue with scope of 'script' statements

---

fontir/src/ir.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/GlobalMetrics_font_customParameters.glyphs

If the corresponding custom parameter is missing from the master, try it from the parent font.
- Fixes https://github.com/googlefonts/fontc/issues/949

[glyphs2fontir] Fallback to setting GlobalMetrics from font

---

resources/scripts/ttx_diff.py

This is less precise than the 'ratio' method we're currently using, but we don't _really_ care about precision here, and quick_ratio is much much much faster.
computing all the ratios for `NotoSans` currently takes several hours; with this patch it takes several minutes.
This should hugely speedup our CI runs; on my laptop we now finish in ~20 minutes.

[ttx_diff] Go back to using 'quick_ratio'

---

fontc/src/lib.rs
ufo2fontir/src/source.rs

Fixes #976. 
`$ resources/scripts/ttx_diff.py --compare default ../font_repos/cherokee/sources/NotoSansCherokee.designspace` now reports identical OS/2 instead of differing on fsType.
The file used for the `default_fs_type_designspace` test amusingly actually specified an fsType so I changed to one that doesn't.
JMM.

Obey UFO fs type specifications

---

fontc_crater/Cargo.toml
fontc_crater/src/ci/html.rs
fontc_crater/src/error.rs

Previously we would just write a big contatenated string of html, which was unreadable and also impossible to diff.
With this patch we clean up the html (newlines & indentation) using tidy.
This is particularly important because it means git can efficiently compute deltas on the index, instead of each new commit involving adding a new ~1MB blob to the repo.
JMM

[crater] Tidy ci report html

---

fea-rs/src/compile/error.rs
fontc/src/args.rs
fontc/src/main.rs

It's quite confusing that you can set `RUST_LOG` to adjust how much you see except for one specific thing that relies on a flag.
Delete the flag, use the same logging as everything else, and tell the user how to see the error if we aren't showing them.
JMM

Use our logging framework for logging

---

otl-normalizer/src/variations.rs

The order of variation regions within the region list is left up to the compiler, and in some instances fontc and fontmake were choosing different orderings. This ensures that regardless of the ordering in the region list, deltas are presented in a consistent ordering in the output.

[normalizer] Standardize location ordering

---

resources/scripts/ttx_diff.py

Works around #975 (until we also have gain the ability to remove overlaps)

ttx_diff: pass --keep-overlaps for static fontmake builds for now

---

fea-rs/src/compile/validate.rs
fea-rs/test-data/compile-tests/mini-latin/bad/aalt_reference_missing_feature.ERR
fea-rs/test-data/compile-tests/mini-latin/bad/aalt_reference_missing_feature.fea

Instead of an error; this matches what fonttools does.

[fea-rs] Make non-existent feature in aalt a warning

---

resources/scripts/ttx_diff.py

Because the most relevant information (in the case of an error) is going to be what gets printed at the end of the stream, not the start of it.
JMM

[ttx_diff] If truncating stderr, truncate head

---

fontbe/src/features.rs

Currently these are using 'debug', which doesn't seem right.
JMM

Use log::warn for fea-rs warnings in fontc

---

fea-rs/src/parse/grammar/gpos.rs
fea-rs/test-data/compile-tests/mini-latin/good/pair_pos_funny_syntax.fea
fea-rs/test-data/compile-tests/mini-latin/good/pair_pos_funny_syntax.ttx

This syntax is not documented, but it is treated as equivalent to 'pos a b 20' by both afdko and feaLib, and exists in at least one noto font.
Opened https://github.com/adobe-type-tools/afdko/issues/1757 to see if this is intended or just works by accident; in either case I think supporting it is expedient.

[fea-rs] Support 'pos a 20 b' pairpos syntax

---

fea-rs/src/compile/validate.rs
fea-rs/src/parse/grammar/feature.rs
fea-rs/src/token_tree/typed.rs
fea-rs/test-data/compile-tests/mini-latin/bad/cv_params.ERR
fea-rs/test-data/compile-tests/mini-latin/bad/cv_params.fea
fea-rs/test-data/compile-tests/mini-latin/bad/stylistic_set_names.ERR
fea-rs/test-data/compile-tests/mini-latin/bad/stylistic_set_names.fea

Our validation code was broken in a subtle way, where we were skipping the first statement in the block if it wasn't one of the special statements.
This fixes that, and also fixes a possible deadlock in the parsing of the cvParameters block.
This gets at least one more font compiling.

[fea-rs] Fix validation of ss01-ss20 & cv01-cv99

---

Cargo.toml
glyphs-reader/Cargo.toml
glyphs-reader/src/glyphdata/glyphdata_impl.rs

This includes a fix for a .glif parsing bug.
This _would_ get us compiling Noto Sans Mongolian but now I'm running into the thing I noticed for the first time yesterday, and which I was confident I would never see in the wild: #996

Update to norad 0.14.2

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/test-data/compile-tests/mini-latin/good/inline-null-multisub.fea
fea-rs/test-data/compile-tests/mini-latin/good/inline-null-multisub.ttx

This is a funny corner of the spec but it's suported by fonttools and exists in NotoSerifBengali, so let's get that compiling.

[fea-rs] Support inline null multi-sub with class

---

glyphs-reader/Cargo.toml
glyphs-reader/src/font.rs

Fixes https://github.com/googlefonts/fontc/issues/264
After this [HankenGrotesk-Italic.glyphs](https://github.com/marcologous/hanken-grotesk/blob/master/sources/HankenGrotesk-Italic.glyphs) is happier

implement glyphsLib's logic to find base style shared by all masters

---

fea-rs/src/token_tree/typed.rs
fea-rs/test-data/compile-tests/mini-latin/good/base_table.fea
fea-rs/test-data/compile-tests/mini-latin/good/base_table.ttx

This was causing a panic in a font (wavefront) but unfortunately it was one of two panics, so it doesn't move the needle.

[fea-rs] Fix typo bug in BaseScriptList

---

fontc/src/lib.rs
glyphs-reader/src/font.rs
resources/testdata/glyphs2/WdthVar.glyphs

we were only testing parsing instance widthClass for glyphs3 sources, where this property already holds a number 1..9
for glyphs2 this is an enumerated string that maps to numbers from 1 to 9.
`lookup_class_value` is incorrectly mapping the widthClass to numbers from 50 to 200 (i.e. using the corresponding percentages instead of the enumerated integer values)
https://github.com/googlefonts/fontc/blob/4a4019c66902e9ce68c7b98403a734b94a88eaf2/glyphs-reader/src/font.rs#L1971-L1980
... but then the WidthClass::try_from fails because only numbers 1 to 9 are supported:
https://github.com/googlefonts/fontc/blob/4a4019c66902e9ce68c7b98403a734b94a88eaf2/fontdrasil/src/types.rs#L110-L134
I first push a failing test case (simply duplicating an existing test for glyphs3/WdthVar.glyphs, coverted to …

fix parsing widthClass from glyphs2 instances

---

glyphs2fontir/src/source.rs
resources/testdata/glyphs3/WghtVar1290upem.glyphs

`fontc` and `fontmake` disagree about `yStrikeoutSize` for [soft-type-jacquard/sources/Jacquard24Charted.glyphs](https://github.com/scfried/soft-type-jacquard).
In outlineCompiler.py in ufo2ft `yStrikeoutSize` is set to `openTypeOS2StrikeoutSize` if present, otherwise `postscriptUnderlineThickness`. Turns out 
https://github.com/googlefonts/glyphsLib/blob/9d5828d874110c42dfc5f542db8eb84f88641eb5/Lib/glyphsLib/builder/custom_params.py#L1136-L1156 captures parameters that differ from the ufo2ft defaults, notably underline thickness and position.
After this fix `OS/2` and `post` match for Jacquard 24 Charted. Presumably impacts others too.

Fix bug where fontc didn't have Glyphs-specific underline defaults

---

fontc/src/lib.rs
fontir/src/ir.rs
resources/testdata/glyphs3/StaticWithInstance.glyphs

Fixes #1008. Makes `name` identical for [soft-type-jacquard/sources/Jacquard24Charted.glyphs](https://github.com/scfried/soft-type-jacquard)

Avoid assigning names for unreachable instances

---

glyphs-reader/src/font.rs
resources/testdata/glyphs3/TheBestNames.glyphs

Fixes #1011.
Combined with #1009 at least two families (listed in #1011) will have a matching `name` table

Expose and fix name processing discrepency

---

glyphs-reader/src/font.rs
resources/testdata/glyphs2/MasterNames-Italic.glyphs
resources/testdata/glyphs2/MasterNames.glyphs
resources/testdata/glyphs3/MasterNames-Italic.glyphs
resources/testdata/glyphs3/MasterNames.glyphs

Fixes #264 for glyphs2 as well.
the test currently fails because we aren't generating glyphs2 master names properly (they are all set to 'Regular' which doesn't help)

generate master names when upgrading glyphs2 to 3 

---

glyphs2fontir/src/source.rs
resources/testdata/glyphs3/MVAR.glyphs

OS/2 for Ga Maamli, Alumni Sans Pinstripe, and likely more should match after. Alumni Sans Pinstripe now reports identical in default mode locally.

Take abs of win descent when reading .glyphs files

---

glyphs-reader/src/font.rs
glyphs2fontir/src/toir.rs
resources/testdata/glyphs3/Fea_Labels.glyphs

Convert them to featureNames.
Fixes https://github.com/googlefonts/fontc/issues/950

[glyphs2fontir] Support stylistic set labels

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/tables/name.rs
fea-rs/src/compile/validate.rs
fea-rs/src/token_tree/typed.rs
fea-rs/test-data/compile-tests/mini-latin/bad/cv_params.ERR
fea-rs/test-data/compile-tests/mini-latin/bad/stylistic_set_names.ERR
fea-rs/test-data/compile-tests/mini-latin/good/duplicate_feature_names.fea
fea-rs/test-data/compile-tests/mini-latin/good/duplicate_feature_names.ttx

Previously we would error if there were more than one of these blocks, but the spec merely says that they must occur before any rules.
This now supports multiple featureNames blocks, and matches the behaviour of fonttools (last writer wins).
For CvParameters, we will only look at the first such block, and skip the rest; no source in our collection has multiple such blocks defined within a given feature, and updating the logic is more complicated so I would like to defer it for now.
- fixes #1019

[fea-rs] Better handling of featureNames & cvParam

---

fontbe/src/os2.rs
fontir/src/ir.rs
resources/testdata/WghtVar-Bold.ufo/fontinfo.plist
resources/testdata/WghtVar-Regular.ufo/fontinfo.plist
ufo2fontir/src/source.rs

Fixes #1026, [cuneiform/sources/NotoSansCuneiform.designspace](https://github.com/notofonts/cuneiform) is identical locally after.
Ty @cmyr for [pointing out](https://github.com/googlefonts/fontc/issues/1026#issuecomment-2409468203) that I misread the `.designspace` initially.
JMM if happy.

Obey `fontinfo.plist` `openTypeOS2Panose` value for the default ufo

---

fontc_crater/src/ci/html.rs

- if a result is identical and was also identical in the previous run, skip it in the main list.
- if a result improved and is now identical, show the per-table improvements in the detail view.
JMM

[crater] Tweak reporting of identical matches

---

glyphs-reader/src/font.rs
resources/testdata/glyphs3/TheBestV2NamesInAV3File.glyphs

Fixes #1029. [sedan/sources/Sedan-Regular.glyphs](https://github.com/googlefonts/sedan), marked v3 but with a v2-style name in it, is now identical locally.

Support v2 style names in v3 files

---

fontbe/src/fvar.rs
fontbe/src/stat.rs
fontc/src/lib.rs
fontdrasil/src/types.rs
fontir/src/ir.rs
resources/testdata/glyphs3/StandardAxisNames.glyphs

Part of fixing https://github.com/googlefonts/fontc/issues/1020
This makes so that we follow fonttools' axis naming of a special group of registered axes, conventions still used by some old source files.
The remaining part of #1020 requires norad to support parsing of `<labelname>` element.

Name 'standard' axes to match fonttools

---

resources/scripts/ttx_diff.py

We have spurious normalizer failures sometimes, and this will now check for those cases and retry (up to five times) if they occur.
JMM

[ttx_diff] Retry normalizer on failure

---

fontc_crater/src/args.rs
fontc_crater/src/main.rs
fontc_crater/src/sources.rs

This has nothing to do with CI, and is only used by the old-style runners.
Ultimately we should just unify these different interfaces; by default we could keep a list of inputs in the cache dir as a json file, and with no provided args we would create or run that.

[crater] Remove 'fonts_repo' cli arg

---

fontc_crater/README.md
fontc_crater/src/args.rs
fontc_crater/src/ci.rs
fontc_crater/src/ci/html.rs
fontc_crater/src/main.rs
resources/scripts/ttx_diff.py

* Set defaults on crater arguments and simplify example commands
* Use the same default for local font repos in ttx_diff
* Default ttx_diff to compare default because gftools doesn't actually do what it says at time of writing
* Add the ability to run ttx_diff against a specific source in a repository
* `python resources/scripts/ttx_diff.py https://github.com/cyrealtype/Alice#sources/Alice.glyphs` will check for a local copy of the repo, clone it if there isn't one, and then build/compare the glyphs file specified in the fragment
* Document how to run ci locally to get an html report; very useful when trying to alter the html!
* Add a copy repro button to the results
Copy repro gets you something like `python resources/scripts/ttx_diff.py …

Tweaks to make reproducing builds from crater easier

---

resources/scripts/ttx_diff.py

The flow here may change in future but for now it's handy if both tools agree
JMM

Make ttx_diff use the same repo dir as crater

---

fontc_crater/README.md
fontc_crater/src/ci/html.rs

Right now if you click copy repro on https://googlefonts.github.io/fontc_crater/ it navigates, effectively scrolling to top of page.
JMM

Prevent navigation on copy repro click

---

resources/scripts/ttx_diff.py

right now the `gpos.xpath("//Lookup")` ends up selecting and removing GSUB lookups of type 2, 4, 5 and 6 as well, even though we only intended to prune the GPOS ones.
That's the way `//` works, it will select all matching elements following the current node anywhere they appear, not only their descendants. GSUB follows GPOS since ttx sorts table alphabetically.
Putting a dot in front `.//` ensures only the descendants of the current node are selected.
see https://www.w3schools.com/xml/xpath_syntax.asp

[ttx_diff] ensure only the GPOS lookups get xpath'ed for pruning

---

resources/scripts/ttx_diff.py

[ttx_diff] Remove unused argument

---

resources/scripts/ttx_diff.py

At the beginning of the run, we now check the 'rebuild' flag, and explicitly delete anything we are required to rebuild. This lets us simplify later logic by knowing we're allowed to reuse anything that exists.
This is part of a larger refactor to support the CI use case; because CI builds each individual font in a transient temporary directory, these artifacts do not persist between runs. To reuse artifacts CI is going to need to start storing these artifacts somewhere other than in the build directory.

[ttx_diff] Simplify reuse logic

---

resources/scripts/ttx_diff.py

Invoking this through cargo has some overhead, and involves possible conjestion (I believe only one cargo process at a time will run in a given package or workspace) and I would also like to rule out one more possible complication that could contribute to getting SIGKILL'd.
longer term, in order to manage the growing complexity of ttx_diff and to support the very different cases of 'CI on many fonts running on a transient host' and 'me at my desk comparing one source' I'd like to tease apart the building vs diffing bits of ttx_diff, and one part of that will mean the diffing bits shouldn't need to know where the `fontc` repo is located; we'll just pass in the path to the binary itself.

[ttx_diff] Build otl-normalizer binary explicitly

---

resources/scripts/ttx_diff.py

- Improve some type annotations
- rename 'run' to 'log_and_run'
- use kwargs to forward more args to subprocss.run
- use subprocess.run timeout arg instead of gnu timeout
JMM

[ttx_diff] More cleanup

---

resources/scripts/requirements.txt

https://github.com/googlefonts/fontmake/releases/tag/v3.10.0
no code changes to fontmake itself, this is simply bumping the minimum required dependencies (e.g. fonttools, ufo2ft, glyphsLib) which in turn fixes a bunch of bugs
JMM

requirements.txt: bump fontmake==3.10.0

---

fontbe/src/glyphs.rs
fontc/src/lib.rs
resources/testdata/glyphs2/MatrixComponent.glyphs

Simplified reproduction of problem impacting Luxurious Roman (`python resources/scripts/ttx_diff.py https://github.com/googlefonts/luxurious-roman#sources/Luxurious-Roman.glyphs`)
```shell
$ python resources/scripts/ttx_diff.py resources/testdata/glyphs2/MatrixComponent.glyphs
...glyf, head, hhea, hmtx diff...
$ diff ~/oss/fontc/build/default/fontc.glyf.ttx ~/oss/fontc/build/default/fontmake.glyf.ttx
38c38
<     <TTGlyph name="infinity" xMin="750" yMin="272" xMax="877" yMax="443">
---
>     <TTGlyph name="infinity" xMin="767" yMin="284" xMax="863" yMax="431">
```
This appears to be due to fontc assuming it can simply apply the component transform to the control box when in fact it needs to transform the points and compute the control box of the new points. …

Expose and fix broken processing of bbox for components whose transform is more than scale and transform

---

fontc_crater/Cargo.toml
fontc_crater/README.md
fontc_crater/src/args.rs
fontc_crater/src/ci.rs
fontc_crater/src/ci/html.rs
fontc_crater/src/error.rs
fontc_crater/src/main.rs
fontc_crater/src/sources.rs
fontc_crater/src/ttx_diff_runner.rs

_this is blocked until I do a release of google-fonts-sources_
This will facilitate gftools mode.
Ultimately I decided to just rip out a bunch of the old functionality, because keeping it working was becoming a chore and it really wasn't being used much.

[crater] Initial support for richer targets

---

fontc_crater/src/ci.rs
fontc_crater/src/ttx_diff_runner.rs

There are lots of commits to this repo that would trigger a CI run but which won't produce any difference to the behaviour of fontc; this patch lets us avoid spamming the crater report with identical entries.

[crater] Skip writing if results unchanged

---

fontc_crater/resources/style.css
fontc_crater/src/ci/html.rs

- add a list of tables that differ inline
- move the reproduction link into the details view (we were running out of space)

crater html display tweaks

---

fontc_crater/Cargo.toml
fontc_crater/src/ci.rs
fontc_crater/src/main.rs
fontc_crater/src/ttx_diff_runner.rs
resources/scripts/requirements.txt
resources/scripts/ttx_diff.py

This wires everything up to get gftools working in crater.
- currently blocked on ~https://github.com/googlefonts/google-fonts-sources/pull/24 and~ https://github.com/googlefonts/gftools/pull/1047
- but maybe we don't actually need to merge the gftools patch? If we can pip install from a git rev or branch, we could just maintain our own branch of gftools and not need to dirty up the main tree.
- we skip noto fonts and other fonts that have a custom recipe provider
- there are a number of failures because it turns out that in lots of cases one source does produce multiple fonts; a bunch of these I could address by turning off config options (so to not build small caps or italics) but a handful of fonts are building a regular and a bold, and I didn't see a config option for this.

gftools mode for crater

---

fontir/src/variations.rs

the first commit is a repro for https://github.com/googlefonts/fontc/issues/1043#issuecomment-2426907952
the lack of rounding within the delta computation can lead to deltas that are off-by-one by the time they are eventually ot-rounded to i16, as it is shown in Gelasio's MVAR table (from which the reproducer is drawn).
The commits that follow will apply the fix for #1043 as well as for #235, and add more tests borrowed from fonttools models_test.py
Basically we need to apply the rounding within the very same loop in which deltas get subtracted away from the absolute master values. This is to make sure that the rounding errors are accounted for and don't accummulate beyond 0.5 when multiple regions overlap.
The use of the banker's "round half to even" method (`round_ties_even` in Rust) …

Fix rounding of VariationModel::deltas

---

resources/scripts/ttx_diff.py

In ttx_diff.py we already erased the head.modified, but we don't also erease the head.created. The latter is also set to the current time when the source does not contain an explicit openTypeHeadCreated (most do not). I have seen random ttx-diffs caused by the fact that sometimes fontc and fontmake builds differs by one or two seconds in the head.created.
For example this one in a recent run of fontc_crater:
Since both compilers support the standard [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) variable for reproducible builds we may well make use of it here.

[ttx_diff] set SOURCE_DATE_EPOCH to ensure head.modified and created are the same

---

fontc_crater/src/ci.rs
fontc_crater/src/main.rs

This is a coarse way of determining whether or not any python packages have been modified, which we can use for invalidating a potential cache.
Also adds a env var to force CI to rerun, which is something I often want during development.

[crater] Compute and store 'hash' of python packages

---

fontc_crater/resources/style.css
fontc_crater/src/ci.rs
fontc_crater/src/ci/html.rs

This is useful information, and will be even more useful if we want to know if caching is useful.
This is also potentially useful diagnostic info; if runtimes spike after some particular change, we probably broke something.
looks like:

[crater] Show runtime in html

---

fontc_crater/src/main.rs
fontc_crater/src/target.rs

I want to enforce some invariants on these types, which requires making some of their fields non-visible, which requires them to be in a module.
Doing this in a separate PR for the benefit of clearer diffs for subsequent PRs.

[crater] Move target stuff into ::target module

---

fontc_crater/src/ttx_diff_runner.rs

This would happen in certain cases where some error caused every target to fail. This hasn't happened in production but it has happened various times in my local testing, and it's annoying.
JMM

[crater] Don't serialize nans

---

fontc_crater/src/ci.rs
fontc_crater/src/ci/html.rs
fontc_crater/src/main.rs
fontc_crater/src/target.rs
fontc_crater/src/ttx_diff_runner.rs

Okay this... was annoying, but how we were handling targets had some dumb issues:
- we weren't including the config file in serialization, which means that we didn't have enough info to generate the repro command for gftools
- (and also it was possible to end up with distinct targets serializing identically, in the case where a repo contained multiple configs which pointed to overlapping sources; not sure if this existed but was possible)
- but I also want to be efficient in what we serialize, and the config and source paths generally share a stem
- because we serialize to json and use targets as the keys, we need to ensure they serialize as strings
- so the logic got complicated fairly quickly.
I have the repro command fix working on top of this, and will PR that separately.

Crater rework targets

---

fontc_crater/src/ci/html.rs
fontc_crater/src/target.rs
resources/scripts/ttx_diff.py

This is best effort. In particular,
- it doesn't ensure that the git rev of the repo is the same
- it assumes a single possible location for the checkouts
- it doesn't ensure that the python toolchain is equivalent
but it does support gftools mode, and it does work?
based on #1083, which should go in first.

[crater] Fix repro command

---

fontc_crater/src/ci.rs
fontc_crater/src/ci/results_cache.rs
fontc_crater/src/target.rs
fontc_crater/src/ttx_diff_runner.rs
resources/scripts/ttx_diff.py

This clears the cache if the pip freeze output is different.
It's possible that this isn't worth the complexity, but it should offer meaningful runtime speed improvements, so let's give it a try?

[crater] Cache output of fontmake between runs

---

Cargo.toml
fontbe/src/features.rs
fontbe/src/features/marks.rs
fontbe/src/hvar.rs
fontbe/src/mvar.rs

make sure masters for global/glyph/layout metrics are rounded before computing deltas

---

fontc_crater/src/ci.rs
fontc_crater/src/ci/html.rs

We were using the fontc rev as the key to a map of runs -> detailed results, which doesn't work because it's possible for multiple runs to share the same git rev (e.g. if the inputs or the installed python packages have changed)
JMM

[crater] Use timestamp to key crater results

---

resources/scripts/requirements.in
resources/scripts/requirements.txt

Brings in the newest glyphsLib, as well as updates our gftools to include a commit that stops us from running ttxautohint.
JMM

Update python dependencies

---

glyphs-reader/data/update.py
glyphs-reader/src/glyphdata.rs
glyphs-reader/src/lib.rs

Per conversation with @cmyr on #1066, try to compact data generated from glyphsLib xml files. Don't rust format, don't space nicely, just ram it all together in a compact form.

Compact generated data

---

fontc_crater/resources/style.css
fontc_crater/src/ci/html.rs

This is shown as a single line in the results section, not in the main table.
looks like this:

[crater] Report number of identical families

---

fontc_crater/src/ci/results_cache.rs

I had these on higher levels than needed during development, but they should really just all be at TRACE.
JMM

[crater] Cleanup logging of cache hits/misses

---

fontbe/src/os2/max_context.rs

Key fix is a missing +1:
```rust
fn sequence_len(&self) -> usize {
self.input_sequence.len() + 1
}
```
Makes OS/2 match for 
```shell
$ python resources/scripts/ttx_diff.py https://github.com/SorkinType/Alata#sources/Alata.glyphs
```

Add a missing +1

---

fontbe/src/metrics_and_limits.rs

Most fields in `hhea` are set based [only on glyphs with bounds](https://github.com/fonttools/fonttools/blob/e04dfaab/Lib/fontTools/ttLib/tables/_h_h_e_a.py#L101-L119), but `advanceWidthMax` is an exception to this, as it considers [every glyph that has an entry in `hmtx`](https://github.com/fonttools/fonttools/blob/e04dfaab/Lib/fontTools/ttLib/tables/_h_h_e_a.py#L73).
This commit includes empty glyphs in the calculation of the field, which matches fontmake's behaviour. After this change, Fleur De Leah compiles identically:
```bash
$ python resources/scripts/ttx_diff.py https://github.com/googlefonts/fleurdeleah#sources/FleurDeLeah.glyphs
...
output is identical
```
<sub>Note: this is a personal contribution independent of my employer, and so I've submitted from a fork under my personal …

Include empty glyphs when calculating max width, to match fonttools

---

fontc_crater/src/ci/html.rs
fontc_crater/src/ttx_diff_runner.rs
resources/scripts/ttx_diff.py

This is a bit hacky, because comparing size doesn't really work like difference, but I've squeezed it into a shape where it seems to work okay?
It basically works like this:
- for each table produced by both compilers, we find the ratio of their sizes
- if the ratio exceeds a threshold (currently 1/10) then we add it to the the report
- in the actual report, we just display these size differences as a delta, in bytes. Negative numbers mean that fontc is smaller than fontmake, and positive numbers mean the inverse.

[crater] Report size differences

---

resources/scripts/requirements.in
resources/scripts/requirements.txt

we no longer need to install gftools from github, as our patches were released upstream.
also, glyphsLib [6.9.4 reverted a change in 6.9.3](https://github.com/googlefonts/glyphsLib/pull/1044) that caused lots of unnecessary diffs in GlyphOrder
JMM

use gftools==0.9.74, update glyphsLib==6.9.4

---

fontc_crater/src/target.rs
resources/scripts/ttx_diff.py

Hello! This is just a small one with QoL fixes for two crater-related crashes:
- [Quote URL in reproduction command, to help parse sources with spaces in their name](https://github.com/googlefonts/fontc/commit/b3faa37e41e3b6d63f61e2ea7d5c7b8dbacf2638)
- [Create cache directory (~/.fontc_crater_cache) if it does not exist yet](https://github.com/googlefonts/fontc/commit/0af851f8659abda5240e191f3240379a1add9706)
---
Both can be reproduced and tested by copying the reproduction command for 'Konkhmer Sleokchher.glyphs' from [the hosted fontc_crater results](https://googlefonts.github.io/fontc_crater/) and running it without a `~/.fontc_crater_cache` directory present :boom: 
<sub>Note: this is a personal contribution independent of my employer, and so I've submitted from a fork under my …

Two small fixes for two small crater crashes

---

fontc_crater/src/ci/html.rs

Unfortunately my fix for reproduction commands in #1103 – introducing bash quotes – interfered with the outer JavaScript quotes, breaking the 'copy reproduction command' entirely...
This PR remedies this by alternating the quotes style. For this and all future changes, I have now got a local fontc_crater setup, and have verified the fix. The documentation for doing so was excellent, and I wish I'd checked for it the first time; sorry for the trouble!
<sub>Note: this is a personal contribution independent of my employer, and so I've submitted from a fork under my personal profile and email to make this distinction</sub>

Fix crater quality-of-life fix

---

resources/scripts/ttx_diff.py

If we're smaller and the ttx is equivalent, that seems fine.

[ttx_diff] Only report size issues if fontc > fontmake

---

resources/scripts/ttx_diff.py

This reverts commit ffcfadfc3ce0ee35166baa3e2f8d6df2fee7f3a4.
I edited this PR after review and the change I made was not correct.

Revert "[ttx_diff] Only report size issues if fontc > fontmake"

---

resources/scripts/ttx_diff.py

This is not a very elegant way of expressing this but it works and leaves the existing logic in place, in case at some point we decide we _do_ care if fontc produces something significantly smaller.

[ttx_diff] Only report size differences if fontc bigger

---

fontbe/src/fvar.rs
fontbe/src/stat.rs
fontc/src/lib.rs
fontir/src/ir.rs
resources/testdata/glyphs3/DuplicateNames.glyphs

Fix for #1105 on the python side made it possible to reuse non-font-specific names, make fontc consistent.
Makes `python resources/scripts/ttx_diff.py 'https://github.com/googlefonts/Exo-2.0#sources/Glyphs/Exo2-Italic.glyphs'` and `python resources/scripts/ttx_diff.py 'https://github.com/googlefonts/atkinson-hyperlegible#sources/AtkinsonHyperlegible.glyphs'` and hopefully others identical instead of different on `(name, fvar)`. 
JMM if happy.

We no longer have to avoid reusing non-font-specific names

---

fontdrasil/src/piecewise_linear_map.rs

but keep the outward interface as f32 to limit the scope of changes (otherwise callers would have to deal with f64s and there are a lot)
This seems to fix https://github.com/googlefonts/fontc/issues/1117 in the sense that ttx_diff.py now reports [Grenze-Gotisch](https://github.com/Omnibus-Type/Grenze-Gotisch) as "output is identical".
Basically, the loss of precision happened while converting glyphs sources to ir: the instance locations are in design-space in the source; we store them as normalized location
https://github.com/googlefonts/fontc/blob/53151a1af8b2977d3aaca66dd6d7d13c43a80ec9/glyphs2fontir/src/toir.rs#L288
... but then in the ir::NamedInstance they are in user-space (like in fvar) so they must be converted again `to_user`: …

piecewise_linear_map: perform internal computations as f64 to increase precision

---

fontbe/src/features/kern.rs

If FEA contained a languagesystem statement with the DFLT script and any language other than 'dflt', we were not correctly adding the kern feature to these languages.
- fixes #1121

[kern] Fix handling of DFLT script languages

---

fontbe/src/avar.rs
fontbe/src/cmap.rs
fontbe/src/features.rs
fontbe/src/font.rs
fontbe/src/fvar.rs
fontbe/src/gvar.rs
fontbe/src/head.rs
fontbe/src/hvar.rs
fontbe/src/metrics_and_limits.rs
fontbe/src/mvar.rs
fontbe/src/name.rs
fontbe/src/orchestration.rs
fontbe/src/os2.rs
fontbe/src/post.rs
fontbe/src/stat.rs
fontc/src/lib.rs
fontir/src/orchestration.rs

How this happened:
- I was looking into an issue with name records generated from FEA
- I got confused about why we were calling a method called `set_unconditionally`, instead of just `set`
- The docs for that method had a TODO saying it was (mostly?) only necessary because `write-fonts` types don't impl `PartialEq`
- ... except that they have, for over a year
- so I went and tried to impl that trait, except we don't impl it for them directly, we impl it for a wrapper type, `BeValue`
- ...and the docs for _that_ type said it was only necessary to get around the orphan rules
- ... which wouldn't be a problem if we just impl'd the `Persistable` trait for the write-fonts types in the same crate where the trait is defined (`fontir`)
- So I did _that_, and then ran into an issue where for …

Remove `set_unconditionally` & `BeValue`

---

fontc/src/lib.rs
fontir/src/glyph.rs

I think when I originally wrote this I assumed it to be nonsensical to repeat a component but for a VF it's OK if some locations do this.
Per #1115 this occurs in real fonts.

Allow identical (same glyph, same transform) components

---

Cargo.toml
fea-rs/src/compile/tables/name.rs
fontbe/src/name.rs

This includes a few tweaks to make sure we are sorting the name table.

[chore] Bump fontations crates

---

fea-rs/src/compile/output.rs
fea-rs/src/compile/tables/name.rs
fontbe/src/features.rs
fontbe/src/name.rs
fontbe/src/orchestration.rs
fontbe/src/paths.rs
fontc/src/lib.rs
fontc/src/timing.rs
resources/scripts/ttx_diff.py
resources/testdata/CustomNameTableInFea.ufo/features.fea
resources/testdata/CustomNameTableInFea.ufo/fontinfo.plist
resources/testdata/CustomNameTableInFea.ufo/glyphs.{600}/bar.glif
resources/testdata/CustomNameTableInFea.ufo/glyphs.{600}/contents.plist
resources/testdata/CustomNameTableInFea.ufo/glyphs/bar.glif
resources/testdata/CustomNameTableInFea.ufo/glyphs/contents.plist
resources/testdata/CustomNameTableInFea.ufo/glyphs/plus.glif
resources/testdata/CustomNameTableInFea.ufo/groups.plist
resources/testdata/CustomNameTableInFea.ufo/kerning.plist
resources/testdata/CustomNameTableInFea.ufo/layercontents.plist
resources/testdata/CustomNameTableInFea.ufo/lib.plist
resources/testdata/CustomNameTableInFea.ufo/metainfo.plist
resources/testdata/glyphs3/WghtVarWithStylisticSet.glyphs

Previously we were just dropping them on the floor.
This is one of a number of cases where it is possible for FEA to generate a table that is also generated (or could be generated) through the main compilation process.
This introduces an overall strategy for handling this: when FEA generates these extra tables we now stash them in the main context, where we can reference them when building the final font.
This patch also uses this mechanism to merge name records generated from FEA into the main name table; this looks to get us at least a +7 on crater.
As a bonus this includes a commit that fixes a little bug in ttx_diff where we were accidentally sorting name ids as if they were lookup ids, and which very briefly had me doubting my sanity.
- fixes #1130

Merge names from FEA into final table

---

glyphs-reader/src/font.rs
glyphs-reader/src/propagate_anchors.rs

The loading logic mostly involves the RawFont type, and if we ever move that to its own module it will make sense to keep this together.
(no functional change)

[glyphs] Move loading logic into RawFont

---

glyphs-reader/src/font.rs
glyphs-reader/src/lib.rs
glyphs2fontir/src/source.rs

We're going to need to support a bunch of of these, and it was becoming hard to keep track of what was being handled and what wasn't. This moves all the custom params (at the font level) into a new CustomFontParameters struct.
It also reduces boilerplate when these are used in glyphs2fontir.
The ultimate goal here is to do smarter parsing of these custom paramaters in such a way as to be able to warn if there are any we aren't handling.

[glyphs] Clean up custom params

---

glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/KernFloats.glyphs

Glyphs kern values can be floats, but we were parsing them as integers.
This also uncovered something else fishy: our integer parsing logic in glyps-reader/ascii-plist-derive will happy parse something like "1.321" as an integer, by parsing to a float and casting.
I think this is incorrect? I think it is reasonable to go the other way (to accept an integer value as a float) and it _might_ be reasonable to accept an integer value with no fractional component as a float, but I definitely don't think we should parse a float with a fractional value as an integer; it hides bugs like this.

[glyphs] Parse kerning as floats

---

glyphs-reader/src/font.rs
glyphs-reader/src/lib.rs
glyphs-reader/src/plist.rs
glyphs2fontir/src/source.rs

This is a rollup of three commits that rework how we parse custom parameter values from glyphs sources.
- This now parses all custom param values to the `Plist` type, which represents any plist data
- This means we do not need to know the expected type for a given key in order to parse it; we will parse anything that is in the source.
- *exhaustive handling*: Instead of querying into the custom parameters with the keys that we know, we now iterate through all the parameters in sequence, which forces us to handle them all (or report where we don't).
- This reuses the same parsing logic and `CustomParameters` type for the top-level `Font` as well as each individual master, which lets us delete a bunch of code
This PR doesn't change any observable behaviour, but there is a followup that will …

Glyphs custom params parsing rework

---

glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/UnusualCustomParams.glyphs

_This is based on #1143_
This handles additional custom parameters, specifically `openTypeHeadLowestRecPPEM`, and the various hhea & vhea caret properties (vhea isn't handled yet, but we can at least parse it now in preparation).
These params are kind of funny because you don't seem to be able to add them via the glyphs.app UI? But they exist in some fonts, and were causing crater failures.
- closes #1128

[glyphs] Handle additional custom params

---

fontc_crater/src/ci/html.rs

When showing crater to someone new to fonts they wondered what those things were, make it easier to find out
JMM

Add links to compilers to crater output

---

fontc_crater/resources/style.css
fontc_crater/src/ci/html.rs

When I load crater for my own use or to show others I typically want to see the latest results and the failures. As the list of results has grown this means load then scroll down almost every time. To mitigate this hide most of the results by default and provide an option to see all.
JMM if happy

Show only latest crater results plus a link to show more

---

glyphs2fontir/src/source.rs
resources/testdata/glyphs3/An-Italic.glyphs

```shell
$ python resources/scripts/ttx_diff.py 'https://github.com/Omnibus-Type/Faustina#sources/Faustina-Italic.glyphs' | grep DIFF
DIFF 'OS_2', build/default/fontmake.OS_2.ttx (98.1%)
DIFF 'STAT', build/default/fontmake.STAT.ttx (93.8%)
DIFF 'fvar', build/default/fontmake.fvar.ttx (97.7%)
DIFF 'glyf', build/default/fontmake.glyf.ttx (100.0%)
DIFF 'head', build/default/fontmake.head.ttx (95.5%)
DIFF 'hmtx', build/default/fontmake.hmtx.ttx (99.9%)
DIFF 'name', build/default/fontmake.name.ttx (96.4%)
$ python resources/scripts/ttx_diff.py 'https://github.com/Omnibus-Type/Faustina#sources/Faustina-Italic.glyphs' | grep DIFF
DIFF 'glyf', build/default/fontmake.glyf.ttx (100.0%)
DIFF 'hmtx', build/default/fontmake.hmtx.ttx (99.9%)
```
JMM if happy

Prove we don't match fontmake for Glyphs italic and fix it

---

fontbe/src/glyphs.rs
fontir/src/glyph.rs
fontir/src/ir.rs

If a glyph has mixed components & contours, we need to convert it to use all of one or the other.
If such a glyph has a component that _also_ has mixed components & contours, we need to make sure we handle the child component first.
We handles this by first collecting the set of such glyphs, and then determining an appropriate ordering.
I tried to keep this as simple as possible; in particular I'm defensive against cycles but am not reporting those errors here, since I assume we catch them elsewhere.
- fixes #1146

Deterministic resolving of mixed component/contour glyphs

---

fontir/src/error.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

In particular, we will now actually include the invalid string.
There are a number of failures on crater that report this error, so it would be nice to see what's going on.

Better reporting of InvalidTag errors

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/validate.rs
fea-rs/src/compile/variations.rs
fea-rs/src/token_tree/typed.rs
fontbe/src/features.rs
fontbe/src/features/kern.rs
fontbe/src/features/marks.rs
fontbe/src/fvar.rs
fontbe/src/mvar.rs
fontbe/src/orchestration.rs
fontbe/src/test_util.rs
fontc/src/lib.rs
fontdrasil/src/coords.rs
fontdrasil/src/piecewise_linear_map.rs
fontdrasil/src/types.rs
fontir/src/glyph.rs
fontir/src/ir.rs
fontir/src/paths.rs
fontir/src/variations.rs
fontra2fontir/src/toir.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

This replaces a bunch of use of f32 (in parsing and in coordinate types) with f64.
There are two tests that are failing which I don't want to touch, because I don't really understand what's best.
This doesn't have a dramatic impact on crater, but it does show improvements for fvar & HVAR for a number of fonts.
closes #1152 
(The main place where we still use f32 is when we are close to `F2Dot14` types, because f32 fully captures the precision these can represent)

We want more (f64)

---

glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/MultipleVendorIDs.glyphs

Fixes OS/2 and name diffs for `python resources/scripts/ttx_diff.py 'https://www.github.com/googlefonts/teko#sources/Teko.glyphs'`
JMM

Don't overwrite Glyphs v3 values with v2 values

---

glyphs2fontir/src/source.rs
resources/testdata/glyphs3/MultiplePanose.glyphs

Makes `python resources/scripts/ttx_diff.py 'https://github.com/notofonts/bamum#sources/NotoSansBamum.glyphs'` identical which hopefully tips us from 199 to 200+ identical on https://googlefonts.github.io/fontc_crater/
JMM

Prefer default master panose

---

fontir/src/ir.rs
resources/testdata/MetaTable.ufo/fontinfo.plist
resources/testdata/MetaTable.ufo/glyphs/contents.plist
resources/testdata/MetaTable.ufo/layercontents.plist
resources/testdata/MetaTable.ufo/lib.plist
resources/testdata/MetaTable.ufo/metainfo.plist
ufo2fontir/src/source.rs

Compile meta from ufo sources

---

resources/scripts/ttx_diff.py

Fixes #1173, `python resources/scripts/ttx_diff.py 'https://github.com/googlefonts/ingrid-darling#sources/IngridDarling.glyphs'` now passes.
JMM

Ignore the on/off curve marker if there is only one point

---

glyphs-reader/src/font.rs
resources/testdata/glyphs2/FeaLegacyName.glyphs

These were stored in the 'notes' field.
- fixes #1174

[glyphs] Handle legacy stylistic set names

---

glyphs-reader/src/font.rs
resources/testdata/glyphs2/ItalicItalic.glyphs

A custom name of "X Italic" for an Italic would result in "X Italic Italic".
Fixes `name` diff for `python resources/scripts/ttx_diff.py 'https://github.com/googlefonts/genos#sources/Genos-Italic.glyphs' --compare gftools --config ~/.fontc_crater_cache/googlefonts/genos/sources/config.yml` (though sadly GSUB remains)
Fixes #1175 
JMM

Let's not name things Thing Italic Italic

---

glyphs-reader/src/font.rs
resources/testdata/glyphs2/MasterNotMapped.glyphs

Makes `avar` match for `python resources/scripts/ttx_diff.py 'https://github.com/SorkinType/SplineSans#sources/SplineSans.glyphs'`
JMM

Expose and fix mistranslation from python that can lead to bad avar

---

fea-rs/test-data/compile-tests/mini-latin/good/contextual_format_4.fea
fea-rs/test-data/compile-tests/mini-latin/good/contextual_format_4.ttx

Specifically showing that we will combine the inline statements from multiple chain rules into a single lookup.
An identical test is included in https://github.com/fonttools/fonttools/pull/3726.
JMM

[fea-rs] Add test case for inline format 4 sub rules

---

fontc_crater/src/ci/html.rs

Because these came from a hashmap and we then sorted only by the count, if counts were equal the ordering could change between runs, which was causing us to push a bunch of unnecessary commits.
just noticed this when I went to pull crater changes locally and saw a whole load of new commits that were just shuffling this list. JMM.

[crater] Make summary sort order deterministic

---

fontbe/src/os2.rs
fontc/src/lib.rs
fontir/src/ir.rs
resources/testdata/FontInfo-Regular.ufo/fontinfo.plist
ufo2fontir/src/source.rs

Reduces diff for `python resources/scripts/ttx_diff.py 'https://github.com/wix/wixmadefor#sources/WixMadeforText-SemiBoldItalic.ufo'`
JMM if happy

Add support for ufo openTypeOs2Weight/WidthClass

---

fontbe/src/os2.rs
fontc/src/lib.rs
resources/testdata/FontInfo-Thin.ufo/fontinfo.plist
resources/testdata/FontInfo-Thin.ufo/glyphs/contents.plist
resources/testdata/FontInfo-Thin.ufo/layercontents.plist
resources/testdata/FontInfo-Thin.ufo/lib.plist
resources/testdata/FontInfo-Thin.ufo/metainfo.plist
resources/testdata/fontinfo_var.designspace

#1191 had a bug, add a test to expose and fix.
Makes `python resources/scripts/ttx_diff.py 'https://github.com/TypeNetwork/Josefinslab#sources/JosefinSlab.designspace'` identical.
JMM if happy.

Prefer variable default for usXClass when variable

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/tables/name.rs
fea-rs/src/compile/validate.rs
fea-rs/src/parse/grammar/metrics.rs
fea-rs/src/token_tree/typed.rs

Parsing NameSpec from fea retains the double quotes, dropping them only when generating final `name` records. That causes fontc to produce unwanted empty name records because it filters using is_empty. Naive solution: drop the quotes earlier so is_empty works as expected.
Makes `name` identical for `python resources/scripts/ttx_diff.py 'https://github.com/marcologous/hanken-grotesk#sources/HankenGrotesk.glyphs'`.

Drop quotes from names parsed from fea earlier so we detect empty ones correctly

---

glyphs2fontir/src/erase_open_corners.rs
glyphs2fontir/src/lib.rs
glyphs2fontir/src/toir.rs

This implements the functionality to erase 'open corners', which are features of some outlines where the intended corner of two curves needs to be inferred.
This implementation is a bit more verbose than we'd like, because kurbo does not currently have an implementation of arbitrary curve-curve intersection, so we've ported the implementation from fonttools' bezierTools.
... this was way more of a headache than I'd expected, with many exciting wrong turns and dead-ends. In any case, it seems like finally this is working although it only gives us a +1 on crater 😭

[glyphs] Impl 'erase open corners'

---

glyphs2fontir/src/erase_open_corners.rs
glyphs2fontir/src/toir.rs

My initial implementation of corner erasure had a significant problem: in an attempt to be clever I was not erasing corners as they were found, but instead collecting 'deletion operations' that could be applied all at once at the end.
The problem with this, in hindsight, is obvious: In a closed path, it is possible for a single segment to have an open corner at both ends, and correctly handling this requires applying the deletion of the first corner before trying to calculate the position of the second.
This new approach solves this by modifying the path in place, as corners are found. To do this efficiently it uses a copy-on-write type so that we only ever allocate if we actually are going to erase a corner, which is not the common case.
Doing it this was makes the logic tricky, because …

[glyphs] Rework corner erasure to delete in-place

---

fontc_crater/Cargo.toml
fontc_crater/src/ci.rs
fontc_crater/src/main.rs

That is, fonts that live in private repos under the googlefonts org.

[crater] Support for private fonts

---

resources/scripts/ttx_diff.py

Previously it was just 'adjusted', which is general enough that it was unclear to me when I saw it in diffs that it had originated in the ttx_diff script, and not in the original ttx output.
This name will hopefully make it more clear that this is a diff-specific thing.
JMM

[ttx_diff] Mark adjusted points as 'diff_adjusted'

---

glyphs2fontir/src/erase_open_corners.rs

This is a funny case that was also being mishandled by glyphsLib, although we were producing slightly different incorrect output so it showed up in a diff. I've put up a [patch for glyphsLib as well](https://github.com/googlefonts/glyphsLib/pull/1058); we should merge both of them or neither.
(merging both patches gives us a +9 on crater)

[glyphs] Erase open corners two segment edge case

---

fontir/src/ir/path_builder.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/toir.rs

Although it isn't supported in the editor, the glyphs source format supports curves with only on-curves, using the truetype 'implied oncurve points' model.
When dealing with a contour of this type, we should skip rotating the nodes when generating the path, because the first point of these contours is already correct (being the off-curve point of the first segment).
- fixes #1207

[glyphs] Don't rotate nodes if all are off-curve

---

fontc/src/lib.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/WghtVarGasp.glyphs

Makes `python resources/scripts/ttx_diff.py 'https://github.com/tokotype/PlusJakartaSans#sources/PlusJakartaSans-Italic.glyphs' --rebuild fontc` report the `gasp` table identical
JMM if happy

Implement gasp for .glyphs

---

resources/scripts/ttx_diff.py

[ttx_diff] put normalized `<contour>` elements first, before `<instructions>`

---

resources/scripts/requirements.txt

Fixes a regression in fonttools while computing bounds of nested composite glyphs with transformed components:
https://github.com/fonttools/fonttools/releases/tag/4.55.6
it should narrow down fontc_crater's glyf table diff a bit and probably fix #1206 for good

Update fonttools 4.55.6 in requirements.txt

---

glyphs-reader/src/font.rs

Fixes #1218
This matches `fontTools.misc.transform::Transform.rotate()` method, and makes Karla-Italic.glyphs ttx_diff.py output identical.

[glyphs-reader] normalize 90°/180°/270° rotated component transform

---

resources/scripts/requirements.txt

includes fix for https://github.com/googlefonts/glyphsLib/issues/1059 which should improve fontc_crater's overall diff score

update glyphsLib 6.10.0 in requirements.txt

---

Cargo.toml
fontbe/src/features/kern.rs
fontbe/src/features/properties.rs
glyphs-reader/src/glyphdata.rs

This also bumps us to use the new icu4x 2.0 beta.
icu4x is not currently returning the correct script values for codepoints that were added to ScriptExtensions.txt in Unicode 16, so we have a temporary workaround that manually checks for those specific values before calling out to icu4x.
Note: this will cause a a big crater drop until we merge and bring in https://github.com/fonttools/fonttools/pull/3756.

Work around icu4x issue with unicode 16 scriptext

---

resources/scripts/requirements.in
resources/scripts/requirements.txt

notably includes fixes for https://github.com/googlefonts/gftools/pull/1076 and https://github.com/googlefonts/ufo2ft/issues/896#event-16122153076

update gftools and ufo2ft in requirements

---

otl-normalizer/src/args.rs
otl-normalizer/src/common.rs
otl-normalizer/src/error.rs
otl-normalizer/src/gdef.rs
otl-normalizer/src/gpos.rs
otl-normalizer/src/lib.rs
otl-normalizer/src/main.rs
resources/scripts/ttx_diff.py

This table is a lot like mark/kern rules, in that it contains scalar values that can have variations applied. Like with those structures, this is an excellent case for normalization, since it means we can ignore differences related to the order in which deltas are stored.
This patch adds the ability to normalize this table, and updates ttx_diff to do that and to remove it as well as the VarStore from GDEF.
This gives us another +20 or so on crater.

Normalize Ligature Caret List

---

fea-rs/src/compile/features.rs
fea-rs/src/util/ttx.rs
fea-rs/test-data/compile-tests/mini-latin/good/always_sort_lookups.fea
fea-rs/test-data/compile-tests/mini-latin/good/always_sort_lookups.ttx
fea-rs/test-data/fonttools-tests/GPOS_2.expected_diff

The order of lookups within a feature don't matter. In general we end up with a sorted order via the implementation, but in the case where there are multiple declarations of a given feature this was not always the case.

[fea-rs] Ensure feature lookups are always sorted

---

glyphs2fontir/src/source.rs
resources/testdata/glyphs3/InvalidVendorID.glyphs

Since this is allowed to be missing; we can just log the error and continue.
This gets us compiling at least one more font, `madimi.glyphs`.
As a followup, the only diff between us and fontmake for this font is that we have the OS/2 `achVendID` value of `NONE` while fontmake has `    ` (0x20 * 4)`. I think fontmake is wrong here, since all spaces is not a valid tag, and the [spec clearly says that this should be a tag](https://learn.microsoft.com/en-us/typography/opentype/spec/os2#achvendid).

[glyphs] Don't error on invalid vendorID value

---

fea-rs/src/compile/features.rs
fea-rs/test-data/compile-tests/mini-latin/good/aalt_rule_order.fea
fea-rs/test-data/compile-tests/mini-latin/good/aalt_rule_order.ttx

The aalt feature has special behaviour where rules are supposed to be added to aalt from other features, in the order that those features are listed in the aalt block.
Unfortunately, since a given feature can exist for multiple languagesystems and contain different lookups for each, there is still ambiguity to the order in which rules are to be added.
Previously (and without much intention) we were adding rules in the order that the features would end up in the feature list; that is, within a feature we were adding rules based on the sorting order of the language systems.
This didn't match fonttools, where rules are added in the order that they are declared in the target feature.
With this patch, we match fonttools by re-sorting the lookups for a given feature based on the lookup id, …

[fea-rs] Tweak sort order of aalt rules

---

fontc/src/lib.rs
fontir/src/ir.rs

In tests I want to be able to write,
```
let gid = glyph_order.glyph_id("Aacute")
// instead of
let gid = glyph_order.glyph_id(&GlyphName::new("Aacute"));
```
So this just changes the argument of 'contains' and 'glyph_id' to use the same trait bounds as are used on the underlying collection.
JMM

Make GlyphOrder methods work with &str

---

fontbe/src/cmap.rs
fontbe/src/features.rs
fontbe/src/features/kern.rs
fontbe/src/features/marks.rs
fontbe/src/glyphs.rs
fontbe/src/gvar.rs
fontbe/src/hvar.rs
fontbe/src/metrics_and_limits.rs
fontbe/src/os2.rs
fontbe/src/post.rs
fontir/src/glyph.rs
fontir/src/ir.rs

::iter() now iterates over both gids and names
::iter_names() iterates over only names
JMM, another little tweak from ongoing work.

Tweak GlyphOrder iteration

---

fea-rs/src/compile/lookups.rs
fontbe/src/features/kern.rs
fontbe/src/features/properties.rs
fontbe/src/orchestration.rs

No functional change.
I was never very happy with how kerning is tested; in particular there was no clean entry point for unit tests, since a lot of the logic was inside the `KerningGatherWork`, which we can't easily launch without running the whole compiler.
This teases things apart a bit, so that we now have a `finalize_kerning` free fn that takes the raw kerning pairs and various bits of other necessary state and generates the kerning features & lookups.
On top of this, I'm able to build a test harness that lets us set all of the state that can impact kerning, and then inspect the output. This will let me write more tests that are more tractable, and where we can have more confidence that they reflect what is actually happening at runtime.

Refactor kerning logic to make it more testable

---

fontbe/src/glyphs.rs
resources/scripts/requirements.in
resources/scripts/requirements.txt

Now that fonttools has also removed this old workaround, we shall remove it as well in fontc.
See https://github.com/fonttools/fonttools/pull/1788
Fixes https://github.com/googlefonts/fontc/issues/283

[fontbe] remove workaround for old macOS bug with composites with all-zero deltas

---

Cargo.toml

This brings in a patch that makes our varstore generation more closely match fonttools.
JMM

[chore] Update write-fonts

---

fontbe/src/features/kern.rs

... when appropriate, which follows the same logic as for generating mark positioning rules: in the case of ufo/designspace sources, if categories are manaully defined in GDEF we will use those, otherwise we will use either public.opentypeCategories or the glyphs.app glyph category property.
This fixes a bug I noticed when implementing the 'dist' feature.

[kern] Use opentype categories to determine marks

---

resources/scripts/ttx_diff.py

- we weren't always deleting ligcaret output, which means that when running locally, it was being reused between different fonts.
- fixed a python warning about checking for None
JMM

[ttx_diff] Fix a pair of little things

---

.github/workflows/rust.yml

It doesn't help that CI always fails with PRs coming from forks with 'Error: Input required and not supplied: token'.
We can just skip that for forks.
JMM

[ci] skip Build GS job if PR is coming from a fork

---

Cargo.toml
fontbe/src/gvar.rs
fontbe/src/orchestration.rs
fontir/src/variations.rs

Hello all!
This is the companion pull request for the upstream googlefonts/fontations#1345, after we rehomed the initial attempt to conditionally write `gvar` intermediates (#1225); thank you for your patience.
We will close the older PR in favour of this.
Until we land upstream this is still a draft, so happy to use it to guide that PR in terms of naming, documentation, and any other finishing touches.

Use new `gvar` coordinates type with upstream intermediates optimisation

---

Cargo.toml

write-fonts 0.35.1 contained breaking changes from 0.35.0 and has been yanked. 0.36.0 is the correct next version.
JMM

[chore] Update write-fonts version

---

fontc/src/lib.rs

There were a bunch of things from fontations that were being imported via skrifa, which was making it hard to tell exactly what types from skrifa we were _actually_ using.
JMM

[fontc] Cleanup test imports

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/features.rs
fea-rs/src/compile/lookups.rs
fea-rs/src/compile/lookups/contextual.rs
fea-rs/src/compile/validate.rs
fea-rs/src/token_tree/typed.rs
fea-rs/src/util/ttx.rs
fea-rs/test-data/compile-tests/mini-latin/good/provider_basic_insert_marker.fea
fea-rs/test-data/compile-tests/mini-latin/good/provider_basic_insert_marker.ttx
fea-rs/test-data/compile-tests/mini-latin/good/provider_insert_between_rules.fea
fea-rs/test-data/compile-tests/mini-latin/good/provider_insert_between_rules.ttx
fea-rs/test-data/compile-tests/mini-latin/good/provider_remap_contextual_ids.fea
fea-rs/test-data/compile-tests/mini-latin/good/provider_remap_contextual_ids.ttx
fea-rs/test-data/compile-tests/mini-latin/good/provider_respect_ordering.fea
fea-rs/test-data/compile-tests/mini-latin/good/provider_respect_ordering.ttx
resources/scripts/ttx_diff.py

This was about as straight-forward as I could've hoped for, I think, and gives us a modest crater boost.
- closes #1257

Handle magic insertion marks when merging external features

---

resources/scripts/ttx_diff.py

That is, the order in which classes are assigned, which is then also the order of class sets within the lookup.
fontmake uses glyph names but fontc uses glyph ids; this reorders the fontc lookups to match fontmake.
This pattern might occur in a few other lookup types, but I'll handle them one at a time.

[ttx_diff] Reorder class-based chain sub order

---

fontbe/src/hvar.rs
fontc/src/lib.rs
fontdrasil/src/coords.rs
resources/testdata/glyphs2/WghtVar_ImplicitAxes.glyphs

Fixes #1256 
The first commit reproduces the bug, followed by actual fix

fix Glyphs 2 sources with implicit axes always getting indirect HVAR

---

fontc/src/lib.rs
glyphs-reader/src/font.rs
resources/testdata/glyphs3/WghtVarWithStylisticSet.glyphs

It looks like the glyphsLib impl was updated to do this since our original implementation.
Gives us at least a +1 on crater.

[glyphs] Skip empty stylistic set names

---

fea-rs/src/common.rs
fea-rs/src/compile/lookups/contextual.rs
fea-rs/test-data/compile-tests/mini-latin/good/chain_sub_format_choice.fea
fea-rs/test-data/compile-tests/mini-latin/good/chain_sub_format_choice.ttx

The way format 1 subtables work means they don't support input classes, _unless_ those classes contain a single glyph, in which case we can pretend they aren't classes.

[fea-rs] Handle edge case in chain context compilation

---

fea-rs/src/bin/ttx_test.rs
fea-rs/src/tests/compile.rs
fea-rs/src/tests/parse.rs
fea-rs/src/util.rs
fea-rs/src/util/ttx.rs

This functionality existed but only worked for the bundled fonttools tests (for historical reasons) this expands on that so it can be used for all the ttx-based tests, and lets it be controlled via the FEA_FILTER_TESTS environment variable.
Also removes some redundant code, but otherwise no functional change.
JMM

[fea-rs] Add ability to filter ttx tests with env var

---

glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/WghtVarInstancePanose.glyphs

Makes panose match for GSC. JMM if happy.

Support panose from instances

---

fea-rs/src/compile/metrics.rs
fontbe/src/features/kern.rs
fontbe/src/orchestration.rs

Since these are always a noop.
We had a test for this apparently, but it was wasn't failing as expected since it was using normalizer output, and normalizer doesn't bother showing us anything (since it's a noop).

[kern] Skip class/class kern rules with zero values

---

glyphs-reader/src/font.rs
resources/testdata/glyphs2/WghtVar_OS2.glyphs
resources/testdata/glyphs3/WghtVar_OS2.glyphs

GSMetric's `filter` attribute (that restrict a given metric to a group of glyphs, e.g. small caps) is not relevant to build OS/2 and MVAR tables. Some source contains those, normally following the same-named metric which is supposed to apply globally (and thus be stored in font wide metric tables).
glyphsLib does parse these filter attributes but doesn't even use them, when looking up a metric by name it simply returns the first one it finds. Similarly here when we collect metrics by name, we only take the first one we find and ignore any duplicate that may follow.
Fixes #1269  
After the fix, the following gives "output is identical"
```
$ python resources/scripts/ttx_diff.py 'https://github.com/Etcetera-Type-Co/Epilogue#sources/Epilogue.glyphs' --compare gftools --config …
```

Fix duplicate glyphs3 GSMetrics; take the first and ignore 'filter'

---

resources/scripts/requirements.txt

see https://github.com/googlefonts/ufo2ft/releases/tag/v3.4.2
this makes fontc_crater happier, notably for a brand font that becomes 'output is identical' after this
JMM

requirements.txt: update ufo2ft==3.4.2

---

resources/testdata/glyphs3/COLRv1-simple.glyphs

Realized from crater that fontmake is actively producing COLRv1 fonts from .glyphs sources and created a simple example of linear and radial gradients:

Add a simple font that fontmake compiles to COLRv1

---

resources/scripts/ttx_diff.py

There was one thing I'd forgotten to remap, and which I guess isn't used super often?
JMM

[ttx_diff] Fixup class-based context reordering

---

fea-rs/src/compile/lookups/contextual.rs
fea-rs/src/compile/lookups/gsub_builders.rs
fea-rs/test-data/compile-tests/mini-latin/good/contextual_duplicate_lig.fea
fea-rs/test-data/compile-tests/mini-latin/good/contextual_duplicate_lig.ttx

- Improves the logic for determining when we can reuse a lookup for an inline ligature sub rule, which will let us be much more aggressive in reusing these lookups,
- And adds logic to skip duplicate identical rules in ligature substitution tables.

[fea-rs] Better merging of contextual ligature rules

---

fontbe/src/features.rs
fontbe/src/features/kern.rs
fontbe/src/features/marks.rs
fontbe/src/orchestration.rs
fontc/src/workload.rs

In order to compile both marks & kern we need to have already compiled the GSUB table. To avoid doing this repeatedly, we now compile it immediately after parsing the AST, and then make it available to the mark & kern feature writers.
We also similarly store the explicit GDEF classes, if they were in the FEA, and try to share more code between mark & kern generation in general.
This also includes a commit that makes us convert glyph names to glyph ids earlier in the marks compilation process, which similarly helps us share more code with kerning.
(all of this is motivated by work on abvm and blwm)

[features] Share more code, do less work

---

Cargo.toml
fea-rs/src/util/ttx.rs

Fixes https://github.com/googlefonts/fontc/issues/945 and https://github.com/googlefonts/fontc/issues/1268
maybe since this was a patch (compatible) release, cargo should pick it up in any case, but I suppose it doesn't hurt if we explicitly do bump

bump write-fonts 0.36.1: computes checksum_adjustment and sorts tables as recommended

---

fea-rs/src/compile/lookups.rs

So... it turns out that this is extremely fiddly and complicated, and this patch isn't getting it completely correct; but I think it's worth checkpointing this, because I think the next step is a larger refactor, and I'll want to include some of this work in that.
So the problem we're trying to solve, here, is how best to match fonttools lookup ordering for lookups that are generated by 'feature writers'.
This is made more complicated by the fact that fonttools is generating FEA which it passes off to the feature compiler, but fontc is generating feature & lookup types directly, and then trying to merge them into the compiled FEA in such a way as to replicate the lookup ordering used in fonttools.
Some things that make this problem tricky:
- some lookups are declared inside a feature …

Better ordering of generated features

---

fontc_crater/src/ci/html.rs

Sometimes ttx_diff reports a diff with ratio of 1.0, and we were treating this the same as if it was identical. This patch makes sure we are distinguishing between 'identical' and 'very very close' by manually nudging the percent in this case.
JMM

[crater] Work around diffs rounded to 100%

---

glyphs-reader/src/font.rs
glyphs-reader/src/propagate_anchors.rs
resources/testdata/glyphs2/DontPropagateAnchors.glyphs

I've tested this by running ttx_diff on **notofonts/arabic/sources/NotoSansArabic.glyphspackage** and got these improvements:
|   COMPARISON  | Before  |   After   |
| ------------- | ------- | --------- |
| (mark / kern) | 29.249% | Identical |
|     GDEF      | 56.062% | Identical |
|     GPOS      | 87.500% | Identical |
|   ligcaret    | 34.043% | Identical |
(issue #889)

Respect 'Propagate Anchors' custom parameter

---

fontc_crater/src/ci.rs
fontc_crater/src/main.rs

This will let us update the crater input file without renaming it.

[crater] Store input sha instead of filename

---

glyphs-reader/src/font.rs
glyphs-reader/src/plist.rs
glyphs-reader/src/propagate_anchors.rs
glyphs2fontir/src/toir.rs
resources/testdata/glyphs3/COLRv1-simple.glyphs

Read the example provided in #1284

Parse basic linear/radial gradient specifications from .glyphs

---

glyphs-reader/src/plist.rs

Helps with FoldIt which does things like `color = "1"`, though FoldIt will still fail due to color tuples that don't have 4 values:
```
gradient = {
colors = (
(
(64,255),
0
),
(
(191,255),
1
)
);
end = (0.4489,0.0368);
start = (0.4192,0.8964);
};
```
Edit: 2 part colors appear to be grayscale per https://github.com/googlefonts/glyphsLib/blob/c4db6b981d577f456d64ebe9993818770e170454/Lib/glyphsLib/builder/common.py#L41-L50, will add that in a followon
JMM

Parse quoted numbers as bools, consistent with how normal numbers are handled

---

Cargo.toml

This brings in a fix that for a problem where we did not preserve the markFilterSet id when splitting GPOS subtables.

Bump write-fonts

---

fontc_crater/Cargo.toml
fontc_crater/src/ci.rs
fontc_crater/src/ci/html.rs

These are just displayed in a block at the top, after the summary but before the detailed report.
They aren't included as "other failures" because those are all associated with running particular targets, and this failure happens before we get a target. (A target is something specific in crater, and you can't create one wthout valid paths to the config and the source file.)
It's kind of ugly and we might want to iterate on that, but it at least gets the information out there.

[crater] Display repos for which we couldnt find targets

---

glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/SpacingMark.glyphs

Confused by what I was thinking when I wrote this, since I remember intentionally including SpacingCombining in this statement, based on some reference? but it isn't what python is doing, and it's a source of diff so... no clue.
JMM

[glyphs] Only non-spacing marks are non-spacing

---

glyphs-reader/src/font.rs
resources/testdata/glyphs3/MissingWidth.glyphs

see https://github.com/googlefonts/glyphsLib/blob/c4db6b981d577f456d64ebe9993818770e170454/Lib/glyphsLib/classes.py#L3662

[glyphs] match glyphsLib defaults if width is missing

---

glyphs-reader/src/glyphdata.rs

Missing this was causing us to incorrectly treat some glyphs as ligatures, which was then causing us to not include them in mark-to-base.
The list of categories/subcategories seems to have changed over time and/or not be fully documented; the list that I initially included were those that were available in the version of glyphs I was using at the time, but I've seen some other ones in the wild, and we can add them as they're encountered. (this was encountered in [NotoSansSiddham](https://github.com/notofonts/siddham)).
JMM

[glyphs] Add 'Composition' subcategory

---

fontbe/src/features/kern.rs

Otherwise we end up doing some unnecessary work, which was making it harder to debug another issue I was having with marks.

[kern] Exit early if there are no kern pairs

---

fontc_crater/src/args.rs
fontc_crater/src/ci.rs

I often like to run crater locally, but runtime is starting to get prohibitive. This option lets us skip all the gftools builds, which cuts the number of targets in half, but means we're at least still trying to build all the fonts we know of.

[crater] Add flag to skip gftools builds

---

fea-rs/src/token_tree/typed.rs
fontbe/src/features/kern.rs

That is, if the user FEA has a `kern` feature and there is no '# Automatic Code' comment, we will skip generating kerning rules based on non-FEA font data.
(on top of #1338)

[kern] Manual kern feature without insert mark wins

---

fea-rs/src/token_tree/typed.rs
fontbe/src/features/kern.rs

This reverts commit 801de70e1de9570c40ceb5366e03d7e0eb6339ac.
This caused a bunch of regressions on crater. I think it's something where we want to do this for ufo but not for glyphs? But I'll revert while I investigate further.
JMM

Revert "[kern] Manual kern feature without insert mark wins"

---

fea-rs/src/token_tree/typed.rs
fontbe/src/features.rs
fontbe/src/features/kern.rs

Specifically if it exists and there is no '# Automatic Code' insert marker.
We'll also want to do this for marks & curs, but that can be a followup PR.
- reworked from #1339 (which I reverted)
- based on #1344; without that patch merging this causes a significant regression.

[kern] If a manual kern/dist exists, don't generate one

---

glyphs-reader/src/glyphdata.rs

Gets at least one more GDEF matching.
Khaled mentioned elsewhere that we may want to be more permissive in what we accept for these values, since it _can_ just be a freeform field and we falling back to `None` might be a source of bugs, but I'm avoiding making that larger change in favour of simple forward progress.
JMM

[glyphs] Support 'Other' subcategory

---

glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/PreferableNames.glyphs

After this ttx_diff for GSC suggests `name` is the only table that differs and the difference is that only fontc emits name 25.
Fixes #1343

Support nameid 25 in .glyphs source and names on instances

---

fontir/src/ir.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/LightOriginNames.glyphs

https://www.youtube.com/watch?v=zMF_jc5BFcs describes my feelings about name handling.
I updated a number of expected results based on ttx diff.
Spot-checking name failures from crater this seems to help with at least the following:
* `python resources/scripts/ttx_diff.py 'https://github.com/batsimadz/Sankofa-Display#sources/Sankofa.glyphs'`
* `python resources/scripts/ttx_diff.py 'https://github.com/CatharsisFonts/Cormorant#sources/generated/CormorantGaramond.glyphs'`

Touchup name handling

---

glyphs-reader/src/glyphdata_bundled.rs

As is traditional #1357 included an off by one, leading to 108 fontc failures on https://googlefonts.github.io/fontc_crater/
JMM

Expose and fix off by one in bundled glyphs data

---

fontbe/src/font.rs
fontc/src/lib.rs
resources/testdata/CustomBaseTableInFea.ufo/features.fea
resources/testdata/CustomBaseTableInFea.ufo/fontinfo.plist
resources/testdata/CustomBaseTableInFea.ufo/glyphs/bar.glif
resources/testdata/CustomBaseTableInFea.ufo/glyphs/contents.plist
resources/testdata/CustomBaseTableInFea.ufo/layercontents.plist
resources/testdata/CustomBaseTableInFea.ufo/lib.plist
resources/testdata/CustomBaseTableInFea.ufo/metainfo.plist

We don't currently compile this table ourselves, so the logic here is a bit funny; we just check right at the end of compilation if we FEA generated one, and if so we add it to the final font.
Progress on #1364

Use BASE table from FEA, if present

---

fontbe/src/font.rs
fontbe/src/gvar.rs
fontbe/src/hvar.rs

Previously we would always generate some of these tables and then just skip them when we were assembling the final font; now we skip them earlier.
In the case of gvar there is probably some additional optimization possible, since we are still generating and storing all the empty gvar fragments, but the plumbing there is complicated so I've left that be for now.
Concretely this was motivated by me wanting to write a very simple test font that would include a STAT font from FEA, and for the purposes of my test I don't need this font to actually be variable.

[fontbe] Don't generate vf tables for static font

---

resources/scripts/ttx_diff.py

This PR extends the normalization in #1107 to `gvar`, which can be reordered in tandem to avoid equivalent diffs.
This patch improved the `gvar` percentage significantly in most crater projects I tested with, but there is still a remaining discrepancy that stems from there being more `gvar` deltas than points in `glyf` in some cases.
I have not had time to investigate further yet – and suspect anything from phantom points to me straight-up introducing bugs ; ) – hence the draft status. Does this difference sound familiar to anyone?
<sub>Note: this is a personal contribution independent of my employer, and so I've submitted from a fork under my personal profile and email to make this distinction</sub>

Reorder `gvar` points to match normalized `glyf`

---

glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/ZeroMetrics.glyphs

Glyphs does not serialize metric values if they are zero, but sometimes metric values are _intentionally_ zero, when they would otherwise be meaningless; we can distinguish (at least some of?) these cases because although the metric value is zero the overshoot is (often?) a non-zero value.
With this patch we distinguish between a metric which is missing and a metric that exists but has no value; in this latter case we treat it as having a value of zero.
----
This patch is an improvement, and gives us a +small on crater, but I don't think it goes far enough; I believe that a missing value for a metric should be treated as a `0`. Doing this breaks a bunch of tests, though, so I'm opening this smaller PR first, since it is at least some improvement; opened #1379 to discuss the larger change.

[glyphs] Treat null metric as zero if overshoot exists

---

resources/scripts/ttx_diff.py

There is some non-deterministic crash on CI where we are out of bounds on an array access; this will check that condition and skip if a delta is out of bounds.
~based on #1381, which should go in first~
JMM

[ttx_diff] Be more defensive when filling deltas

---

resources/scripts/ttx_diff.py

These are different ways of representing the absense of a value, and they both seem fine?
JMM

[ttx_diff] Treat 'NONE' and '`    `' tags as equivalent

---

glyphs-reader/src/font.rs
resources/testdata/glyphs2/WghtVar.glyphs
resources/testdata/glyphs2/WghtVar.glyphspackage/fontinfo.plist
resources/testdata/glyphs2/WghtVar_Anchors.glyphs
resources/testdata/glyphs2/WghtVar_Anchors.glyphspackage/fontinfo.plist
resources/testdata/glyphs2/WghtVar_Avar.glyphs
resources/testdata/glyphs2/WghtVar_Avar.glyphspackage/fontinfo.plist
resources/testdata/glyphs2/WghtVar_Instances.glyphs
resources/testdata/glyphs2/WghtVar_Instances.glyphspackage/fontinfo.plist
resources/testdata/glyphs2/WghtVar_NoExport.glyphs
resources/testdata/glyphs2/WghtVar_OS2.glyphs
resources/testdata/glyphs2/WghtVar_OS2.glyphspackage/fontinfo.plist
resources/testdata/glyphs2/alignment_zones_v2.glyphs
resources/testdata/glyphs2/infinity.glyphs
resources/testdata/glyphs2/infinity.glyphspackage/fontinfo.plist
resources/testdata/glyphs3/ZeroMetrics.glyphs
resources/testdata/glyphs3/infinity.glyphs
resources/testdata/glyphs3/infinity.glyphspackage/fontinfo.plist

That is, if a value is not defined for a particular master but is in the metrics list, we treat it as having a value of zero.
This more closely matches fonttools, and better handles the semantics of the glyphs format, which skips serializing `0` in some cases.

[glyphs] If a metric is defined, it has a value

---

glyphs-reader/src/font.rs
resources/testdata/glyphs2/OtherVendorName.glyphs

This seems to be used in some older glyphs sources, instead of 'vendorID'.
Based on #1386, which should go in first. otherwise JMM.

[glyphs] Use 'openTypeOS2VendorID' custom param, if set

---

resources/scripts/ttx_diff.py

In the case where there are different numbers of points in an outline (generally due to differences in corner erasure in very dense outlines?) adjusting off-by-ones can introduce a lot of noise that makes the diff harder to understand.
This impacts more fonts than I had expected, around ten.
JMM

[ttx_diff] Skip off-by-ones if element counts differ

---

glyphs-reader/src/font.rs
resources/testdata/glyphs3/InstanceNames.glyphs

Even if the instance does not have a name, which more closely matches the logic in glyphsLib.

[glyphs] Include names from variable instances

---

Cargo.toml
fontbe/Cargo.toml
fontc/Cargo.toml
fontdrasil/Cargo.toml
fontir/Cargo.toml
fontra2fontir/Cargo.toml
glyphs2fontir/Cargo.toml
ufo2fontir/Cargo.toml

Patch bump impacted things so they can be deployed.
Fontations ran into this, fixed in https://github.com/googlefonts/fontations/pull/1408 by using nu-ansi-term. Since we seemingly don't use it I just dropped it here.

Remove ansi_term dep, impedes google3 and unused

---

fontir/src/error.rs
fontir/src/ir.rs
fontir/src/ir/static_metadata.rs
resources/testdata/dspace_rules/Basic.designspace
resources/testdata/dspace_rules/CustomFeatures.designspace
resources/testdata/dspace_rules/Last.designspace
resources/testdata/dspace_rules/README.md
ufo2fontir/src/source.rs

This is the first step towards supporting `rvrn` (and other feature variations features) from designspace files.

Add IR types for FeatureVarations, parse from dspace

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/feature_writer.rs
fea-rs/src/compile/features.rs
fea-rs/src/compile/lookups.rs
fontbe/src/features.rs
fontbe/src/features/feature_variations.rs
fontc/src/lib.rs
fontdrasil/src/coords.rs

This was a bit hairier than expected, naturally.
The basic idea is pretty simple: we treat this like other 'feature providers', where the state is passed into fea-rs which then handles the compilation. Getting that working was a bit of a project though because we didn't previously support external features/lookups that end up in GSUB.
- closes #412

Compile FeatureVariations from designspace files

---

ufo2fontir/Cargo.toml
ufo2fontir/src/source.rs

Hello, we're getting the whole team into fontc bug fixing. This was a bug spotted on one of our library fonts.

Fix OS/2 fsSelection for an italic-only font, to match ufo2ft

---

fontdrasil/src/coords.rs

Hello! Just a measly -1 byte PR to make the constant match 🚀

Fix typo in normalized space coord maximum

---

glyphs-reader/src/glyphdata.rs

This ``or_else`` which I removed here is actually not needed because the ``construct_category`` method already handles glyph names with a suffix basically the same way.
https://github.com/googlefonts/fontc/blob/e14ac32850aa5efdb0584f347be1fbfd8c9d8309/glyphs-reader/src/glyphdata.rs#L527-L533
In fact, even after removing the block, the method ``match_prod_name_with_suffix`` added with PR #1354 continues to pass, confirming the removed lines are unnecessary.
https://github.com/googlefonts/fontc/blob/e14ac32850aa5efdb0584f347be1fbfd8c9d8309/glyphs-reader/src/glyphdata.rs#L1093-L1102

[glyphdata.rs] simplify logic for glyph names with suffixes

---

fontbe/src/fvar.rs
fontbe/src/stat.rs
fontir/src/ir/static_metadata.rs

In the case where multiple existing name records are applicable for reuse, the non-deterministic order of HashMap meant that either could be chosen. This PR explicitly prefers the smallest ID, which makes the process deterministic, and matches [fonttools' behaviour](https://github.com/fonttools/fonttools/blob/d5aec1b9dbcbaa3f97d0d553fe85a92927b48faa/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L326-L329).
(I think this covers everywhere, but is there anywhere else that needs updating?)

Make name reuse deterministic, and use smallest ID as fonttools does

---

fontbe/src/features/feature_variations.rs
fontir/src/ir/static_metadata.rs
ufo2fontir/src/source.rs

This was an oversight in the original implementation; order doens't matter here, so let's keep the innards private and sorted.

[fontir] Enforce that ConditionSet always sorted

---

glyphs-reader/src/font.rs
glyphs-reader/src/glyphdata.rs
glyphs-reader/src/glyphdata_bundled.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs2/ProductionNames.glyphs
resources/testdata/glyphs3/ProductionNames.glyphs

Towards fixing https://github.com/googlefonts/fontc/issues/248
After #1354 we have the production names in our generated glyphdata but were using it only for looking up a glyph's category/subCategory using its production name.
This PR uses these same production names for their primary purpose i.e. renaming glyphs in the final font ready for 'production' (which means following the AGLFN rules).
The `--no-production-name` CLI flag is now being used for this when the inputs are .glyphs sources. Previously it was only having an effect when the input was a .designspace or .ufo.
I haven't implemented yet the additional logic in glyphsLib for those glyphs that have suffixes or comprise ligatures but do not have a predefined `production` name set in the GlyphData.xml. I will probably tackle that …

[glyphs] read production names from GlyphData to populate glyph postscript names

---

glyphs-reader/src/font.rs
resources/testdata/glyphs3/AxisRules.glyphs

This is split out from the work on bracket layers.
This will parse the `axisRule` layer attribute in glyphs3, and will parse rules out of layer names for glyphs2.

[glyphs] Parse 'axis rules'

---

fontbe/src/features/marks.rs
fontbe/src/fvar.rs
fontc/src/lib.rs
fontir/src/ir/static_metadata.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/InstanceNoPostscript.glyphs
resources/testdata/glyphs3/InstancePostscript.glyphs
ufo2fontir/src/source.rs

Implements https://github.com/googlefonts/fontc/issues/1371
([fonttools already supports this](https://github.com/fonttools/fonttools/blob/cc10bfc7d18e97efe1c5239ce5f47ba73050e3db/Lib/fontTools/varLib/__init__.py#L136-L138), although only from UFOs as glyphsLib does not parse this custom parameter yet)

Compile per-instance postscript names from Glyphs and designspaces

---

fontbe/src/features/feature_variations.rs
fontbe/src/features/marks.rs
fontbe/src/features/test_helpers.rs
fontbe/src/hvar.rs
fontbe/src/mvar.rs
fontdrasil/src/coords.rs
fontdrasil/src/types.rs
fontir/src/ir/static_metadata.rs
fontir/src/variations.rs
fontra2fontir/src/toir.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
ufo2fontir/src/source.rs
ufo2fontir/src/toir.rs

This serves as a collection of axes, and handles the very common task of providing a mapping from a tag to an axis.
I was noticing that each compilation was creating potentially thousands of duplicate transient mappings; now we hopefully only do it once.
No functional change.
JMM

Add fontir::Axes type

---

resources/scripts/requirements.txt

Updated using [the usual procedure](https://github.com/googlefonts/fontc/tree/main/fontc_crater#ci) – mostly hoping to bump fonttools to see fonttools/fonttools#3797 through to completion, which should give a nice crater boost :)

Update Python requirements to bump fonttools

---

fontbe/src/post.rs
fontc/src/lib.rs
glyphs-reader/src/font.rs
glyphs-reader/src/glyphdata.rs
resources/scripts/requirements.in
resources/scripts/requirements.txt
resources/scripts/ttx_diff.py
resources/testdata/glyphs3/ProductionNames.glyphs

Meant to fix https://github.com/googlefonts/fontc/issues/248 and #1299 
by "synthetic" production names I mean production names for glyphs that, even though they have no direct entry in GlyphData, their production name can be derived (e.g. alternate glyphs ending with a suffix or ligatures where each ligature component does have an explicit production name).
I also disabled --no-production-name flag in ttx_diff.py, which means fontc_crater will apply the final glyph renaming after this PR, for both DS and .glyphs sources.
This build GSC and Oswald without ttx diffs (I haven't tried a full local fontc_crater run).

glyphdata: support synthetic production names

---

fea-rs/src/compile/feature_writer.rs
fontc/src/lib.rs
resources/testdata/WghtVar-Bold.ufo/features.fea
resources/testdata/WghtVar-Regular.ufo/features.fea

In the course of the bracket layers work I've been finding a few little bugs in the original designspace-based work.
It turns out we only have one font in the crater collection that both uses designspace feature variation rules, _and_ has other GSUB features (Geologica) so this slipped through the cracks.

[fea-rs] Remap ids after inserting rvrn lookups

---

fontbe/src/features/feature_variations.rs
fontc/src/lib.rs
resources/testdata/dspace_rules/Basic.designspace
ufo2fontir/src/source.rs

This is a funny special case because it isn't handled by the usual FEA codepaths; however it is fairly easy to match fonttools and the resulting code is pretty self-contained, so I think it's reasonable.
This doesn't do much now, but becomes important when we land the bracket layers stuff.

[fea-rs] Match fonttools sorting for feature variations

---

fontbe/src/features.rs

The command line option is --emit-debug not --emit_debug.

Fix a typo in a warning message

---

fea-rs/src/compile/features.rs
fea-rs/src/compile/lookups.rs
fea-rs/src/compile/lookups/contextual.rs
fontc/src/lib.rs
resources/testdata/WghtVar-Bold.ufo/features.fea
resources/testdata/WghtVar-Regular.ufo/features.fea

Because this is what happens in fontmake, and I'd missed this in the noise of other diffs.

[fea-rs] Sort rvrn lookups ahead of aalt

---

fontc/src/lib.rs
fontc/src/workload.rs
fontir/src/glyph.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs

Tl;dr just do it in glyphs2fontir, don't fiddle with core processing
Reverts changes to core processing.
glyphs2fontir now presents bracket glyphs as normal glyphs it produces in the preliminary glyph order. It then produces two distinct implementations of work for glyphs, one for not-brackets and one for brackets. This enables things like don't run the bracket until the parent (terminology?) is done.

Try to implement Colin's original approach to bracket layers

---

fontc/src/lib.rs
fontc/src/workload.rs
fontir/src/glyph.rs
fontir/src/ir.rs
fontir/src/orchestration.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
resources/testdata/glyphs2/WorkSans-minimal-bracketlayer.glyphs

On top of #1437, this actually generates the alternate glyphs.
This does _not_ generate the FeatureVariations tables, but it does give us a whole bunch of targets on crater for which those are the only things missing...

Generate bracket glyphs

---

fontc/src/args.rs
fontc/src/lib.rs
fontir/src/glyph.rs
fontir/src/orchestration.rs

intended to match the functionality of fontmake's `--filter DecomposeComponentsFilter` option used by some of the fonts in our collections like Jacquard12.glyphs.
Fixes https://github.com/googlefonts/fontc/issues/1441
(note that for ttx_diff.py to work with this, we also need modify gftools builder to let this option through, currently it will still raise ValueError: unknown fontmake arg. See https://github.com/googlefonts/gftools/pull/1113).

Add --decompose-components option to turn all composites to simple glyphs

---

fontir/src/orchestration.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/LibreFranklin-bracketlayer.glyphs

recycled from #1457, which is obsoleted by #1456

[glyphs] Add test case for bracket glyph anchors

---

fontc/src/lib.rs
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs2/WorkSans-minimal-bracketlayer.glyphs

This generates the actual lookups, features, and FeatureVariation tables that make use of the bracket glyphs.

[glyphs] Generate feature variations

---

fea-rs/Cargo.toml
fontbe/Cargo.toml
fontc/Cargo.toml
fontc_crater/Cargo.toml
fontdrasil/Cargo.toml
fontir/Cargo.toml
fontra2fontir/Cargo.toml
glyphs-reader/Cargo.toml
glyphs2fontir/Cargo.toml
otl-normalizer/Cargo.toml
ufo2fontir/Cargo.toml

Bumping all the published crates' minor version in preparation for a fontc v0.2.0 release. This is the list of changes per crate
```
Changes for fontdrasil from fontdrasil-v0.1.1 to 0.2.0
92b9570 bump fea-rs, fontc and related crates' minor version
a37a6fa [glyphs] Factor out layer->ir logic
98348f8 Add fontir::Axes type
7dcb264 Fix typo in normalized space coord maximum
bcbf2dd Wire up FeatureVariations support
a8da93d Simplify creating Axes for testing
Changes for fea-rs from fea-rs-v0.19.1 to 0.20.0
92b9570 bump fea-rs, fontc and related crates' minor version
a09320f [fea-rs] Update fonttools test case with new glyphs
60ff232 [fea-rs] Combine mixed single & liga sub rules
6b30dd9 [fea-rs] Add some docs
4f3db12 [fea-rs] Error on conflicting lig sub rules
74d853f [fea-rs] Sort rvrn …
```

bump fea-rs, fontc and related crates' minor version

---

.github/workflows/release.yml

the release workflow failed because of an incompatibility between pip-compile and the latest pip
https://github.com/jazzband/pip-tools/issues/2176
https://github.com/googlefonts/fontc/actions/runs/15186515318/job/42708565488#step:4:37
(we use pip-compile to generate the requirements.txt to be used by the Glyphs.app fontc plugin)
The current workaround is to pin pip to the version immediately preciding the offending one.
Note that the fontc-v0.2.0 wheels were successfully published to PyPI, only the creation of the Github Release (and upload of the binary artifacts to the GH release page) failed. I'll do a manual run of the release workflow after this is merged and hopefully it will just work.

[ci/release] pip pip<25.1 due to incompatibility with pip-compile

---

fontc/src/lib.rs
fontir/src/glyph.rs
resources/testdata/glyphs3/NestedNoExportComponent.glyphs

Currently if a no-export glyph is a component in a composite glyph, which is also a component in another composite glyph, all the composite glyphs will be decomposed into simple glyphs. This is because no-export components are flattened before decomposing no-export glyphs.
Decomposing no-export glyphs first then flattening, does not decompose the composite glyph with nested components, which keeps the file size smaller and matches what ufo2ft does.

Improve flattening nested no-export components

---

resources/scripts/ttx_diff.py

Some fonts use name IDs that do not exist in the name table, so don’t assume the name ID is valid when mapping it to its string.
This is seen with https://github.com/dancoull/ClimateCrisis after https://github.com/googlefonts/fontc/pull/1470.

[ttx_diff] Protect against non-existing name IDs

---

fontc/src/lib.rs
glyphs2fontir/src/source.rs

see https://github.com/googlefonts/glyphsLib/issues/1081; glyphs.app puts these under rlig, but glyphsLib does not, so let's match glyphsLib for now.

[glyphs] Feature variations go under rvrn by default

---

fea-rs/src/compile/tables.rs
fea-rs/test-data/fonttools-tests/spec9c1.ttx
fea-rs/test-data/fonttools-tests/spec9c2.ttx
fea-rs/test-data/fonttools-tests/spec9c3.ttx

This had been zero'd out to match fonttools, but fonttools now uses the expected value.
(This also brings in updated fonttools test files.)
JMM

[fea-rs] Use correct magic number in head table

---

fontbe/src/features/feature_variations.rs
fontir/src/feature_variations.rs
fontir/src/ir/static_metadata.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs2/Alexandria-bracketglyphs.glyphs

_this is on top of #1476_
Specifically this means running the 'overlay_feature_variations' method
twice, once in glyphs2ir and then finally when generating the actual
feature variations tables.
To make this possible we had to refactor that code to work on glyph
names, instead of on GIDs.
With this patch we are showing identical for a number of new fonts on crater.

[glyphs] More preciesly match glyphsLib bracket logic 

---

fontir/src/feature_variations.rs

I'm not totally sure how I screwed this up? But it was causing a problem in one of our test fonts, and this is now matching the python.
JMM

Fixup a bug in overlay_feature_variations

---

Cargo.toml
fea-rs/src/compile/features.rs
fea-rs/src/compile/lookups.rs
fea-rs/test-data/compile-tests/mini-latin/good/rule_promotion_and_aalt.fea
fea-rs/test-data/compile-tests/mini-latin/good/rule_promotion_and_aalt.ttx
fea-rs/test-data/fonttools-tests/spec8a.ttx

That is, if a single sub rule has been promoted to a ligature or multiple sub lookup, but it is in an aalt-participating feature, we should still include those rules in aalt.
See https://github.com/fonttools/fonttools/pull/3847 for the fonttools impl of this logic.
(this will be a minor regression until we update fonttools in ci, but I think that's okay)

[fea-rs] Account for promoted rules in aalt

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/test-data/compile-tests/mini-latin/good/mixed_single_and_liga_with_lookupflags.fea
fea-rs/test-data/compile-tests/mini-latin/good/mixed_single_and_liga_with_lookupflags.ttx

this was an oversight that was also missing in fonttools, but it has been fixed there as of https://github.com/fonttools/fonttools/pull/3849.

[fea-rs] Check lookupflags before promoting mixed rules

---

fontbe/src/features/ot_tags.rs

This PR mirrors the equivalent fix for issue googlefonts/ufo2ft#896 in commits googlefonts/ufo2ft@b06c85c5 and googlefonts/ufo2ft@0b5e1598.
As a lone difference it avoids retaining the incorrect name for N'Ko, as my understanding is that unlike ufo2ft all use-cases are in-repo and so there is no outwards backwards compatibility to preserve.
This gives a few crater wins for the respective Noto fonts for each writing system.
cc @anthrotype

Fix typos in Bhaiksuki and N'ko script tags, following ufo2ft

---

glyphs-reader/src/font.rs
glyphs-reader/src/propagate_anchors.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/glyph-with-bracket-component.glyphs

One of the larger remaining todos for bracket layers: if a glyph does not have bracket layers but it has components that do, we need to create dummy bracket layers in order for the components to be set correctly.

[glyphs] Propagate component bracket layers

---

fontir/src/ir.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs2/BracketTestFontKerning.glyphs

This is the last remaining thing I'm aware of, related to bracket glyphs, and should fix a few outstanding mark/kern diffs on crater.
The test + test file was taken from glyphsLib and cleaned up a little bit.
(edit: this should actually give us a healthy +identical on crater)

[glyphs] Expand kerning to bracket glyphs

---

resources/scripts/ttx_diff.py

Since #979, we have been disabling overlap removal for fontmake's static builds, but this was only applying in the `default` mode. This PR ensures it applies it in the `gftools` mode too, to make it clear which differences are due to gftools' influence alone.
In particular, some Soft Type fonts that only differed in their gftools builds now build identically :rocket: 
This PR also:
- Makes overlap removal configurable with a flag, as we will re-enable it in all static cases later (#717)
- Fixes space-separation when concatenating extra arguments, which was needed to pass in the new arg and – if we cross our fingers – may fix existing crashes on crater too

Disable overlap removal for gftools too

---

fontc/src/lib.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs
resources/testdata/glyphs_fea_include/features/hello.fea
resources/testdata/glyphs_fea_include/glyphs_include.glyphs

This requires tracking the directory where the file was stored, and passing this through to fea-rs, so it can lookup referenced files using that directory as a base.
This is currently the source of a number of fontc crashes (which it might not fully fix, but at least they evolve into a different sort of crash)

[glyphs] Support include statements in glyphs sources

---

glyphs2fontir/src/source.rs

Reverts googlefonts/fontc#1501
After some discussion with @anthrotype we believe that this is not quite the correct approach. The problem is that we are not currently propagating anchors on bracket layers, which means that even if bracket glyphs have the correct GDEF class, they don't have the correct anchors, which makes them useless.
If we fix anchor propagation to handle bracket glyphs, then we should get the correct categories for free. Cosimo is going to work on patch for this in glyphsLib first, and then we'll match that behaviour here.

Revert "Determine GDEF categories for bracket glyphs too"

---

resources/testdata/glyphs2/OpszWghtVar_AxisMappings.glyphs
resources/testdata/glyphs3/WghtVar_AxisLocation.glyphs

... using a more recent .appVersion to workaround this bug:
https://github.com/googlefonts/glyphsLib/issues/993#issuecomment-2962404528
I need this for #1528 but would like to reduce the diff noise there
JMM

open/save a bunch of .glyphs testdata file with newer Glyphs.app

---

fontc_crater/src/ci.rs
fontc_crater/src/target.rs
resources/scripts/ttx_diff.py

- when creating a reproduction command for ttx_diff, we will now pass the relevant SHA as a url query
- in a repro command for a target with a disambiguated checkout (i.e. that includes a _SHA suffix) we will strip that suffix from the command (but include the appropriate SHA as a query, above)
- in ttx_diff we will checkout the rev that is passed as a query.
annoyingly, this involved a change to the data representation of a 'target', which means that crater will act as if every result in the run that includes this change is new; after that one run everything should go back to normal.

Handle git revs in crater/ttx_diff

---

glyphs2fontir/src/source.rs

This applies the common custom parameter precedence of instance, then master, then overall font, netting a new target on crater.

Accept 'meta Table' custom parameter from multiple places

---

fontbe/Cargo.toml
fontc/src/args.rs
fontc/src/lib.rs
fontc/src/timing.rs
fontc/src/workload.rs
fontir/Cargo.toml
glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
glyphs2fontir/src/toir.rs

There are three blockers to running fontc over WASM:
* The pervasive use of timers, which can be a pain when `Instant::now()` causes a crash; we either make them optional (`JobTimer`) or we conditionally hide the actual `instant` fields.
* The use of file paths, which can be a pain when you don't have a filesystem; we provide ways of getting pre-loaded binary data into the Args struct and using that instead, and provide an alternate `run` method which directly emits the binary file instead of writing it to disk.
* The use of threads in the workload orchestrator; we don't use a separate ThreadPool and use a nightly version of crossbeam while on WASM to make it all compatible with [wasm-bindgen-rayon](https://github.com/RReverser/wasm-bindgen-rayon).
The result is a web-based font compiler; …

Allow building on WASM

---

glyphs-reader/src/font.rs
glyphs-reader/src/propagate_anchors.rs
resources/testdata/glyphs2/AlumniSans-wononly.glyphs

- we were not using the associated master id when looking for backup anchors during propagation
- we were not accounting for the fact that it is possible for only bracket layers to have components, but not normal layers.
this gives us another handful of identical 💁 
JMM

[glyphs] Fix bug in anchor propagation

---

.github/workflows/rust.yml
fontc/Cargo.toml
fontc/src/args.rs
fontc/src/lib.rs
fontc/src/timing.rs
fontc/src/workload.rs
fontir/Cargo.toml
glyphs2fontir/src/source.rs

Following Rod's comments on #1478, this cleans up the library interface to fontc by:
* Reducing WASM cfg ifdefs by choosing once between real and fake clocks for timing
* Separating out CLI-specific functions such argument parsing and moving the Clap dependency to the binary
* Merging "on disk" and "in memory" sources into a single `Input` type
* Sharing common code between the library and binary entry points
The clocks stuff turned out to be a little gnarly because of the use of `Instant` in the timing structs. I broke it down into fairly small atomic commits for ease of reviewing.

Library cleanliness

---

fea-rs/Cargo.toml
fontbe/Cargo.toml
fontc/Cargo.toml
fontc_crater/Cargo.toml
fontdrasil/Cargo.toml
fontir/Cargo.toml
fontra2fontir/Cargo.toml
glyphs-reader/Cargo.toml
glyphs2fontir/Cargo.toml
otl-normalizer/Cargo.toml
ufo2fontir/Cargo.toml

```
Changes for fontdrasil from fontdrasil-v0.2.0 to 0.2.1
e789909 Simplify the debug repr of Coords
2ff7939 [clippy] Push the rock back up the hill
851376e [fontdrasil/ufo2fontir] Prefer axis (English) `<labelname>` over axis.name like fonttools does
Changes for fea-rs from fea-rs-v0.20.0 to 0.20.1
2ff7939 [clippy] Push the rock back up the hill
c3896ea [fea] Handle nested contextual lookups in aalt
e7e9494 [fea-rs] Account for promoted rules in aalt
0c74763 [fea-rs] Check lookupflags before promoting mixed rules
e18b0ee [fea-rs] Mask out high byte of lookupflag literals
a455043 [fea-rs] Allow featureNames and cvParams in GPOS
da49909 fix up all occurrences of Axis with empty localized_names map
1acd3a1 [fea-rs] Use correct magic number in head table
Changes for fontir from fontir-v0.2.0 …
```

bump fontc and other crates in preparation for 0.3.0 release

---

resources/scripts/requirements.txt

notably, fonttools 4.59 no longer depends on fs
https://github.com/fonttools/fonttools/releases/tag/4.59.0

update fonttools in requirements.txt

---

resources/scripts/ttx_diff.py

If I copy and run one of fontc_crater's reproducer commands I get the following error when the url contains a query (? followed by the commit sha):
```
$ python resources/scripts/ttx_diff.py 'https://github.com/JulietaUla/Montserrat?cc8daf2e70#sources/Montserrat-Italic.glyphs'
https://github.com/JulietaUla/Montserrat?cc8daf2e70#sources/Montserrat-Italic.glyphs
Running git clone https://github.com/JulietaUla/Montserrat?cc8daf2e70 in /Users/clupo/.fontc_crater_cache/JulietaUla
Cloning into 'Montserrat?cc8daf2e70'...
fatal: https://github.com/JulietaUla/Montserrat?cc8daf2e70/info/refs not valid: is this a git repository?
Traceback (most recent call last):
File "/Users/clupo/oss/fontc/resources/scripts/ttx_diff.py", line 1320, in <module>
app.run(main)
~~~~~~~^^^^^^
File …
```

ttx_diff: exclude query from the git clone url

---

resources/scripts/requirements.txt

should fix a regression in glyphsLib 6.11.2 affecting a bunch of fonts in fontc_crater (e.g. Playfair) regarding glyphs using components with alternate layers 
https://github.com/googlefonts/glyphsLib/releases/tag/v6.11.3

update glyphsLib in requirements.txt

---

fea-rs/src/compile/feature_writer.rs

This was the cause of a diff in NotoSerifTibetan: that FEA contained an a `kern` feature, but the feature writer was only generating a `dist` feature. In this case it should not consider the presense of the `kern` feature when determining where to insert the lookups for `dist`.
This should get us at least a +1 on crater :)
JMM

[kern] Ignore feature markers from ungenerated features

---

fontdrasil/Cargo.toml
fontdrasil/src/lib.rs
fontdrasil/src/util.rs
glyphs-reader/src/propagate_anchors.rs

Specifically I want to use it in fontir, which means it shouldn't live in glyphsLib.
I've added a trait in order to support different possible glyph types.
This is no functional change, just a refactor.

Make 'depth_sorted_composite_glyphs' a general util fn

---

otl-normalizer/src/gpos.rs
otl-normalizer/src/gpos/cursive.rs
resources/scripts/ttx_diff.py

This is simple as there's only one subtable type and it reueses structures we already had from other work.
This does give us at least a +1, but it also has made clear that we have a bug in our cursive lookup generation, where it seems like we're handling RTL differently from fontmake.

[normalizer] Normalize cursive pos

---

glyphs-reader/src/font.rs
resources/testdata/glyphs3/WghtVar_AxisLocationFloat.glyphs

`python3 resources/scripts/ttx_diff.py 'https://github.com/usted/Albert-Sans?f7f4608223#sources/AlbertSans-Italic.glyphs' --compare gftools --config ~/.fontc_crater_cache/usted/Albert-Sans/sources/config.yaml` is identical with this change.
JMM.

Truncate axis location values like glyphsLib

---

fontir/src/glyph.rs

Tiny fixups to try and make some of these things more visible, as I try to debug a funny component flattening issue.
JMM

[fontir] Tweak glyph ir logging

---

fontc_crater/resources/style.css
fontc_crater/src/ci/html.rs

This allows users to add 'annotations' to targets, which can be used to explain known problems and link to issues.
Annotations are added by manually editing an `annotations.json` file stored alongside the output.
Annotations are maximally dumb: they are associated with a target and will be visible for as long as that target produces a diff, unless they are manually removed.
(This seems more and more useful as we get into the long tail, and is particularly motivated by the fact that I'm currently focused on investigating diffs and opening issues.)
annotations are displayed like:
and if no annotations exist, a little button will give you the following:

[crater] Support annotations

---

fea-rs/src/compile/compile_ctx.rs
fea-rs/src/compile/features.rs
fea-rs/test-data/compile-tests/mini-latin/good/lookupflag_scope.fea
fea-rs/test-data/compile-tests/mini-latin/good/lookupflag_scope.ttx

This is kind of interesting; I'm not really sure that fonttools is correct, but it matches afdko and this is a corner case that is unlikely to matter in a real source.
According to the spec, any lookupflags should be cleared whenever we encounter a script statement.
fonttools follows this, _unless_ the current language system is already (script, dflt), where 'script' is the script set by the new statement.
We _kind of_ matched this, previously, except that we did not take the language into account; we would skip clearing the flags if the new script was the same as the old one.
The fonttools logic here is definitely better. That said, the behaviour is unintuitive in some cases, for instance:
```fea
feature derp {
lookup W {
lookupflag IgnoreMarks;
script latn;
sub one by two;
} W;
lookup X …
```

[fea-rs] Better match fonttools handling of script stmt

---

fontbe/src/glyphs.rs
fontc/src/lib.rs
resources/testdata/glyphs3/ComponentPointRounding.glyphs

This matches fontmake (and also our own simple glyphs) where rounding occurs before the final variation data is generated.
gives us another +small identical.
JMM

[fontbe] Round component pts before generating deltas

---

resources/scripts/ttx_diff.py

I am not entirely sure why, but after #1590 running ttx_diff.py on Kablammo.glyphs gives a weird "lxml.etree.XPathEvalError: unknown error".  Notice the +2 in red under https://googlefonts.github.io/fontc_crater/#other-failures
Maybe the xml file is to big and the xpath expression too broad? i am not entirely sure. But making the xpath expression more selective and explicit seems to fix the error.
JMM

ttx_diff: use more specific xpath to select nameID=25

---

glyphs-reader/src/font.rs

Reverts #1588
Requires https://github.com/googlefonts/glyphsLib/releases/tag/v6.11.5
JMM

[glyphs-reader] Don't truncate Axis Location values as in latest glyphsLib

---

fontc_crater/src/ci.rs
fontc_crater/src/ci/html.rs
fontc_crater/src/main.rs

It's otherwise tricky to see what targets take the longest to run, which is something I'm curious about.

[crater] Print per-target runtime

---

fontbe/src/glyphs.rs
fontc/src/lib.rs
resources/testdata/glyphs3/StaticComposite.glyphs
resources/testdata/glyphs3/WghtVarComposite.glyphs

The USE_MY_METRICS flag is primarily useful for hinted fonts where composite glyphs should reuse the hinted metrics of one of their components.
Since fontc doesn't support hinting, and the flag can be dangerous in variable fonts where composite and component metrics may differ across masters, we now only set the flag for static fonts to match fontmake's legacy behavior.
We plan to change fontmake to do the same for variable fonts as well.
Fixes https://github.com/googlefonts/fontc/issues/1614

[glyf] Only set USE_MY_METRICS flag for static fonts, not variable fonts

---

fea-rs/src/compile/validate.rs
fea-rs/src/parse/grammar/glyph.rs
fea-rs/test-data/parse-tests/good/notdef_and_null.PARSE_TREE
fea-rs/test-data/parse-tests/good/notdef_and_null.fea

The spec is very clear that '.' is not valid in a glyph name with the sole exception of '.notdef', and that if you are using 'null' as a glyphname you should escape it with a backslash.
Ultimately, though, a bunch of fonts _do_ use '.null' as a glyph name, and it feels pointless to try and update all of these sources.
As a compromise we will now accept these glyph names, but print a warning, as our last concession to principle.

[fea] Allow '.null' as glyph name

---

fontir/src/glyph.rs
fontir/src/orchestration.rs

This matches fonttools, which just ignores references to components that do not exist.

[fontir] Fix crash when component is missing

---

glyphs-reader/src/font.rs

... but there are locations defined for masters. I'm not sure what causes this particular situation but it exists and it seems fine, we can just fall through and the calling code will treat it like any other case where there is an incomplete mapping.
This gives us at least a +1 on crater.

[glyphs] Fix crash when font has no axes

---

fontbe/src/glyphs.rs
fontir/Cargo.toml
fontir/src/glyph.rs
fontir/src/ir.rs

Fixes https://github.com/googlefonts/fontc/issues/1638
Makes VendSans.glyphs among others "output is identical"
```
$ python3 resources/scripts/ttx_diff.py 'https://github.com/ktkm/Vend-Sans?2663f1c7da#sources/VendSans.glyphs'
```
(Will add some tests after lunch)

Handle components with overflowing 2x2 transform exceeding F2Dot14 limits

---

resources/scripts/requirements.txt

https://github.com/googlefonts/ufo2ft/releases/tag/v3.6.5
Gives us at least one +1 with Ruthie.glyphs.
```diff
--- /Users/clupo/oss/fontc/build/default/fontc.glyf.ttx	2025-09-19 14:00:14
+++ /Users/clupo/oss/fontc/build/default/fontmake.glyf.ttx	2025-09-19 14:00:14
@@ -2482,8 +2482,7 @@
</contour>
<contour>
<pt x="293" y="377" on="1"/>
-        <pt x="293" y="376" on="0"/>
-        <pt x="278" y="381" on="0"/>
+        <pt x="293" y="374" on="0"/>
<pt x="268" y="385" on="1"/>
<pt x="247" y="394" on="0"/>
<pt x="242" y="399" on="1"/>
```
The diff was caused by the fact that the decomposition of a component with F2Dot14-overflowing transform was happening at different stages of the build pipeline in fontc vs ufo2ft/fonttools.
I made ufo2ft match fontc, because it makes more sense to …

bump ufo2ft to 3.6.5 in requirements.txt

---

fontir/src/glyph.rs
fontir/src/ir.rs

This also more generally reworks the interpolation code so that it all lives in one place (methods on `GlyphInstance`).

[ir] Also interpolate width/height etc in instances

---

glyphs-reader/src/font.rs
glyphs2fontir/src/source.rs
resources/testdata/glyphs3/CustomParamRedefinition.glyphs

Makes `python3 resources/scripts/ttx_diff.py 'https://github.com/ktkm/Vend-Sans?2663f1c7da#sources/VendSans-Italic.glyphs'` identical
JMM

Match fontmake name nuance

---

glyphs2fontir/src/source.rs
resources/testdata/glyphs3/manual_bracket_layer_and_component_has_one_too.glyphs

We were deciding whether to replace a bracket glyph's component with a an appropriate bracket glyph for that component based on whether the two alternates had equivalent names, instead of whether the replacements applied in equivalent regions.

[glyphs] Fix logic bug around bracket glyph components

---

glyphs-reader/src/font.rs
glyphs-reader/src/plist.rs

Apparently some idiot (pretty sure it was me...) thought that despite randomly quoting bools and ints nobody would ever do that for a float.
Makes `python3 resources/scripts/ttx_diff.py 'https://github.com/SUSE/suse-font?7159afb255#sources/SUSE.glyphs'` identical because `"900"` now parses as an axis location value instead of magically vanishing out from under us.

Parse quoted floats

---

fontir/src/glyph.rs
fontir/src/ir.rs

Just a little bit of cleanup.
I'm mostly opening this to ask a question: what if a glyph has an instance with contours and another instance with components? Is this checked before now?

[ir] Make has_components_and_contours a method

---

fontc/src/lib.rs
fontc/src/workload.rs

Current, the input to the compiler API is `Input` - which admittedly makes sense, given the name. But it means that inputs are restricted to the set of source types enumerated in the `Input` enum. If we have people implementing their own source types (which we do!) then it makes sense for allow compilation of *any* object which `impl Source`. This pushes the creation of a `Source` from an `Input` higher up the pipeline, so that any `Box<dyn Source>` can be compiled.
Also improves the lifetime story of `Workload` to avoid messing with `'static` - `Workload`s only need hang around as long as the `Source`s that they are compiling.

Compile anything which implements Source
