- ir/src/ir.rs
- ir/src/lib.rs
- ufo2ir/Cargo.toml
- ufo2ir/src/error.rs
- ufo2ir/src/lib.rs
- ufo2ir/src/toir.rs
- ufo2ir/testdata/wght_var.designspace
Starting to rough in some of the patterns for ufo2ir. We are as yet somewhat far from doing anything useful :)
> Design space axis to IR axis

- ir/Cargo.toml
- ir/src/depgraph.rs
- ir/src/lib.rs
Toys to help figure out when things changed, meant to facilitate incremental compilation.
> Starting on change tracking

- fontir/src/depgraph.rs
Allows us to model dependencies between files. May need to become pattern-based. Baby steps.
> Add the ability to consider A changed if B changes.

- resources/testdata/WghtVar-Bold.ufo/fontinfo.plist
- resources/testdata/WghtVar-Bold.ufo/glyphs/bar.glif
- resources/testdata/WghtVar-Bold.ufo/glyphs/contents.plist
- resources/testdata/WghtVar-Bold.ufo/metainfo.plist
- resources/testdata/WghtVar-Regular.ufo/fontinfo.plist
- resources/testdata/WghtVar-Regular.ufo/glyphs/bar.glif
- resources/testdata/WghtVar-Regular.ufo/glyphs/contents.plist
- resources/testdata/WghtVar-Regular.ufo/metainfo.plist
- resources/testdata/wght_var.designspace
This sort of sample is helpful to several packages (ex ufo to ir *and* fontc) so I put it in a global resources/testdata.
Originally created for #4.
Ok2merge.
> Add a very stripped down sample of a designspace to use in fontc tests

- README.md
- fontc/Cargo.toml
- fontc/src/error.rs
- fontc/src/main.rs
- fontir/Cargo.toml
- fontir/src/error.rs
- fontir/src/serde.rs
- fontir/src/source.rs
- ufo2fontir/Cargo.toml
- ufo2fontir/src/source.rs
> Rough in parallel designspace glyph to IR processing

- resources/testdata/WghtVar.glyphs
Has a hyphen and an explanation mark that vary on wght from 400 to 700. Original "artwork."
> A .glyphs VF for testing

- fontc/src/main.rs
- fontir/src/error.rs
- fontir/src/source.rs
- fontir/src/stateset.rs
- glyphs2fontir/src/source.rs
- ufo2fontir/src/source.rs
For now don't do anything meaningful with them.
NOTE: setup to target something other than main. @cmyr thought that once the prior PR in the chain (#21) merges this might auto-redirect to main so... lets find out.
> Find the glyphs in a .glyphs and sketch out wiring to process them

- fontc/Cargo.toml
- fontc/src/error.rs
- fontc/src/main.rs
- fontir/Cargo.toml
- fontir/src/ir.rs
- fontir/src/serde.rs
- fontir/src/source.rs
- fontir/src/stateset.rs
> replace toml-rs with serde_yaml

- ufo2fontir/Cargo.toml
> Use a release of Norad again

- fontir/Cargo.toml
- fontir/src/error.rs
- fontir/src/ir.rs
- fontir/src/orchestration.rs
- ufo2fontir/Cargo.toml
- ufo2fontir/src/error.rs
- ufo2fontir/src/source.rs
- ufo2fontir/src/toir.rs
reworking of #4 on top of latest changes
> Start emitting IR for UFO glifs

- fontir/src/lib.rs
- fontir/src/piecewise_linear_map.rs
Meant for us in addressing #22
> Add a piecewise linear map based on the python version

- fontir/Cargo.toml
- fontir/src/ir.rs
- fontir/src/serde.rs
- glyphs2fontir/Cargo.toml
- glyphs2fontir/src/source.rs
- ufo2fontir/Cargo.toml
- ufo2fontir/src/source.rs
> Use IndexSet<String> for glyph order

- fontir/src/coords.rs
- glyphs2fontir/src/source.rs
- glyphs2fontir/src/toir.rs
- ufo2fontir/src/source.rs
- ufo2fontir/src/toir.rs
> Make Location a type so it can have impl's

- fontc/src/main.rs
> Make it possible to change the build dir

- fontc/Cargo.toml
- fontc/src/error.rs
- fontc/src/main.rs
- fontir/src/orchestration.rs
- fontir/src/source.rs
- glyphs2fontir/src/source.rs
- ufo2fontir/src/source.rs
Trying to get from the PoC in #26 to a more realistic implementation. Closes #26.
As ever naming is the hardest part. At time of writing "work" is an executable unit and "job" is that plus metadata such as what must happen before this job runs.
> First pass at executing job graph

- resources/testdata/Static-Regular.ufo/features.fea
- resources/testdata/Static-Regular.ufo/fontinfo.plist
- resources/testdata/Static-Regular.ufo/glyphs/bar.glif
- resources/testdata/Static-Regular.ufo/glyphs/contents.plist
- resources/testdata/Static-Regular.ufo/glyphs/plus.glif
- resources/testdata/Static-Regular.ufo/lib.plist
- resources/testdata/Static-Regular.ufo/metainfo.plist
- resources/testdata/static.designspace
Intended for use testing feature compilation (#73). Split out from #76.
> Add a simple test ufo+ds that has features

- fontbe/src/error.rs
- fontbe/src/features.rs
- fontbe/src/lib.rs
- fontc/src/main.rs
- fontir/src/error.rs
- fontir/src/ir.rs
- fontir/src/orchestration.rs
- fontir/src/paths.rs
- fontir/src/serde.rs
- fontir/src/source.rs
- glyphs2fontir/src/source.rs
- ufo2fontir/src/source.rs
Baby steps.
Final stage of #76 broken into smaller parts.
Fixes https://github.com/googlefonts/fontmake-rs/issues/73
Along the way fixed https://github.com/googlefonts/fontmake-rs/issues/45.
> Build fea files in ufo+ds if identical across masters

- fontir/Cargo.toml
- fontir/src/ir.rs
- glyphs-reader/Cargo.toml
- glyphs-reader/src/font.rs
- glyphs2fontir/src/source.rs
- glyphs2fontir/src/toir.rs
- ufo2fontir/Cargo.toml
- ufo2fontir/src/toir.rs
Minimize reinvention of wheel by using kurbo for transform and point.
Builds on #98. Fixes #100. Step toward #99.
> Use Kurbo's Point and Affine types

- fontir/src/ir.rs
- ufo2fontir/src/toir.rs
Try to avoid setting off debug_assert's in BezPath :)
I mistakenly assumed a BezPath with a move would not be empty but it (correctly) is. Correct our interrogation of the BezPath.
Smoke test UFOs love to open with a curve and close with dangling offcurve; support that. 
https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#point-types suggests more variants than I've supported thus far should work. qcurve is also unimplemented. Baby steps.
> Update path handling based on smoke test

- fontir/src/ir.rs
> Fill in qcurve

- fontbe/src/orchestration.rs
- fontc/src/main.rs
- fontdrasil/src/orchestration.rs
- fontir/src/orchestration.rs
- glyphs-reader/src/font.rs
- glyphs-reader/src/plist.rs
- glyphs2fontir/src/source.rs
- ufo2fontir/src/source.rs
- ufo2fontir/src/toir.rs
Discovered in preparing another PR that clippy is unhappy with us. Ran `clippy --fix` (vast majority of changes), manually removed an unnecessary lifetime, and ran `cargo fmt`.
Just merge.
> Make clippy happy @ 1.67

- fontc/src/main.rs
- fontir/src/stateset.rs
- glyphs-reader/src/font.rs
- glyphs-reader/src/plist.rs
> Forgive me oh wise and powerful clippy

- README.md
> Very sophisticated instructions

- fontbe/src/cmap.rs
- fontbe/src/error.rs
- fontbe/src/lib.rs
- fontbe/src/orchestration.rs
- fontbe/src/paths.rs
- fontbe/src/post.rs
- fontc/src/main.rs
No tmeant to be correct, merely to tick the box for #138
> Emit mvp post

- fontbe/Cargo.toml
- fontbe/src/hmtx.rs
> Properly round advances when building hmtx

- fontbe/src/font.rs
- fontbe/src/hmtx.rs
- fontbe/src/lib.rs
- fontbe/src/orchestration.rs
- fontbe/src/paths.rs
- fontc/src/main.rs
If you compile a font and try to ttx it sadly it blows up because we don't have maxp yet. Soon!
I would like to merge this and then grow the set of tables over the next couple of PRs as we drive towards #138.
> Assemble final font

- fontbe/src/glyphs.rs
- fontc/src/main.rs
I'm confident this improves the situation. I'm not sure it can be said to finish the job. Please read #152 and tell me your thoughts.
Helps with #152.
Just merge.
> Improve composite glyf bbox computation

- fontbe/src/font.rs
- fontbe/src/lib.rs
- fontbe/src/maxp.rs
- fontbe/src/orchestration.rs
- fontbe/src/paths.rs
- fontc/src/main.rs
> Create the minimal maxp for a TrueType outlines font

- fontc/src/args.rs
- fontc/src/lib.rs
- fontc/src/main.rs
No functional change, just doing some cleanup and trying to get up to speed on these crates.
> [fontc] move Args to args module

- fontc/src/args.rs
- fontc/src/main.rs
A little more cleanup.
(just merge me)
> [fontc] Replace test_args with Args::for_test

- fontc/src/config.rs
This costs us an extra allocation per init, in exchange for a slightly simpler API.
This also modifies one of the tests in a way that I think leaves it functionally unchanged.
> [fontc] Recompute config path as needed

- fontc/src/change_detector.rs
- fontc/src/lib.rs
- fontc/src/main.rs
No functional change, although I did need to add a bunch of getters in order to expose stuff that was previously accessed directly.
> [fontc] Move ChangeDetector into change_detector.rs

- fontc/src/lib.rs
- fontc/src/workload.rs
This is no functional change, although I did move some of the code related to testing into a method, Workload::run_for_test; this saved me needing to make a bunch of the fields on Workload visible.
> [fontc] Add workload module

- fontbe/src/features.rs
- fontbe/src/orchestration.rs
- fontc/src/work.rs
- fontc/src/workload.rs
- fontir/src/coords.rs
- fontir/src/ir.rs
- fontir/src/orchestration.rs
- fontir/src/piecewise_linear_map.rs
- fontir/src/stateset.rs
- fontir/src/variations.rs
- glyphs2fontir/src/source.rs
- ufo2fontir/src/source.rs
> Combine identical impl blocks

- resources/testdata/glyphs2/WghtVar.glyphs
- resources/testdata/glyphs3/WghtVar.glyphs
To help validate glyphs2fontir name support.
Loaded and saved file in Glyphs for v3 and v2.
Just merge me.
> Add 'name' values to WghtVar.glyphs

- resources/testdata/glyphs2/TheBestNames.glyphs
- resources/testdata/glyphs3/TheBestNames.glyphs
Even more .glyphs name samples.
> Set all the names I could find

- fontbe/src/font.rs
- fontc/src/lib.rs
Contributes to #138 
Just merge.
> Don't lose post

- ufo2fontir/src/source.rs
No functional change, but in reviewing an earlier PR I noticed that this was calling `collect` three different times and I wondered if there was a reasonable alternative.
Conclusion: There is a semi-reasonable alternative?
> [ufo2fontir] Codegolf computing UPM

- .github/workflows/rust.yml
Numerous copy/paste errors later, fixes #128. JMM.
> Update CI to match https://github.com/googlefonts/fontations/pull/254

- fontbe/src/hmetrics.rs
- fontbe/src/os2.rs
- fontc/src/change_detector.rs
- fontc/src/lib.rs
- fontc/src/workload.rs
- fontir/src/ir.rs
- fontir/src/orchestration.rs
- fontir/src/paths.rs
- fontir/src/serde.rs
- fontir/src/source.rs
- glyphs2fontir/src/source.rs
- ufo2fontir/src/source.rs
- ufo2fontir/src/toir.rs
Fixes #205. So far only the metrics at the default location are used. Baby steps. JMM if seems sane.
> Use a loc:metrics map

- fontbe/src/fvar.rs
- fontir/src/error.rs
- fontir/src/ir.rs
- fontir/src/serde.rs
- glyphs2fontir/src/source.rs
- glyphs2fontir/src/toir.rs
- ufo2fontir/src/source.rs
- ufo2fontir/src/toir.rs
> Use font_types definition of Tag for IR

- fontbe/src/avar.rs
> Fix bad merge

- fontbe/src/font.rs
- fontbe/src/fvar.rs
- fontir/src/ir.rs
Fix bug identified in https://github.com/googlefonts/fontmake-rs/pull/211#discussion_r1150527035.
> Fix fvar filtering bug

- fontbe/Cargo.toml
- fontir/Cargo.toml
- glyphs-reader/Cargo.toml
- glyphs2fontir/Cargo.toml
- ufo2fontir/Cargo.toml
Fixes #217.
Fix is in https://github.com/linebender/kurbo/pull/254.
JMM.
> Use kurbo 0.9.2 to get fix to cubic to quadratic

- fontir/src/ir.rs
- fontir/src/variations.rs
- resources/testdata/WghtVar-Bold.ufo/fontinfo.plist
- resources/testdata/WghtVar-Regular.ufo/fontinfo.plist
- ufo2fontir/src/source.rs
> Expose and fix bug where metrics would capture for glyph-only layers

- resources/testdata/Mov-Max-X.ufo/fontinfo.plist
- resources/testdata/Mov-Max-X.ufo/glyphs/contents.plist
- resources/testdata/Mov-Max-X.ufo/glyphs/period.glif
- resources/testdata/Mov-Max-X.ufo/glyphs/space.glif
- resources/testdata/Mov-Max-X.ufo/layercontents.plist
- resources/testdata/Mov-Max-X.ufo/metainfo.plist
- resources/testdata/Mov-Max-Y.ufo/fontinfo.plist
- resources/testdata/Mov-Max-Y.ufo/glyphs/contents.plist
- resources/testdata/Mov-Max-Y.ufo/glyphs/period.glif
- resources/testdata/Mov-Max-Y.ufo/glyphs/space.glif
- resources/testdata/Mov-Max-Y.ufo/layercontents.plist
- resources/testdata/Mov-Max-Y.ufo/metainfo.plist
- resources/testdata/Mov-Origin.ufo/fontinfo.plist
- resources/testdata/Mov-Origin.ufo/glyphs/contents.plist
- resources/testdata/Mov-Origin.ufo/glyphs/period.glif
- resources/testdata/Mov-Origin.ufo/glyphs/space.glif
- resources/testdata/Mov-Origin.ufo/layercontents.plist
- resources/testdata/Mov-Origin.ufo/lib.plist
- resources/testdata/Mov-Origin.ufo/metainfo.plist
- resources/testdata/mov_xy.designspace
> Add a test .designspace with two axes, one to move X and the other Y

- fontbe/Cargo.toml
- fontbe/src/avar.rs
- fontbe/src/font.rs
- fontbe/src/fvar.rs
- fontbe/src/glyphs.rs
- fontbe/src/gvar.rs
- fontc/Cargo.toml
- fontir/Cargo.toml
- fontir/src/coords.rs
- fontir/src/error.rs
- fontir/src/ir.rs
- fontir/src/serde.rs
- fontir/src/variations.rs
- ufo2fontir/Cargo.toml
- ufo2fontir/src/source.rs
Produce a gvar table that doesn't make FontTools angry.
Builds on #236.
> Compile a gvar for Texturina that ttx accepts

- fontbe/Cargo.toml
- fontc/Cargo.toml
- fontir/Cargo.toml
- glyphs-reader/Cargo.toml
- glyphs2fontir/Cargo.toml
- ufo2fontir/Cargo.toml
Picks up the fix in https://github.com/linebender/kurbo/pull/266
Fixes #255
> Move to kurbo 0.9.3 to fix compilation failure

- fontbe/src/font.rs
- fontbe/src/glyphs.rs
- fontbe/src/head.rs
- fontbe/src/orchestration.rs
- fontbe/src/paths.rs
- fontc/src/lib.rs
- fontc/src/workload.rs
- fontdrasil/src/orchestration.rs
It's very handy to know from the loca data what the format is so (edit) added a new context slot just for that.
> Pick short or long loca

- glyphs-reader/src/font.rs
Per https://github.com/googlefonts/fontmake-rs/pull/252#discussion_r1170197713
JMM
> Correct comment

- fontbe/src/avar.rs
- fontbe/src/font.rs
- fontbe/src/orchestration.rs
- fontc/src/change_detector.rs
- fontc/src/config.rs
- fontc/src/lib.rs
- fontc/src/main.rs
- fontc/src/workload.rs
Add a test for compile w/o emitting ir, fix resulting problems. Fixes #224. Aside: discovered https://github.com/googlefonts/fontations/pull/367 along the way.
> Obey emit_ir more closely

- fontc/src/args.rs
- fontir/src/glyph.rs
- fontir/src/orchestration.rs
- glyphs2fontir/src/source.rs
- ufo2fontir/src/source.rs
This makes emit ir default on so I had to turn it off for tests where I don't want that.
> Make arg and flag defaults match

- glyphs-reader/plist_derive/src/attrs.rs
- glyphs-reader/plist_derive/src/lib.rs
- glyphs-reader/src/font.rs
- glyphs-reader/src/to_plist.rs
I had a small block of time so I decided to take a look at the fromplist macro, and fix #257.
I also tried to add a bit more error support. This macro is pretty hacky and I started trying to rationalize it but that is a project beyond the scope of my afternoon, so I'm backing away. There's definitely a whole whack of unnecessary panicking in there, though.
I've updated some of the code to use the new macro attribute, but i'm not totally sure where all we would want it; I figure after this gets merged y'all can fix up the code to take advantage of it as needed.
> From plist fixups

- Cargo.toml
- fontbe/src/error.rs
- fontbe/src/gvar.rs
- fontbe/src/metrics_and_limits.rs
> Update to latest fea-rs, write-fonts

- Cargo.toml
- fontbe/src/orchestration.rs
- fontir/src/ir.rs
- fontir/src/serde.rs
Fixes #278. Includes minimal changes to accomodate updated signature for iup. JMM.
> Use font-types serde support

- fontbe/src/error.rs
- fontbe/src/fvar.rs
- fontbe/src/glyphs.rs
- fontbe/src/gvar.rs
- fontbe/src/lib.rs
- fontbe/src/orchestration.rs
- fontbe/src/test_util.rs
- fontc/src/lib.rs
- fontc/src/workload.rs
- fontir/src/variations.rs
> Fire IUP optimization per glyph

- resources/scripts/ttx_diff.py
> Support ttx_diff.py run on a .designspace

- fontbe/src/os2.rs
After this and the PRs it is built on OS/2 for Oswald differs on {usLastCharIndex, usBreakChar, usMaxContext}
> Set codepage range bits in OS/2

- resources/scripts/ttx_diff.py
> Didn't rename dir in ttx_dif.py

- fontir/src/stateset.rs
- glyphs2fontir/src/source.rs
> Appease clippy

- fontbe/src/glyphs.rs
Initially I thought of modifying fonttools to match fontc and make sure USE_MY_METRICS flag is only set on the VF when all the masters have it set (https://github.com/fonttools/fonttools/pull/3163), but then I changed my mind, because it doesn't matter what the non default masters do, and in fact I wasn't able to see any differences whatsoever whether that flag was set only when all masters would set it (fontc's current logic), vs the flag being set when the default master has it set (ufo2ft's logic).
Note that we only ever set that flag automatically on the first component whose base glyph's advance is _the same_ as the composite glyph that references it, so whether it is set or not doesn't actually produce any visual differences, but probably saves a fraction of a microsecond as …
> only test for use_my_metrics component flags for the default instance

- Cargo.toml
- fontbe/src/fvar.rs
> Update fontations crates + fea-rs

- fontbe/src/fvar.rs
- fontbe/src/orchestration.rs
- fontc/src/lib.rs
- fontir/src/coords.rs
- fontir/src/error.rs
- fontir/src/glyph.rs
- fontir/src/ir.rs
- fontir/src/variations.rs
- glyphs2fontir/src/source.rs
- glyphs2fontir/src/toir.rs
- ufo2fontir/src/source.rs
- ufo2fontir/src/toir.rs
Name matches how some sources do it but Tag feels much more natural so translate to tag more aggressively.
IMHO #347 makes more sense after this. I think this is a good change regardless of whether we proceed with #347.
JMM.
> Use tag instead of name in Location

- Cargo.toml
- ufo2fontir/Cargo.toml
fixes some designspace and FEA parsing issues.
> Bump norad and fea-rs

- fontir/src/variations.rs
trying to really understand what's going on here, so might as well commit my little fixups.
JMM
> [fontir] Minor fixups in variations.rs

- fontbe/src/features.rs
- fontbe/src/glyphs.rs
- fontbe/src/metrics_and_limits.rs
- fontc/src/work.rs
- fontc/src/workload.rs
- fontdrasil/src/orchestration.rs
Building on #356, let work tell us if it completes things other than itself (e.g. glyf completes loca)
JMM if happy
> Housekeeping: Let Work tell us what ids it completed

- Cargo.toml
> Update fontations & fea-rs

- resources/scripts/time_build.py
Hoping to save myself copy/pasting the same bash commands over and over
JMM
> Script that helps compare build time across branches

- Cargo.toml
Fixes issue with IUP delta optimization https://github.com/googlefonts/fontations/issues/571
> bump write-fonts to 0.14.1

- Cargo.toml
- fontbe/src/features.rs
- fontir/src/variations.rs
And fix bug that revealed where the ordering required by VariationRegion was not being enforced.
DO NOT SUBMIT until using a release that contains https://github.com/cmyr/fea-rs/pull/222; should be fine to review tho. EDIT: updated to fea-rs 0.15.0.
> Update to fea-rs floating like a butterfly

- fontbe/src/avar.rs
- fontbe/src/glyphs.rs
- fontc/src/lib.rs
- fontc/src/workload.rs
- fontir/src/ir.rs
- fontir/src/variations.rs
- glyphs-reader/plist_derive/src/lib.rs
- glyphs-reader/src/font.rs
- glyphs2fontir/src/source.rs
- ufo2fontir/src/source.rs
TIL, via #418, that "merge when ready" merges even if you fail CI.
Fix all the issues from that, and a bunch of new ones courtesy of a rust update.
JMM
> Fix clippy, format, etc after rustup

- fontir/src/serde.rs
> Use pub(crate) in fontir/src/serde.rs

- fontbe/src/avar.rs
Add test to expose bug. Fix it. Done f2f w/ @anthrotype @ TPAC. Bug impacts GS.
> avar was wrong if default was min or max value for the axis

- Cargo.toml
This gets us building noto sans gujarati again. (JMM)
> Bump fea-rs to 0.16.1

- resources/scripts/requirements.txt
Fixes https://github.com/googlefonts/fontc/issues/442
JMM
> add requirements.txt for ttx_diff.py

- README.md
Try to be friendlier to people new to both fontc and Rust
> Tweak root readme

- fontir/src/glyph.rs
- fontir/src/ir.rs
As suggested by #458.
```shell
$ rm -rf build/ perf.data && cargo flamegraph -p fontc --  --source ../OswaldFont/sources/Oswald.glyphs --emit-ir false --emit-timing
$ perf script | ../FlameGraph/stackcollapse-perf.pl | grep GlyphOrderWork | ../FlameGraph/flamegraph.pl > glyphorder-flames.svg
```
Causes has_consistent_2x2_transforms to vanish from a flamegraph zoomed in on GlyphOrder; this is before, after just doesn't have that section:
In the `--emit-timing` thread view glyphorder goes from 2.34% to 1.35% (subject to noise, but consistently less)
> Move consistent transform computation to glyph and avoid allocation

- Cargo.toml
- fontbe/src/error.rs
- fontbe/src/glyphs.rs
- fontbe/src/gvar.rs
- fontbe/src/orchestration.rs
- ufo2fontir/Cargo.toml
This updates our deps (mostly fontations/fea-rs, but also a few other things that have version bumps) and makes the minimal set of changes to get us compiling again. There is more work to do to improve our gvar compilation, but that will happen in follow-up work.
> Update for new delta IUP API

- fontc/src/args.rs
- fontc/src/change_detector.rs
- fontc/src/lib.rs
Fixes https://github.com/googlefonts/fontc/issues/477
JMM
> skip feature IR job if --compile-features=false

- fea-rs/src/compile/compiler.rs
- fea-rs/src/token_tree.rs
- fea-rs/src/token_tree/cursor.rs
- fea-rs/src/token_tree/rewrite.rs
- fea-rs/src/token_tree/stack.rs
- resources/scripts/check_no_println.sh
- two of these were debug helpers, which I can comment out
- one of these is (imo) legitimate use, reporting warnings to the user, and I've added it to the allowlist
> [ci] Address remaining eprintln statements in fea-rs

- fontbe/src/features.rs
A quick patch for #492, computing and storing the deltas.
> Compute and store deltas for variable mark anchors

- fontc/src/change_detector.rs
- fontir/src/ir.rs
- fontir/src/serde.rs
- glyphs-reader/src/font.rs
- ufo2fontir/src/source.rs
- ufo2fontir/src/toir.rs
Don't do anything useful with it yet. Step toward #532.
> Make the export status of a glyph available

- fontc/src/lib.rs
- fontir/src/glyph.rs
- fontir/src/ir.rs
- glyphs2fontir/src/source.rs
Helps with #532. We are a few tests short of saying fixed, for example we don't verify the effects on layout noted in the issue.
> Do not retain glyphs we should not retain

- fontc/src/timing.rs
Allows mouseover for more information
> Title for timing elements

- glyphs-reader/src/font.rs
> [glyphs-reader] fix a typo

- resources/scripts/ttx_diff.py
Totally unnecessary, but I want to have this file up to date so that an upcoming patch only includes my actual changes.
JMM
> [ttx_diff] Run black formatter

- resources/scripts/ttx_diff.py
I discovered this while trying to copy paste the markkern.txt file names to be able to diff them
JMM
> [ttx_diff] fix minor typo

- .github/workflows/gsbuild.yml
Addresses https://github.com/googlefonts/fontc/issues/582#issuecomment-1816811638 and https://github.com/googlefonts/fontc/issues/582#issuecomment-1817191570
> [ci] Add OTS tests on GS builds

- fontbe/README.md
- fontc/README.md
- fontdrasil/README.md
- fontir/README.md
- glyphs-reader/README.md
- glyphs2fontir/README.md
- layout-normalizer/README.md
- ufo2fontir/README.md
> Note what each crate is for in its readme

- fontbe/src/avar.rs
based on #605, which should go in first.
- closes #591
> Use is identity

- fontc/src/change_detector.rs
- fontdrasil/src/types.rs
- ufo2fontir/src/source.rs
This is a pair of commits split out of my kerning work that make it easier to work with the `GlyphName` type.
JMM
> Small GlyphName improvements

- layout-normalizer/src/gpos.rs
Verified manually, we are now printing something much more reasonable for the (very useful!) examples in #641.
- fixes #641
> [ttx_diff] Actually handle extension lookups

- layout-normalizer/src/gpos.rs
- layout-normalizer/src/gpos/marks.rs
- layout-normalizer/src/gpos/pairpos.rs
> [ttx_diff] Split up normalizer gpos module

- layout-normalizer/src/gpos/marks.rs
VariationStoreBuilder::new now wants a region_count
JMM
> layout-normalizer: fix clippy, VariationStoreBuilder::new(0)

- fea-rs/src/token_tree/rewrite.rs
- fontbe/src/marks.rs
- layout-normalizer/src/common.rs
- layout-normalizer/src/gpos/marks.rs
> make clippy happy again

- resources/scripts/fea_ci_requirements.txt
Hoping that this fixes a dependabot warning I was seeing in the console.
> [chore] Update fea-rs tests fonttools version

- Cargo.toml
- fontbe/src/glyphs.rs
- fontbe/src/metrics_and_limits.rs
- fontbe/src/orchestration.rs
- This added an 'empty glyph' variant, which actually seems like less of a simplification here than I'd hoped.
JMM
> Update to new write-fonts version

- fea-rs/src/token_tree.rs
This was used more at some point in the past but now it's just dead code.
JMM
> [fea-rs] Remove 'rel_pos' from Node

- fontc/src/lib.rs
- fontra2fontir/Cargo.toml
- fontra2fontir/src/source.rs
- resources/testdata/fontra/2glyphs.fontra/font-data.json
Trying to sneak things between meetings :)
JMM
> Serde type for the fontra font-data.json file

- fontbe/src/features.rs
- fontir/src/ir.rs
- fontir/src/orchestration.rs
- fontir/src/source.rs
- glyphs2fontir/src/toir.rs
- ufo2fontir/src/source.rs
To differentiate it from the FeaturesAst we will be storing later.
> [fontir] Rename Features -> FeaturesSrc

- fontbe/src/paths.rs
I forgot to push this commit to #695 before I merged.
JMM
> [fontbe] Fix path for FeaturesAst

- fontir/src/error.rs
- fontir/src/ir.rs
- fontra2fontir/src/fontra.rs
- fontra2fontir/src/lib.rs
- fontra2fontir/src/source.rs
- fontra2fontir/src/toir.rs
- resources/testdata/fontra/minimal.fontra/glyphs/%2Enotdef.json
https://codepen.io/rs42/pen/qBvoaLy shows the first outlines ever loaded from fontra by this code.
We have yet to reach the interesting (varc) bits. Baby steps.
> Parse Fontra glyphs as far as contours

- resources/scripts/requirements.txt
https://github.com/googlefonts/fontmake/releases/tag/v3.8.0
> use the latest fontmake 3.8.0

- layout-normalizer/src/gpos.rs
This was sitting around in a stash from a while ago, but now that this API has been adopted this is a nice improvement.
JMM
> [ttx_diff] Use new lookup API in normalizer

- fontc/src/change_detector.rs
- fontc/src/lib.rs
- fontir/src/error.rs
- ufo2fontir/src/source.rs
> Make a UFO-only compile run through

- fontc/src/lib.rs
We recently removed the old scale module. Updating here now so this doesn't cause unnecessary breakage when we publish.
JMM
> [fontc] update skrifa test to new outline API

- fontbe/src/features/kern.rs
> Remove missed dbg statement

- Cargo.toml
- fontbe/src/cmap.rs
- fontbe/src/error.rs
- fontir/src/glyph.rs
Fixes https://github.com/googlefonts/fontc/issues/457
> Update to write-fonts 0.25.0, handling the new cmap conflict

- fea-rs/src/common.rs
- fea-rs/src/common/glyph_map.rs
- fea-rs/src/compile.rs
- fea-rs/src/lib.rs
- fea-rs/src/parse/grammar/glyph.rs
- fea-rs/src/tests/compile.rs
- fontbe/src/features.rs
- fontbe/src/features/kern.rs
- fontbe/src/features/marks.rs
> remove the GlyphName defined in fea-rs, and use the one in fontdrasil

- fontbe/src/head.rs
For #327 ,working for just UFO
> set head.macStyle from OS2 selection_flags

- glyphs-reader/src/font.rs
- glyphs2fontir/src/source.rs
Previously we were generating a separate cmap-like thing in the glyphs module, which was then used to set the codepoints in the ir::Glyph. This just keeps the codepoints in the glyphs Glyph, which will be nice because it means that all the things that we use to determine the glyph category will be in one place.
> [glyphs] Store codepoints in glyph struct

- fea-rs/src/compile/lookups/helpers.rs
- fea-rs/src/compile/metrics.rs
- fea-rs/src/util/pretty_diff.rs
- fontbe/src/features/kern.rs
- fontbe/src/glyphs.rs
- fontra2fontir/src/toir.rs
- glyphs2fontir/src/source.rs
- ufo2fontir/src/source.rs
> clippy day

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/feature_writer.rs
- fontbe/src/features.rs
- fontbe/src/features/marks.rs
- fontbe/src/orchestration.rs
This computes and sets the 'mark filtering set' for mark2mark lookups.
> Mark2mark filtering sets/lookupflags

- layout-normalizer/src/args.rs
- layout-normalizer/src/error.rs
- layout-normalizer/src/glyph_names.rs
- layout-normalizer/src/gpos.rs
- layout-normalizer/src/gsub.rs
- layout-normalizer/src/lib.rs
- layout-normalizer/src/main.rs
This is the first step in adapting it to be used in other contexts, like testing.
> [ttx_diff] Split layout-normalizer into bin & lib

- fontbe/src/features.rs
- fontbe/src/features/kern.rs
- fontbe/src/features/marks.rs
This will make it easier for us to test these types independently.
JMM
> [fontbe] Impl FeatureProvider for kern/mark IR types

- fontbe/src/features/marks.rs
This is a funny situation, where for glyphs.app we want to ignore this but when using a UFO source we want to look at it.
based on #797.
> [marks] Add tests for using GDEF block from user FEA

- fontbe/src/features/marks.rs
I am regularly humbled by how hard it is to follow even relatively trivial boolean logic in my head.
This is on #797, which should go in first.
> [marks] Fix bad boolean logic in find_mark_glyphs

- fontir/src/ir.rs
This was an oversight in the initial code, and is necessary for us to correctly generate mark2lig lookups.
> [marks] Parse empty ligature anchors like '_3'

- layout-normalizer/src/glyph_names.rs
This gives us much better names in many cases.
closes #787 
thanks @simoncozens this has already improved my quality of life..
> [ttx_diff] Try getting glyph names from post table

- ufo2fontir/src/source.rs
> [ufo2fontir] fix non-deterministic glyph order when not explicitly provided

- Cargo.toml
- fontbe/src/features/kern.rs
- fontbe/src/features/properties.rs
This wasn't too hard, although it does require us to duplicate a bit of code in a few places and otherwise slightly complicate some impls.
> [fontbe] Get off patched version of icu_properties

- resources/scripts/bump-version.sh
- resources/scripts/rel-common.sh
- resources/scripts/release.sh
These are very minorly adapted from the scripts in fontations.
> Add scripts for managing release process

- fea-rs/test-data/scripts/run_test_case.py
This was useful for me in trying to debug our deviation from fontmake, and I suspect it might be useful again soon.
> [fea-rs] Add script for building a test case via fontmake

- fea-rs/src/compile/lookups/contextual.rs
- keep track of the number of subtables generated by a given format
- account for the cost of additional offsets when formats generate multiple subtables
Noticed we were overlooking this while trying to debug some GSUB differences; it's not the culprit but we might as well try to be correct.
> [fea-rs] Tweak contextual lookup format selection

- fea-rs/test-data/compile-tests/README.md
> [fea-rs] fixup compile-test README

- resources/scripts/ttx_diff.py
This splits the generating of the different objects that we compare (ttx tables and layout_normalizer output) from the printing of them, which is the first step towards not printing them.
There is one little addition: it now prints a % representing the diff ratio when two outputs differ.
----
Thinking about what we'll want for the bulk compiler, I realize maybe it's more significantly different than I had thought at first? Basically I'm wondering if, when we're called from the bulk compiler we shouldn't just return some kind of JSON summary that just lists the tables and their difference ratio, and we shouldn't really bother writing all the individual files to disk, since it's all going to be nuked on the next font anyway?
> [ttx_diff] Initial refactor for machine-readable output

- resources/scripts/ttx_diff.py
My last PR was missing a stash :/
JMM
> [ttx_diff] Unbreak ttx_diff script

- resources/scripts/ttx_diff.py
And other sources that are not files.
> [ttx_diff] Support.ufo and .glyphspackage sources

- fontc_crater/README.md
- fontc_crater/src/args.rs
- fontc_crater/src/main.rs
- fontc_crater/src/ttx_diff_runner.rs
on top of #862.
Basic for now, but a start.
`cargo run -p fontc_crater -- report myjson.json`
> [fontc_crater] Add support for generating text report

- glyphs-reader/src/font.rs
- resources/testdata/glyphs3/custom_param_disable.glyphs
This was causing us to fail to parse 28 inputs in our test set.
> [glyphs] Parse possible 'disabled' flag in custom params

- fontc_crater/src/ttx_diff_runner.rs
This is more useful when deciding what issues to triage.
> [crater] report failures as both/only fontc/only fontmake

- fontc_crater/src/main.rs
A repo can have multiple targets, and we were running all the targets in a given repo sequentially; this isn't a huge problem except that it meant that if a repo containing multiple sources was run near the end (or took a long time) we wouldn't compile those sources in parallel, causing unnecessary delays.
This is particularly annoying for the noto latin/greek/cryillic fonts, because ttx_diff on them can currently take multiple hours, and we were doing them one at a time.
> [crater] run targets in parallel, not repos

- glyphs-reader/src/plist.rs
The ascii plist format has syntax for inline binary data, which our plist lib wasn't parsing. This adds support for parsing that data, which has compiling another 5 sources from our test set.
> [glyphs] Parse plist data blocks

- resources/scripts/ttx_diff.py
This ultimately wasn't the bottleneck, and this implementation wasn't even returning the output of the executed process.
This reverts commit 0b4f66f527bedcbd76e10444c5255a85c265abea.
the actual speedup is in #897
> Revert "[ttx_diff] Run otl-normalizer in parallel"

- fontc_crater/Cargo.toml
- fontc_crater/src/main.rs
- fontc_crater/src/sources.rs
This moved a bunch of code to that repo, so we can delete it here.
> [crater] Update to google-fonts-sources 0.3

- glyphs2fontir/src/source.rs
> glyphs2fontir: add missing 'description' name record nameID=10

- glyphs-reader/src/propagate_anchors.rs
Instead of tracking  `queue, depths, component_buf, waiting_for_components` with both `queue` and `depths` taking capacity for every glyph, track only depths and the set of glyphs whose depth is as yet indeterminate. Spin until no depth is indeterminate or no forward progress is made.
> Try to find glyph depths in a more typical graph traversal style

- fontdrasil/src/types.rs
- glyphs-reader/src/font.rs
- resources/testdata/glyphs3/WdthVar.glyphs
Fixes https://github.com/googlefonts/fontc/issues/919
> Map Glyphs instance width_class to wdth percent scale when loading axis mappings

- fontbe/src/os2.rs
- fontc/src/lib.rs
- fontdrasil/src/types.rs
- fontir/src/ir.rs
> fontbe/os2: set us{Weight,Width}Class to wght/wdth axis defaults

- fontbe/src/head.rs
> Treat minor as # of thousandths so 42 is .042 not .42

- resources/scripts/ttx_diff.py
Since these are handled by layout normalizer.
This keeps the lookup element itself as well as the 'LookupKind', but removes all other children.
> [ttx_diff] Drop kern/mark lookups in GPOS

- fontir/src/variations.rs
> [clippy] Roll the rock back up the hill

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/lookups/contextual.rs
- fea-rs/test-data/compile-tests/mini-latin/good/anon_lookup_flag.fea
- fea-rs/test-data/compile-tests/mini-latin/good/anon_lookup_flag.ttx
Checking lookup kind only will merge anonyms lookups with different lookup flags.
Fixes https://github.com/googlefonts/fontc/issues/952
> [fea-rs] Take lookup flags into account in ensure_current_lookup_type()

- fontc_crater/src/main.rs
Something weird was happening when we ran on the global threadpool, where tasks were not being started as expected when we were nearing the end of the work queue.
I don't really want to try and debug that, but this relatively simple change seems to have fixed the issue.
> [crater] Use manual threadpool to run targets

- fontbe/src/os2.rs
- fontbe/src/os2/max_context.rs
This will (with #959) get us identical for at least one more font.
- closes #961
> [fontbe] Look at GPOS when computing OS/2 usMaxContext

- fontc_crater/src/ci.rs
This lets the ci environment specify a directory (via an env var) that will be reused for checking out fonts between runs.
This saves 10-20 minutes and a bunch of network congestion on each run.
> [crater] Support caching git checkouts in ci

- fontbe/src/features/kern.rs
This moves the logic for aligning kerns for a single instance into a standalone function so we can write tests against just that.
this is preparing another PR. No functional change, JMM
> [kerning] Refactor alignment to be more testable

- otl-normalizer/src/gpos.rs
This was causing normalizer to be non-deterministic in some cases; because we were merging rules without considering the lookup flags, we would preserve the flag of the first rule we encountered, which would depend on the iteration order of the hashmap.
This fixes the underlying issue, by not merging any rules that do not have identical lookup flags.
> [normalizer] Consider lookup flags when merging rules

- otl-normalizer/src/variations.rs
This impl was added some time back.
JMM
> [normalizer] Fix an old TODO

- fontbe/src/features/kern.rs
- fontir/src/ir.rs
Well this was very very annoying to track down, but ultimately straightforward.
> Alignment determinism

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/test-data/compile-tests/mini-latin/good/single_sub_singleton_class.fea
- fea-rs/test-data/compile-tests/mini-latin/good/single_sub_singleton_class.ttx
- fixes #988 
this will get us compiling at least one more font, which is a nice way to make the diff % go up
> [fea-rs] Correctly handle singlesub singleton class

- glyphs-reader/src/plist.rs
This occurs in at least one real font[1], and trailing commas are supported by the macOS parser, which is a reasonable reference.
1: https://github.com/googlefonts/grapenuts/blob/main/sources/GrapeNuts.glyphs
> [glyphs] Parse arrays with trailing commas

- fontc_crater/src/ttx_diff_runner.rs
This reduces the timeout for ttx_diff to 20 minutes, and includes the exit code or signal number where possible when we a run exits unexpectedly.
JMM
> [crater] Reduce timeout, improve error reporting

- glyphs-reader/src/font.rs
applying @cmyr review comments after #1014 was hastily merged
JMM
> follow up from #1014 to avoid a couple of allocations

- fontc/Cargo.toml
- fontc/build.rs
See https://github.com/rustyhorde/vergen/blob/master/MIGRATING_v8_to_v9.md
JMM
> [chore] Update vergen

- fontbe/src/metrics_and_limits.rs
- fontc/src/lib.rs
- resources/testdata/glyphs3/PixelRef.glyphs
Fixes #1022
[soft-type-jersey/sources/Jersey25.glyphs](https://github.com/scfried/soft-type-jersey), [mavenproFont/sources/MavenPro.glyphs](https://github.com/googlefonts/mavenproFont), [soft-type-jersey/sources/Jersey25.glyphs](https://github.com/scfried/soft-type-jersey) and hopefully more now report identical locally.
JMM if happy
> Expose and fix bug when counting limits of repeatedly referenced components

- glyphs2fontir/src/source.rs
FIxes #1024. [soft-type-yarndings/sources/Yarndings12Charted.glyphs](https://github.com/scfried/soft-type-yarndings) is now deemed identical locally.
JMM if happy.
> Found another hidden cache of defaults for .glyphs

- fontc_crater/src/ci/html.rs
This turns the various 'error' columns in the last row of results (the most recent run) into a link that jumps you to the relevant section of the detailed report.
> [crater] Link to relevant errors for last run

- glyphs-reader/src/font.rs
- glyphs2fontir/src/source.rs
- resources/testdata/glyphs3/WghtVarPanose.glyphs
* Fixes #1031
* Makes [are-you-serious/sources/AreYouSerious.glyphs](https://github.com/googlefonts/are-you-serious) ttx_diff identical
JMM if happy.
> Support panose in .glyphs customParameters

- resources/testdata/designspace_from_glyphs/IntermediateLayer-Black.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/IntermediateLayer-Regular.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/SlantedFont-Italic.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/SlantedFont-Regular.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/WghtVar-Bold.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/WghtVar-Regular.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/WghtVar_Anchors-Bold.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/WghtVar_Anchors-Regular.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Bold.ufo/glyphs/manual-component.glif
- resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Bold.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Regular.ufo/glyphs/manual-component.glif
- resources/testdata/designspace_from_glyphs/WghtVar_NoExport-Regular.ufo/lib.plist
No changes, just hoping to reduce noise from #1035. JMM.
> Ran resources/testdata/designspace_from_glyphs/make_designspace.sh

- resources/scripts/ttx_diff.py
> [ttx_diff] unbreak ttx_diff

- README.md
> Tweak the flamegraph sample command

- README.md
[rendered](https://github.com/googlefonts/fontc/tree/rsheeter-patch-3?tab=readme-ov-file#running-samply)
JMM
> Add an example of usage of samply

- fontc_crater/src/ci.rs
... even if the fontc rev hasn't.
> [crater] Rerun if inputs have changed

- fontc_crater/src/ci.rs
- fontc_crater/src/main.rs
- fontc_crater/src/ttx_diff_runner.rs
- resources/scripts/ttx_diff.py
Currently each invocation of ttx_diff attempts to `cargo build` these targets. This is a problem if you want to run crater locally and also continue working on fontc, since ttx_diff will attempt to recompile any saved changes.
It is also a possible source of various intermittent 'other' errors including some very clear instances where the binaries are not in the target dir as expected.
this also removes use of `timeout` in ci; we now timeout otl-normalizer in the ttx_diff script, and I don't think we need two timeouts (but if it turns out we do, we can put it back)
> [crater] Prebuild fontc & normalizer

- fontc_crater/src/ci/html.rs
This was only being shown for runs that produced a diff.
JMM
> [crater] Add repro links to failures too

- fontbe/src/os2/max_context.rs
Add comments with references like the one @anthrotype noted in https://github.com/googlefonts/fontc/pull/1096#issuecomment-2460423329
JMM
> Add citation Cosimo noted

- fontbe/src/glyphs.rs
Fixes #1078
ufo2ft determines this metric after most of `glyf` is already compiled, which means that component positions will already have been rounded, with negligible offsets discarded. We can match this behaviour by rounding the x-offset _before_ comparing to the identity transform.
After this change, fontc matches fontmake's behaviour for Moirai, in which /Ugrave's /U component has a 0.004 x-offset that is rounded away during compilation.
<sub>Note: this is a personal contribution independent of my employer, and so I've submitted from a fork under my personal profile and email to make this distinction</sub>
> Allow USE_MY_METRICS when dx is negligible, matching ufo2ft

- Cargo.toml
This brings in the new cmap 4 implementation in write-fonts.
> Update fontations crates

- resources/testdata/DoubleComponentError/Bold.ufo/glyphs/contents.plist
- resources/testdata/DoubleComponentError/Bold.ufo/glyphs/inner.glif
- resources/testdata/DoubleComponentError/Bold.ufo/glyphs/outer.glif
- resources/testdata/DoubleComponentError/Bold.ufo/layercontents.plist
- resources/testdata/DoubleComponentError/Bold.ufo/metainfo.plist
- resources/testdata/DoubleComponentError/OuterInner.designspace
- resources/testdata/DoubleComponentError/Regular.ufo/glyphs/contents.plist
- resources/testdata/DoubleComponentError/Regular.ufo/glyphs/inner.glif
- resources/testdata/DoubleComponentError/Regular.ufo/glyphs/outer.glif
- resources/testdata/DoubleComponentError/Regular.ufo/layercontents.plist
- resources/testdata/DoubleComponentError/Regular.ufo/metainfo.plist
Makes the fix a tidier diff to do this on it's own
JMM
> Add test file for #1115

- fea-lsp/src/document.rs
- fea-rs/benches/parsing.rs
- fea-rs/src/bin/highlight.rs
- fea-rs/src/diagnostic.rs
- fea-rs/src/parse.rs
- fea-rs/src/token_tree.rs
- fea-rs/src/token_tree/cursor.rs
This gives us a simple way to generate an AST, which is potentially useful for things like testing.
(want this for a test for #1121)
> [fea-rs] Make parse_string return ParseTree

- glyphs-reader/src/font.rs
_I'm trying to clean this module up a bit; this is a preliminary PR to just doublecheck my understanding_
As I understand it 'Raw' means something parsed right out of the plist data, and these types do not seem to conform to this, and they are only used in types that are themselves not raw.
> [glyphs] Remove 'Raw' from non-raw type names

- fontbe/src/glyphs.rs
This declares a few local variables that lets us cleanup log strings by using more inline format strings.
No functional change, JMM
> [fontbe] Minor cleanup in CheckedGlyph

- fontbe/src/cmap.rs
- fontbe/src/features/kern.rs
- fontbe/src/metrics_and_limits.rs
- fontbe/src/os2.rs
- fontir/src/glyph.rs
- fontir/src/orchestration.rs
- glyphs2fontir/src/source.rs
saves needing to manually create a `WorkId` everytime.
> [fontir] Add get_glyph convenience method

- fontc_crater/src/ci/html.rs
I find myself counting targets impacted using find, make crater do it for me.
JMM if happy
> Add a count of targets impacted by tag

- fontir/src/glyph.rs
I'm trying to wrap my head around #1146
> Exploratory fix for non-deterministic processing of mixed contours and paths

- resources/scripts/requirements.txt
Notably the https://github.com/fonttools/fonttools/issues/3703 fix
JMM
> Update crater deps to pickup FontTools 4.55.1

- fea-rs/src/compile/tables/name.rs
Makes `python resources/scripts/ttx_diff.py 'https://github.com/marcologous/hanken-grotesk#sources/HankenGrotesk.glyphs'` `name` identical.
We filter out names for unknown encodings so hopefully filtering out blank ones is also fine.
JMM if happy
> Avoid adding blank names

- README.md
Bake the entire run and compare branches process into the command
JMM if happy.
> Update README.md hyperfine example

- fontbe/src/os2.rs
- fontc/src/lib.rs
- fontir/src/ir.rs
- resources/testdata/FontInfo-Regular.ufo/fontinfo.plist
- ufo2fontir/src/source.rs
Helps with `python resources/scripts/ttx_diff.py 'https://github.com/wix/wixmadefor#sources/WixMadeforText-SemiBoldItalic.ufo'`
JMM if happy
> Obey source OS/2 family class

- fontc_crater/src/ci.rs
And also log the error kind  when we can't load a repo.
> [crater] Log whether or not auth token is present

- fontbe/src/features/marks.rs
We handle this correctly everywhere else, but were not doing it here.
JMM
> Don't encode all-zero LigCaret deltas

- .github/workflows/rust.yml
Try not to backslide on wasm support (#1215 )
JMM
> Add a wasm check for the parts that currently work

- fea-rs/test-data/fonttools-tests/GPOS_2.expected_diff
I forgot to push a commit clarifying a comment in #1231.
JMM
> [fea-rs] Fixup comment on lookup sort order

- .github/workflows/rust.yml
- fea-rs/src/compile/compiler.rs
- fea-rs/src/compile/opts.rs
- fea-rs/src/parse.rs
- fea-rs/src/parse/context.rs
- fea-rs/src/parse/grammar/mod.rs
- fea-rs/src/parse/source.rs
- fea-rs/src/tests/compile.rs
- fea-rs/src/util/highlighting.rs
- fea-rs/src/util/ttx.rs
- fontbe/src/features.rs
- fontbe/src/features/marks.rs
By removing use of `OsStr(ing)?`
Also add the rust.yml checks to prove it
Another step toward building fontc for wasm (#1215)
> Make fea-rs build for wasm with serde enabled

- glyphs2fontir/src/source.rs
After discussion, this is slightly better semantically; per the spec four spaces means 'null', so we will treat that as if there was no value set.
see discussion at https://github.com/googlefonts/fontc/pull/1232#issuecomment-2631430587
> [glyphs] Just filter out all-space vendor id

- .github/workflows/rust.yml
- Cargo.toml
- ufo2fontir/src/toir.rs
> Move to norad 0.15.0, prove that makes fontc build for wasm32-unknown-unknown

- fea-rs/src/common/glyph_class.rs
- fontbe/src/orchestration.rs
I've needed this a few times during debugging and it's currently sitting in a stash, so I think it's worth just having in tree?
JMM if no objections
> Add KernPair::contains

- Cargo.toml
- fontbe/src/metrics_and_limits.rs
- fontbe/src/os2.rs
- fontc/src/lib.rs
This brings in a delta encoding fix that should give us a little crater boost.
JMM
> [chore] Update fontations

- fontbe/src/features/kern.rs
Simplify the logic around KernFragment, converting them to pairs earlier on.
JMM
> [fontbe] Minor cleanup in kern.rs

- fontbe/src/features/kern.rs
on top of #1246, this adds more tests for kerning.
> [kern] Port more tests from fonttools

- fontbe/src/features/kern.rs
- fontbe/src/features/ot_tags.rs
This seems simple enough, and is passing the fonttools tests.
> Compile the 'dist' feature

- resources/scripts/requirements.txt
> [chore] Update python requirements

- resources/scripts/ttx_diff.py
follow up from #1254: that PR reordered the input sequence, but not the backtrack or lookahead sequences.
Gives us another +1 on crater.
I imagine I'll have to also make this handle GPOS chain contexts too, but I'll wait until it shows up in a diff.
> [ttx_diff] Also reorder lookahead & backtrack values

- resources/scripts/ttx_diff.py
I figured we'd have to do this, but I ran into a font that showed the issue, so here we are.
JMM
> [ttx_diff] Also reorder class-based pos contexts

- glyphs-reader/src/font.rs
- glyphs2fontir/src/source.rs
Update name and add ref per https://github.com/googlefonts/fontc/pull/1272#issuecomment-2659150063
JMM
> Fix name and add ref

- .github/workflows/rust.yml
- resources/scripts/tidy_glyphs.py
As suggested in https://github.com/googlefonts/fontc/pull/1279#issuecomment-2659853798
JMM
> CI for .glyphs tidyness

- fontbe/src/features.rs
- fontc/src/lib.rs
- ufo2fontir/src/source.rs
> [chore] Clippy day

- fontc_crater/Cargo.toml
> [chore] Bump version on google-fonts-sources

- glyphs-reader/src/plist.rs
This will now handle unicode escapes, including surrogate pairs. Will error on unpaired surrogate pairs.
In the process of this work I noticed a few other omissions related to string parsing; the major one is that the reference impl supports the use of single quotes to delimit strings. This doesn't seem to be in any of our sources, but it might be worth fixing now?
> [glyphs] Improve parsing of escape sequences

- fontbe/src/features.rs
- fontbe/src/features/kern.rs
- fontbe/src/features/marks.rs
- fontbe/src/features/properties.rs
- fontbe/src/orchestration.rs
- fontc/src/lib.rs
This was one of the big things that was missing from layout, and gives us a healthy bump on crater.
- closes #1086
> Generate abvm & blwm features

- glyphs-reader/data/update.py
my vscode likes to run black (ruff) autoformatter automatically on save, which skews diffs since I want to touch this file
JMM
> blacken glyphs-reader/data/update.py

- fontc_crater/README.md
> [crater] Document how to run CI locally

- fontc_crater/README.md
> [crater] Fixup readme to use targets.json

- fontc_crater/Cargo.toml
> [crater] Update google-fonts-sources

- glyphs-reader/src/font.rs
- glyphs-reader/src/plist.rs
- resources/testdata/glyphs3/COLRv1-grayscale.glyphs
After this and #1316 we compile FoldIt w/o error again.
JMM but only after #1316
> Parse .glyphs grayscale colors

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/feature_writer.rs
This reworks how we merge external lookups to try and precisely model the logic of the ufo2ft FeatureWriter system.
This tries to simplify the flow by handling the features in groups, reflecting the different feature writers: we do `curs` (which is trivial) and then we do `dist` and `kern`, and then we do `abvm`, `blwm`, `mark`, and `mkmk`. Overall I think this is much easier to follow.
> [fea-rs] Replicate feature writer insert logic

- resources/scripts/ttx_diff.py
Although we now match fonttools for the assignment of _lookup_ ids, we can differ for the ids of mark filtering sets, because these ids are assigned when the lookup is created and are not remapped later.
The order of these ids doesn't matter, just that they are referenced correctly in the various lookups; and that is handled by normalizer.
JMM
> [ttx_diff] Sort mark filter sets in GDEF

- fontbe/src/features/marks.rs
This was tricky; in the original code I missed that:
- we bind the global set of abvm scripts to `scriptsUsingAbvm` (https://github.com/googlefonts/ufo2ft/blob/16ed156bd6a8b9bc/Lib/ufo2ft/featureWriters/markFeatureWriter.py#L1121)
- then we union that with feaScripts, if they exist (https://github.com/googlefonts/ufo2ft/blob/16ed156bd6a8b9bc/Lib/ufo2ft/featureWriters/markFeatureWriter.py#L1127)
- but then later on we use the original unfiltered set to determine the set of _non_ abvm glyphs, i.e. we have both `scriptsUsingAbvm` and `self.scriptsUsingAbvm` in scrope, and they have different values (https://github.com/googlefonts/ufo2ft/blob/16ed156bd6a8b9bc/Lib/ufo2ft/featureWriters/markFeatureWriter.py#L1133)
...so basically  another eventful day in the font mines.
> [marks] Fix tricky logic in abvm glyph splitting

- fontbe/src/features/marks.rs
Crazy how you just need to omit one little character and type one incorrect word and _everything_ falls apart.
JMM
> [marks] Fix abvm script logic, again

- fontbe/src/features/marks.rs
It's not totally clear that this is unnecessary, but it matches the current behaviour of fonttools and it isn't _wrong_, so we go with that.
(the existing logic _was_ trying to do this, and was just wrong)
> [marks] Unreachable glyphs go into non-abvm

- Cargo.toml
This brings in a fix for a crash during IUP calculation.
JMM
> [chore] Update write-fonts

- fontbe/src/features/properties.rs
I'm not sure the ufo2ft behaivour is totally right, but I think it makes sense to match it for the time being. I've opened an issue to discuss, and if ufo2ft changes their implementation we can revert this.
> [features] Match ufo2ft when classifying glyphs

- fontbe/src/features/kern.rs
- fontbe/src/features/marks.rs
- otl-normalizer/src/common.rs
- add simple line breaking for the script/lang items (this just makes stuff easier to read)
- print a newline after the header (this was an omission)
JMM
> [normalizer] Tweak header format

- resources/scripts/requirements.txt
This will flush the crater cache.
JMM
> [chore] Update python packages

- glyphs-reader/src/font.rs
This is a special case in glyphsLib that we had overlooked.
This shouldn't change much right now but in combination with the 'skipping feature generation for features that were manually declared' it was causing a significant regression. (I'll have that patch up again shortly)
> [glyphs] Manual kern feature always has insert mark

- fontbe/src/features/marks.rs
The same logic as with kerning, but applied to mark, mkmk, abvm, blwm and curs.
> [marks] Skip mark features if present in manual FEA

- fea-rs/src/compile/lookups/helpers.rs
- glyphs-reader/src/font.rs
- resources/scripts/check_no_println.sh
Because one snuck in. If this is failing correctly I'll add a commit to remove the offenders.
> [chore] Update check_no_println to check for dbg!

- fontbe/src/features/marks.rs
- fontbe/src/features/properties.rs
That is, the 'unicode_is_abvm' fn should return 'None' if it is associated with the common script, otherwise true/false based on whether or not any of the other scripts are in the abvm list.
...inching ever closer...
> [marks] Match *ternary* logic in abvm glyph splitting

- fontc_crater/src/ci.rs
Currently, we decide whether or not crater should run by checking if any of the fontc git revision, pip freeze output, or target list sha have changed; and then after a run has finished, we will post an update if the run's results differed at all from the previous run.
This has an annoying side effect: if we push a new commit to fontc that doesn't cause any change observable to crater, we will never post an update, which means we will keep doing full, useless runs (because the git revision of the last run never changes).
This patch changes that behaviour: now if a run produces the same output as the previous run, we will update the summary file, but we will reuse the results file of the previous run; this saves us writing a bunch of redundant bytes, but means the crater summary will …
> [crater] Always update summary after run

- glyphs-reader/src/glyphdata_bundled.rs
Was suposed to go with prior PR but I cleverly made the change on a branch.
JMM
> PhantomData was lost. Ghostly. Spectral. Make it real.

- glyphs-reader/src/glyphdata_bundled.rs
Bug courtesy of #1352 
Restores things like `python resources/scripts/ttx_diff.py 'https://github.com/JAMO-TYPEFACE/Orbit#Sources/Orbit.glyphs'` to passing instead of kerploding.
JMM
> Fix bug where I cleverly wanted a usize to take on negative value

- fontbe/src/stat.rs
- fontc/src/lib.rs
- resources/testdata/CustomStatInFea.ufo/features.fea
- resources/testdata/CustomStatInFea.ufo/glyphs/contents.plist
- resources/testdata/CustomStatInFea.ufo/layercontents.plist
- resources/testdata/CustomStatInFea.ufo/metainfo.plist
We will assume that if this exists it is correct, and use it without question.
This is based on #1369, which helps me keep the test simple.
- progress on #1364
- cc @Hoolean
> Use STAT table from FEA if present

- resources/scripts/ttx_diff.py
This 'densifies' gvar deltas, filling in any that are skipped because of IUP; this will account for the fact that our delta sets sometimes elide a different set of points than varLib's.
JMM
> [ttx_diff] Normalize gvar

- glyphs2fontir/src/source.rs
This entry is currently skipped by glyphsLib.
JMM
> [glyphs] Ignore "variationsPostScriptNamePrefix" name

- resources/scripts/ttx_diff.py
Elsewhere we make sure that name ids are replaced with the actual string value for those names; this makes sure that we also normalize names _within_ the name table.
JMM
> [ttx_diff] Normalize name ids in the name table

- fea-rs/src/parse/source.rs
> [clippy] Roll the rock etc

- resources/scripts/requirements.txt
This brings in a fonttools update
JMM
> [ttx_diff] Update python requirements

- glyphs-reader/src/font.rs
This is no functional change, just my effords to make things a bit more idiomatic as I work out how the logic works here.
JMM
> [glyphs] Tiny bit of cleanup in v2->3 name logic

- resources/scripts/ttx_diff.py
- skip gftools build if possible (this is a bug, we were not respecting the --rebuild flag for gftools-driven builds)
- more informative logging of gvar densification
JMM
> [ttx_diff] Fixups

- glyphs2fontir/src/erase_open_corners.rs
We were sorting these in the reverse order that fonttools was, and in certain fonts (generally with outlines that are generated automatically from bitmaps, from the looks of it) we do have funny curves that produce multiple intersections during corner erasure.
This doesn't increase our 'identical' number, but it does improve the `glyf` diffs for a bunch of fonts.
> [glyphs] open corners: match fonttools if multiple hits

- fontbe/Cargo.toml
- fontbe/src/features/kern.rs
- fontbe/src/features/marks.rs
- fontbe/src/features/properties.rs
- fontc_crater/Cargo.toml
- glyphs-reader/Cargo.toml
> [chore] Update some deps

- glyphs-reader/src/font.rs
This is no functional change, but I need this to be reusable for a subsequent patch.
JMM
> [glyphs] Add method for getting RawName value

- glyphs-reader/ascii_plist_derive/Cargo.toml
Taking the liberty of self-merging in the spirit of version bumps being a self-merge
> Add repository for ascii_plist_derive

- fontir/src/ir.rs
Specifically the typographic names are only cleared if _both_ the family and subfamily are identical to their typographic variants.
---
I spent a while trying to get a test written for this but it's oddly tricky to craft a small source file that expresses the problem, and hopefully it's easy enough to check the referenced python and see that we're matching.
JMM
> [fontir] More closely match ufo2ft when clearing names

- fontir/src/ir.rs
- fontir/src/ir/static_metadata.rs
No functional change, just cleaning this up a bit before I add stuff for rvrn/FeatureVariations
JMM
> [fontir] Move StaticMetadata (& related) to module

- fontc/Cargo.toml
- fontc/src/lib.rs
- glyphs2fontir/src/source.rs
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Bold.ufo/fontinfo.plist
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Bold.ufo/glyphs/A_.glif
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Bold.ufo/glyphs/contents.plist
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Bold.ufo/glyphs/doesnt_matter.glif
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Bold.ufo/glyphs/space.glif
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Bold.ufo/layercontents.plist
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Bold.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Bold.ufo/metainfo.plist
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Regular.ufo/fontinfo.plist
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Regular.ufo/glyphs/A_.glif
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Regular.ufo/glyphs/contents.plist
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Regular.ufo/glyphs/doesnt_matter.glif
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Regular.ufo/glyphs/space.glif
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Regular.ufo/layercontents.plist
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Regular.ufo/lib.plist
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported-Regular.ufo/metainfo.plist
- resources/testdata/designspace_from_glyphs/IncompatibleUnexported.designspace
- resources/testdata/glyphs2/IncompatibleUnexported.glyphs
- resources/testdata/glyphs3/IncompatibleUnexported.glyphs
- ufo2fontir/src/toir.rs
Fixes #1397 
I'll add (failing) tests first to reproduce the issue, then follow up with the simple fix
> Ignore anchors from non-exportable glyphs

- glyphs-reader/data/update.py
My editor keeps auto-formatting this file I'm touching, so it's better to commit the `black` changes seperately to avoid noise
JMM
> run black on glyphs-reader/update.py

- resources/scripts/ttx_diff.py
> [ttx_diff] run black

- fontbe/src/features.rs
- fontbe/src/features/kern.rs
- fontbe/src/features/marks.rs
- fontbe/src/features/test_helpers.rs
... which seems like a nice alternative to writing the same basic thing for the third time.
No functional change, JMM
> [fontbe] Add common harness for testing layout providers

- fontbe/src/features.rs
- fontbe/src/fvar.rs
- fontbe/src/mvar.rs
- fontbe/src/test_util.rs
- fontdrasil/src/types.rs
- fontir/src/ir/static_metadata.rs
- fontir/src/variations.rs
There were a number of different helper methods doing the same thing; this combines them where possible.
No functional change.
JMM
> Simplify creating Axes for testing

- fontir/src/ir.rs
This matches ufo2ft's behaviour which relies on [funky implicit Python `bool`-ness](https://github.com/googlefonts/ufo2ft/blob/fca66fe3ea1ea88ffb36f8264b21ce042d3afd05/Lib/ufo2ft/outlineCompiler.py#L613-L616), but which is likely intentional as an explicit x-height of zero [gets special mention in the spec](https://learn.microsoft.com/en-us/typography/opentype/spec/os2#sxheight). In all other cases ufo2ft uses the explicit x-height, [but also its implicit fallback](https://github.com/googlefonts/ufo2ft/blob/fca66fe3ea1ea88ffb36f8264b21ce042d3afd05/Lib/ufo2ft/outlineCompiler.py#L569), with this PR adding that latter case too.
> Only derive strikeout position from UPM when x-height is explicitly zero

- glyphs-reader/src/font.rs
I found the raw i64 here a bit confusing, (it turns out that our plist derive code uses `Default::default()` to fill in any missing values) and bracket layer parsing depends on the format version.
> [glyphs] Add FormatVersion type

- glyphs2fontir/src/source.rs
This was duplicating the glyph order that already exists in the font object.
JMM
> [glyphs] Remove redundant glyph_names map

- fontc_crater/src/ci.rs
Since changes in ttx_diff can impact the compiled font.
> [crater] Clear caches if ttx_diff changes

- resources/scripts/ttx_diff.py
previously (https://github.com/googlefonts/fontc/pull/1254) we were reassigning class ids within ClassDef following fonttools sorting behavior (which uses glyph names). But since the glyph names can change when we apply production names (#1430), and this sorting by name in ttx_diff happens only after glyphs were renamed (whereas in fontTools.otlLib the sorting occurs with the original names), this creates spurious diffs...
So it's preferable that ttx_diff normalization makes the fontmake font match fontc' instead, which means sorting classes of equal length by the minimum glyph index of their members.
> ttx_diff: reorder classdef ids like fontc (using min gid)

- fontdrasil/src/types.rs
- glyphs-reader/src/font.rs
- glyphs2fontir/src/source.rs
- resources/testdata/glyphs2/WorkSans-minimal-bracketlayer.glyphs
- resources/testdata/glyphs3/LibreFranklin-bracketlayer.glyphs
This is the first step towards handling glyph variations for glyphs sources.
This patch on its own doesn't do anything; the compilation logic is coming in a separate patch, because it's fiddly and deserves attention.
> Parse bracket layers

- fontbe/src/post.rs
- fontc/src/lib.rs
- fontir/src/ir/static_metadata.rs
- glyphs-reader/src/font.rs
- glyphs2fontir/src/source.rs
- ufo2fontir/src/source.rs
Should fix #248
(unit tests coming after lunch)
> support 'Don't use Production Names' custom param and useProductionNames UFO lib key

- glyphs-reader/src/glyphdata.rs
when constructing the production names for glyphs with some suffix, if the data already has a production name for the base glyph name (without the suffix), we can just use that one plus the suffix.
this fixes a bunch of ttx diffs in the prod names of Fustat.glyphspackage and MarkaziText.glyphs which I mentioned in https://github.com/googlefonts/fontc/issues/248#issuecomment-2880365737
I am working on more bug fixes, but this cheap one can already shave some known diffs.
> glyphdata: fix production names with suffix

- fontc/src/lib.rs
- fontir/src/glyph.rs
- fontir/src/ir.rs
- fontir/src/orchestration.rs
- glyphs-reader/src/font.rs
- glyphs2fontir/src/source.rs
- glyphs2fontir/src/toir.rs
- resources/testdata/glyphs2/WorkSans-minimal-bracketlayer.glyphs
Reverts googlefonts/fontc#1438
This was a regression for a bunch of fonts on crater, and I'd like to investigate exactly what was changed from the original PR.
> Revert "Generate bracket glyphs"

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/test-data/compile-tests/mini-latin/bad/ligature_duplicate.ERR
- fea-rs/test-data/compile-tests/mini-latin/bad/ligature_duplicate.fea
This matches AFDKO and fonttools.
see https://github.com/fonttools/fonttools/pull/3835
> [fea-rs] Error on conflicting lig sub rules

- fea-rs/src/token_tree/token.rs
I want to hover over these tokens and know which lookup kind is which 🤷 
JMM
> [fea-rs] Add some docs

- fea-rs/test-data/fonttools-tests/CursivePosSubtable.fea
- fea-rs/test-data/fonttools-tests/CursivePosSubtable.ttx
- fea-rs/test-data/fonttools-tests/MarkBasePosSubtable.fea
- fea-rs/test-data/fonttools-tests/MarkBasePosSubtable.ttx
- fea-rs/test-data/fonttools-tests/MarkLigPosSubtable.fea
- fea-rs/test-data/fonttools-tests/MarkLigPosSubtable.ttx
- fea-rs/test-data/fonttools-tests/MarkMarkPosSubtable.fea
- fea-rs/test-data/fonttools-tests/MarkMarkPosSubtable.ttx
- fea-rs/test-data/fonttools-tests/class_pair_pos_duplicates.fea
- fea-rs/test-data/fonttools-tests/class_pair_pos_duplicates.ttx
- fea-rs/test-data/fonttools-tests/contextual_inline_format_4.fea
- fea-rs/test-data/fonttools-tests/contextual_inline_format_4.ttx
- fea-rs/test-data/fonttools-tests/duplicate_language_stmt.fea
- fea-rs/test-data/fonttools-tests/duplicate_language_stmt.ttx
- fea-rs/test-data/fonttools-tests/duplicate_lookup_reference.fea
- fea-rs/test-data/fonttools-tests/duplicate_lookup_reference.ttx
- fea-rs/test-data/fonttools-tests/single_pos_NULL.fea
- fea-rs/test-data/fonttools-tests/single_pos_NULL.ttx
- fea-rs/test-data/fonttools-tests/variable_mark_anchor.ttx
- fea-rs/test-data/fonttools-tests/variable_scalar_anchor.ttx
- fea-rs/test-data/fonttools-tests/variable_scalar_valuerecord.ttx
This includes a bunch of updates from fonttools that we are handling correctly. (There are some failures that can be addressed individually.)
JMM
> [fea-rs] Update fonttools test cases

- Cargo.toml
- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/validate.rs
- fea-rs/test-data/compile-tests/mini-latin/bad/lookup_mixed_rules.ERR
- fea-rs/test-data/compile-tests/mini-latin/bad/lookup_mixed_rules.fea
- fea-rs/test-data/compile-tests/mini-latin/good/mixed_single_and_liga.fea
- fea-rs/test-data/compile-tests/mini-latin/good/mixed_single_and_liga.ttx
- fea-rs/test-data/fonttools-tests/spec8a.ttx
This behaviour was changed in fontools in https://github.com/fonttools/fonttools/pull/3805; this patch gets us caught up.
This should get us another +something on crater.
> merge mixed lig and single sub rules

- resources/scripts/ttx_diff.py
> [ttx_diff] Normalize postscriptNameID and ValueNameID values

- resources/scripts/ttx_diff.py
Replace the user-defined name IDs with a constant "USER_ID" since the ID itself is uninteresting. Then sort the name records by their attributes, since the order in the name table is also uninteresting.
Fixes #1471
> [ttx_diff] Improve name table normalization

- fontbe/src/features.rs
This didn't seem to be doing anything? @rsheeter what would we actually like to see, here?
> [fontbe] Clean up old timing code

- fontir/src/feature_variations.rs
It's possible for the design coordinates to be out of bounds, in which case the normalized coordinates can be out of bounds.
JMM
> Ensure normalized coords are clamped during overlay

- resources/scripts/requirements.txt
https://github.com/fonttools/fonttools/releases/tag/4.58.1
> update fonttools in requirements.txt

- fontir/src/variations.rs
Adds a test showing a potentially useful application of the variation code
> New variation model test exhibiting computation of a final value

- ufo2fontir/src/source.rs
Fixes https://github.com/googlefonts/fontc/issues/1505
we were previously treating the absence of public.postscriptNames lib key in a UFO the same way as an empty mapping, however fontmake (ufo2ft) distinguishes this and by default treats the absence of explicit postscriptNames as a signal to do no glyph renaming (not even stripping invalid PS characters like hyphens).
/cc @tphinney
> [ufo2fontir] keep nice glyph names when no public.postscriptNames was provided

- resources/scripts/requirements.in
- resources/scripts/requirements.txt
Includes these changes:
https://github.com/googlefonts/fontmake/releases/tag/v3.10.1
https://github.com/googlefonts/ufo2ft/releases/tag/v3.4.6
Fixes https://github.com/googlefonts/fontc/issues/1507
> Bump fontmake and ufo2ft in requirements.txt

- glyphs2fontir/src/source.rs
- resources/testdata/glyphs3/bracket-glyph-order.glyphs
This was causing a minor glyph order difference in some fonts.
JMM
> [glyphs] Add bracket glyphs in lexicographic order

- fontbe/src/fvar.rs
- fontbe/src/stat.rs
- fontc/src/lib.rs
- fontir/src/ir/static_metadata.rs
- resources/testdata/glyphs3/DuplicateNames.glyphs
> only allow default named instance to reuse nameID 2/17, use >= 256 for anything else

- glyphs2fontir/src/source.rs
- resources/testdata/glyphs3/bracket-rules-processed-in-glyph-order.glyphs
Instead of in alphabetical order by glyph name, which is what we get when we just iterate the map of glyphs.
This should give us a +small bump on crater.
> [glyphs] Process bracket rules in glyph-order-order

- resources/scripts/requirements.txt
brings in patches to ufo2ft, glyphslib, and fonttools.
JMM
> Update python deps

- fontdrasil/src/coords.rs
JMM
(this was annoying me while debugging something else)
> Simplify the debug repr of Coords

- resources/scripts/requirements.txt
https://github.com/googlefonts/glyphsLib/releases/tag/v6.11.4
JMM
> Update glyphsLib in requirements.txt

- resources/scripts/requirements.txt
To be merged 1 hour or so after #1575 so we can see any diffs specific to this
https://github.com/googlefonts/ufo2ft/releases/tag/v3.6.0
> Update ufo2ft in requirements.txt

- resources/scripts/requirements.txt
This reverts commit 2576f4575da32f0db1b14fafee1043472803ab42, reversing changes made to 77ca2251f5d5f4d816c1610c381dec1702c70e8c.
> Revert "Merge pull request #1576 from googlefonts/update-ufo2ft"

- fontir/src/glyph.rs
- fontir/src/ir.rs
This gives us a modest bump on crater.
Based on #1578.
> Skip non-export glyphs

- fontir/src/ir/static_metadata.rs
...where I had specified the wrong default flags in #1584 
JMM
> Unbreak head table

- resources/testdata/glyphs2/WghtVar_Avar.glyphs
- resources/testdata/glyphs2/WghtVar_Avar.glyphspackage/fontinfo.plist
- resources/testdata/glyphs3/GlobalMetrics_font_customParameters.glyphs
- resources/testdata/glyphs3/WghtVar_Avar.glyphs
- resources/testdata/glyphs3/WghtVar_Avar.glyphspackage/fontinfo.plist
Exhibits how to fix compile_glyphs_font_with_avar and strikeout_size_fallback
> Fix avar tests by writing all mappings in instances

- glyphs-reader/src/font.rs
- resources/testdata/glyphs2/master_missing_from_instances.glyphs
This more closely matches the behaviour in fonttools.
~(this patch is currently causing some other failures, opening it as a draft to figure out what's going on)~
> [glyphs] Don't combine mappings from masters & instances

- glyphs2fontir/src/erase_open_corners.rs
Specficially in the case where there are multiple intersections, the curve-curve implementation does not behave the same as the line/curve or line/line implementations.
In the latter, the first hit is always the one with the lowest `t` on the first segment; but in the case of segment/segment intersection, the order is based on the order in which recursion occurs.
The key here is to not sort the results, but to retain the order we get after recursion.
This should be worth another +2-4 on crater.
> [glyphs] Match glyphsLib for curve-curve intersections

- fontc_crater/src/ci/html.rs
Just a little QOL improvement, JMM
> [crater] Display icon beside items with annotation

- glyphs-reader/src/font.rs
That is, when building the axis mapping only consider axes that are defined in the font and then look for them in the master, instead of looking at the axes defined in the master and assuming that they exist in the font.
Gives us another +2-4.
JMM
> [glyphs] Treat the font axes as source of truth

- fontir/src/glyph.rs
This doesn't change anything functional, just a bit of refactoring to prepare for things like also interpolating component transforms.
JMM
> [ir] Clean up instance interpolation code

- fontir/src/glyph.rs
_based on #1657_
An upcoming fix to support decomposition of components with intermediate layers causes a bunch of these tests to fail (because some of the test data has multiple layers that are no longer ignored) and so this fixes all of that first so the other PR is cleaner.
> [ir] Cleanup glyph tests (no functional change)

- fontir/src/glyph.rs
We were making sure that the composite glyph was defined at the component glyph locations, but we were not actually using that updated glyph when we then went to make sure each component was defined at the appropriate locations.
There is a remaining issue with how we handle non-trivial affines, but this patch at least fixes a crash in a number of sources.
> [ir] Fix logic bug in decomposition

- resources/scripts/ttx_diff.py
ttx_diff output is made longer and harder to read by use of absolute paths. Try to print something closer to what a user would type, e.g. `~/.fontc_crater_cache` not `/usr/ate/a/donkey/near/rsheeter/.fontc_crater_cache`
> Use ~ not absolute for display of paths
